### ISSUE TITLE
Label Formatting

### ISSUE THREAD

**Issue by okyksl** [bounswe/bounswe2018group9#1]
In the `Meeting #1`, we decided to use label format `<Label-Header>:<Label-Name>` specified in the following article:

>  [Sane GitHub Labels – Dave Lunny – Medium](https://medium.com/@dave_lunny/sane-github-labels-c5d2e6004b63)

Suggested labels in the article are mostly adopted. We may need to incorporate additional labels according to our needs. This issue is designed to track additional discussion on **Label Formatting**.

**Comment by byklyci** [comment]
We can also add our tags " Priority:Critical " for the urgent things.

**Comment by serkan-ozel-2015400123** [comment]
I guess we already have priority: high somekind of label. I think it is enough for the purpose

**Comment by okyksl** [comment]
I'm closing the issue until the specifics of the project becomes clear. After that, we probably need to discuss additional set of labels to cover cases such as implementation platform. e.g `Platform: Node`.
