### ISSUE TITLE
Test Cases(Change Profile and Attend an event)

### ISSUE THREAD

**Issue by serkan-ozel-2015400123** [bounswe/bounswe2018group9#100]
I am going to plan these plan cases.

**Comment by okyksl** [comment]
@serkan-ozel-2015400123 wouldn't it be better to create separate issue for each test case?

**Comment by serkan-ozel-2015400123** [comment]
First version of attend event is ready.

**Comment by serkan-ozel-2015400123** [comment]
First version of change profile is also ready. I will divide the issue into two soon.

**Comment by byklyci** [comment]
I am closing because it is done.
