### ISSUE TITLE
Use Case Diagrams

### ISSUE THREAD

**Issue by nazmicancalik** [bounswe/bounswe2018group9#102]
Guys me and @akaogluozgur are working on Use case diagrams it will be ready tomorrow afternoon

**Comment by nazmicancalik** [comment]
Guys @akaogluozgur and I have made a somewhat final use case diagram. Here how it looks like:
![actopus](https://user-images.githubusercontent.com/25107149/38174438-a826b8b0-35d5-11e8-9095-b07b0dfe0081.png)

Ps: Tonight with the additon of @okyksl we will finalize the use case diagram and  put it on wiki page.

**Comment by okyksl** [comment]
Great work as usual @nazmicancalik @akaogluozgur!

**Comment by akaogluozgur** [comment]
The diagram is added our wiki page, [Use Case Diagrams](https://github.com/bounswe/bounswe2018group9/wiki/Use-Case-Diagrams)

**Comment by byklyci** [comment]
If the issue is done, please close it.Thanks for your effort.
