### ISSUE TITLE
What is annotation? (In general and in our case)

### ISSUE THREAD

**Issue by kemaltulum** [bounswe/bounswe2018group9#104]
Let me first give you the definition in Wikipedia:

> An `annotation` is a metadatum (e.g. post, explanation, markup) attached to location or other data.

Annotation is actually a very simple thing like highlighting the important lines in a text and adding extra notes. However, it is somewhat tricky to explain what annotation is for Actopus.

The definition of Annotation in our glossary is:

> Annotation: Explanatory content attached to an item.

Here is a short list of items we can add annotations for it:
* Location
* Related links (a web site or social media pages)
* Extra info about interesting things

Here is an example from eventbrite.
![event](https://user-images.githubusercontent.com/14013649/38176486-79420a86-35f8-11e8-9b83-0d2dc1613805.jpg)

Actually, I do not think that EventBrite utilizes annotations. But tags can be inspiring for us.

This is the [link](https://www.lucidchart.com/invitations/accept/6288c455-d1e6-41a3-bbe4-bc5a3ee81b12) for the sequence diagram of Add Annotation

**Comment by serkan-ozel-2015400123** [comment]
In the requirements annotations' definition is the same as the definition in the project description that you can find in the main directory of the repository. If you think it needs some changes can you tell us please, if you don't we can close this issue.

**Comment by kemaltulum** [comment]
I examined the related items in the requirement. Actually, they generally refer to the annotations only visible for search engines for improving the SEO performance of web pages. Such annotations are not necessarily editable or determined by end users, rather generated automatically or by hand, I don't know it depends. 

I am closing this issue, since we cannot decide on exact specifications of our annotation mechanism at the moment. When we are dealing with the requirements in the next semester, we can came back to this issue.
