### ISSUE TITLE
Contribution Guide

### ISSUE THREAD

**Issue by okyksl** [bounswe/bounswe2018group9#11]
We should build a contribution guide so that we all can easily check and decide how to contribute to the repo. It should include topics such as:

- [x] Issues
- [x] Commits
- [x] Workflow
  - [ ] Branching
  - [ ] Pulling & Pushing
  - [ ] Merging

Any inconsistencies in habits in such areas would make our job harder in the future. So I suggest we build a guide and stick to it.

**Comment by byklyci** [comment]
I added issues summary and guide in our contribution guide part. 
[Issues](https://github.com/bounswe/bounswe2018group9/wiki/Issues)

**Comment by nazmicancalik** [comment]
@okyksl Oğuz, just to check : Where are we on this issue? Is there anything we can do ? Also, as I asked at issue #3, should we make issues wiki page (on the sidebar) a bit smaller, like Meriç's idea about making our git page a bit smaller and concise.

**Comment by byklyci** [comment]
I added Issues last version on the sidebar.

**Comment by okyksl** [comment]
@nazmicancalik I'm unable to progress since we focused more on `Requirements Elicitation` process. I'll try to make progress as soon as possible.

**Comment by okyksl** [comment]
@nazmicancalik could you review the `Commits` section?

@byklyci can I revision `Issues` section a bit?

**Comment by nazmicancalik** [comment]
I checked out the `Commits` section and it seemed pretty good to me.  We can use this section as a good guideline. We can add new specifications if we need to as we go along. Thanks @okyksl :)

**Comment by okyksl** [comment]
I believe our `Contribution Guide` matured enough so that we can close this issue. As we are practicing **Agile Lifecycle**,  `Contribution Guide` should continue to evolve to reflect changes and needs in our project.
