### ISSUE TITLE
Complete Twitter API Project

### ISSUE THREAD

**Issue by kemaltulum** [bounswe/bounswe2018group9#119]
Hi everyone,

We did a good stuff on this project and each one of us has a separate branch working on it. However, we should merge our branches with TwitterAPI and resolve conflicts if they occur. This is because all the work shall be collected into the same place. 

Merging can be done basically with this process:

Run this command in your branch:
`git merge TwitterAPI`
This command brings the code changes from TwitterAPI branch to your branch.

Then the next step is making a pull request for merging your branch with TwitterAPI branch.

I know, there would be unclear things. Please ask them so that we can help each other.

I am also adding check boxes for everyone checking its work in TwitterAPI branch already.

* [x] Gökhan Tekel
* [x] Didem Öngü
* [x] Hamdi Özgür Akaoğlu
* [x] Nazmican Çalık
* [ ] İlyas Demirkıran
* [x] Yusuf Kalaycı
* [x]  Serkan Özel
* [x] Kemal Tulum
* [x] Galip Ümit Yolcu
* [x] Oğuz Kaan Yüksel

**Comment by serkan-ozel-2015400123** [comment]
Is this okay to be closed

**Comment by okyksl** [comment]
I believe we're done here. To be sure, let @kemaltulum close this issue as he overviewed the whole process.
As a note, if one wants to participate **API Documentation** or **Unit Testing**, our API is waiting you :)

**Comment by serkan-ozel-2015400123** [comment]
@kemaltulum  Can you close this please :)

**Comment by kemaltulum** [comment]
We were not done actually, I got the work of @gkhntkl and we are done.
