### ISSUE TITLE
Git Workflow

### ISSUE THREAD

**Issue by okyksl** [bounswe/bounswe2018group9#12]
According to our `Meeting #2`, I'm organizing the Git Workflow of our repository.

* `master` branch is now protected. Any commits must be made from non-protected branches and submitted via pull-request. I will routinely review the PRs.
* **Feature-branch workflow** is adopted. Documentation on the workflow will be available on `Wiki`. 
* Additionally, `master` branch is cleaned and now uses [Ionic Repository](https://github.com/ionic-team/ionic) commit styles.

**Comment by byklyci** [comment]
* `master` branch protection is a good way to avoid some mistakes and conflicts. This is a remarkable newness of our project.Thank you.

**Comment by gumityolcu** [comment]
I am closing the issue since there is nothing to discuss here and the issues page is very crowded 😃

**Comment by okyksl** [comment]
We're using PRs very well until now, in the long run it will be even more beneficial. _Documentation_ part of this issue will be tracked on #11.
