### ISSUE TITLE
Project Overhaul

### ISSUE THREAD

**Issue by okyksl** [bounswe/bounswe2018group9#120]
So far we have managed to create high quality and creative work on wide-variety of subjects throughout the _Software Engineering_ landscape. I believe we all tried our best to do each task as good as possible with a sense of responsibility. We devised tools that we may utilize, we reflected on ourselves and our works a lot, we researched and studied a lot, we reviewed our work to make it meaningful and useful for later stages of our project lifetime, we even spend a lot of time on our work just to achieve ourselves' high standards while keeping deadlines and expectations of our **Boss** in mind.

However, we also had some shortcomings whether it is quality of work or in terms of presentation. As all teams exhaust, remember that we are a new team where each member has almost null experience on _Software Engineering_, we started to drained away energy wise and that restlessness led to a framework where we tend to forget mindfulness and awareness in our project and in repository, where we stopped to be curious about what we're doing. This framework we jumped into without realizing caused us to move without a plan, intention or goal. Nonetheless, keep in mind this is **exactly** what was expected on **this course** and this is **exactly** what we're supposed to **learn and cope** with. We're not simply learning theoretical and practical knowledge of _Software Engineering_ but also soft skills that are vital to any person including _planning, time management, goal management, organization, communication, reflection, synchronization and coherence_. These are the kinds of things **everyone** has trouble with and thus it is very normal that we're having problems on these topics.

With that being said, I believe all of us want to create a project where we can understand and practice _Software Engineering_ thorough and create a product which we later on reflect back and enjoy. While we're doing our project, we have ability to explore and improve our skills' not only on _Software Engineering_ and also soft skills that I was referring. It seems to me that we can develop something useful and fun while we're developing ourselves.

I would like to know your thoughts on this general perspective. Are there anything you @bounswe/bounswe2018group9 guys like to add or share? Do you agree or disagree with observations here? What can we do to improve our team's framework?

**Comment by akaogluozgur** [comment]
I strongly agree with you. As you say above, I think what we should do first is improving our feedback and reflection mechanism. ( This can be done by increasing communication among our teammates. Thus we can follow and back up each other.)
