### ISSUE TITLE
Status Report #1 - Meetings

### ISSUE THREAD

**Issue by okyksl** [bounswe/bounswe2018group9#123]
I'm waiting your valuable comments & review on [Status Report #1 - Meetings](https://github.com/bounswe/bounswe2018group9/wiki/Status-Report-%231-Meetings). Here is a checklist to track our review status:

* [ ] Gökhan Tekel
* [ ] Didem Öngü
* [ ] Hamdi Özgür Akaoğlu
* [ ] Nazmican Çalık
* [ ] İlyas Demirkıran
* [x] Yusuf Kalaycı
* [x]  Serkan Özel
* [ ] Kemal Tulum
* [x] Galip Ümit Yolcu
* [x] Oğuz Kaan Yüksel

**Comment by byklyci** [comment]
Your writing skills are amazing.Thanks for this good job. @okyksl
