### ISSUE TITLE
Milestone Review #4.1

### ISSUE THREAD

**Issue by okyksl** [bounswe/bounswe2018group9#124]
I added [Requirement Analysis Grooming](https://github.com/bounswe/bounswe2018group9/wiki/Requirement-Analysis-Grooming) page to make [Requirement Analysis](https://github.com/bounswe/bounswe2018group9/wiki/Requirement-Analysis) maintenance more easier. If you have time, please consider any consistency & coherence problems, missing items and possible improvements in our [Requirement Analysis](https://github.com/bounswe/bounswe2018group9/wiki/Requirement-Analysis)  document and add them into  [Requirement Analysis Grooming](https://github.com/bounswe/bounswe2018group9/wiki/Requirement-Analysis-Grooming) page. 

I certainly **need second-eye and a third-eye** since the scope of the [Requirement Analysis](https://github.com/bounswe/bounswe2018group9/wiki/Requirement-Analysis) is huge. I think it is helpful for us to make a readable and understandable [Requirement Analysis](https://github.com/bounswe/bounswe2018group9/wiki/Requirement-Analysis) for the upcoming semester and I think [Requirement Analysis](https://github.com/bounswe/bounswe2018group9/wiki/Requirement-Analysis) is really the base for the many things we develop in our project. Thus, forming a solid [Requirement Analysis](https://github.com/bounswe/bounswe2018group9/wiki/Requirement-Analysis) is one of the key points to succeed in this project.

_As a side note_:
I think appropriate **grooming** files would be beneficial for maintaining certain documents. Also, we can consider a main **Backlog** file for our _agile workflow_.

**Comment by serkan-ozel-2015400123** [comment]
Also why the number of this milestone is 4.1?

**Comment by serkan-ozel-2015400123** [comment]
An issue about 1.1.1.4 and my suggestion 
issue: 

> [specification] What is public content? Is user allowed to search?

suggestion:

> About public content. Users choose an events visibility: it is either public or private to a group. We also add the **group** feature to the system. A group is a collection of users and every event posted to this group is only visible by this group's members. **Therefore, guest users can see/search public content by cannot attend to see the announcements or very details of the event.** However, they cannot search any private content i.e group events.

**Comment by serkan-ozel-2015400123** [comment]
> 1.1.3.1.1. -> 1.1.3.3.1. [category]

can you explain the purpose of this adjustment  Oğuz? I think these two requirements are different if you mean to combine them or categorize under same category.

About  these points 

>   1.1.3.3. Timeline [specification] users shall be able to see that users content
>  1.1.3.3. Timeline [organization] accumulate posting into more sensible structure

I changed timeline. It is all about the history of events that a user attended now.

> 1.1.3.3.6. -> 1.1.4.3. [category] 
What is the point here there are not such requirements do you mean to write them in this manner

**Comment by serkan-ozel-2015400123** [comment]
1.1.4.4. [missing]  Users shall be able to get event recommendations based on their information on the system (event history, user they follow, their interests)

You stated this, we have something like this in system requirements but what can be added is, users' choice of taking recommendation or not.  This can be added under profile section I guess.

**Comment by serkan-ozel-2015400123** [comment]
> 1.1.4.5. [missing] Users shall be able to see his/her followed users' timeline content in a time based order.

Should a user be able to see only his followed users' timeline or all of the users who give this permittion to the system?

**Comment by serkan-ozel-2015400123** [comment]
> 1.1.4. [specification] add comment & vote & share specific actions

Yeah this is right. I was confused feed with timeline. Now, I conclude timeline is about history, feed is like twitter main page.

**Comment by serkan-ozel-2015400123** [comment]
Organization is done to requirements analysis, I am doing enumeration now.

**Comment by okyksl** [comment]
@serkan-ozel-2015400123 I believe you cleared out most of the requirement items I was concerned with, great work! If there are anything remaining, could you please reword below? I would like to clarify these two main points:

* [Requirement Analysis Grooming](https://github.com/bounswe/bounswe2018group9/wiki/Requirement-Analysis-Grooming) is a secondary document for [Requirement Analysis](https://github.com/bounswe/bounswe2018group9/wiki/Requirements-Analysis) where we list possible additions and problematic items. When we have considered some item listed with it, what we wish is _mark that item into a done state and move it to the appropriate section_. In that sense, [Requirement Analysis Grooming](https://github.com/bounswe/bounswe2018group9/wiki/Requirement-Analysis-Grooming) is a **living document** which tracks the status of the [Requirement Analysis](https://github.com/bounswe/bounswe2018group9/wiki/Requirements-Analysis) document. I wanted to clarify this, because I see a [Requirement Analysis New Grooming Page](https://github.com/bounswe/bounswe2018group9/wiki/Requirement-Analysis-New-Grooming-Page) which I believe a misunderstanding of the intended purpose of [Requirement Analysis Grooming](https://github.com/bounswe/bounswe2018group9/wiki/Requirement-Analysis-Grooming).
* I don't think we have a fully practiced **agile** workflow. However, I think that one of the points we had in our class is that agile workflow is becoming more popular and it is more suitable for software development projects due to their _agile_ nature :) I believe most of the suggested tendencies about workflow from **The Boss** in class are also encouraged in agile workflow. Further, it seems to me that its hard to label any kind of workflow in any project so strictly as _agile_ or _waterfall_ or _something_. There are layers of adoption to _agile_ or any _workflow style_. So, I would say there is a _spectrum of workflows_, where in class we generally preferred the agile side of the spectrum and **The Boss** encourages agile workflow. I hope that clarifies my usage of the word agile, which is 
a bit broad and refers to dynamic, fluid, interactive workflows and habits we wish to employ. We could discuss why we're trying to handle and manage our project in the way we're currently and we could discuss what can be done to improve our management of the project.

And a suggestion, you could edit and append additional content to your comments for more readable discussion :)

**Comment by serkan-ozel-2015400123** [comment]
@okyksl  I understand you point about grooming page but I think we should start the grooming page from now on because I have revised everything in requirements and It is very hard to write every change to the grooming page. On the other hand, I think this version of the requirements is stable so let's start a fresh page of grooming page.

I will now write the report by the way in the format we agreed on.
