### ISSUE TITLE
Status Report #1 - Planning

### ISSUE THREAD

**Issue by gumityolcu** [bounswe/bounswe2018group9#127]
[Status Report #1 Planning](https://github.com/bounswe/bounswe2018group9/wiki/Status-Report-%231-Planning) is done. I will be reflecting and making additions to it if I can think of any. Like always, feel free to add your thoughts to it and leave a comment under this issue if you have questions, points to discuss, remarks etc.

Here is a checklist that I stole from @okyksl 's [Review #1 issue](https://github.com/bounswe/bounswe2018group9/issues/123) to track our review status:

* [ ] Gökhan Tekel
* [ ] Didem Öngü
* [ ] Hamdi Özgür Akaoğlu
* [ ] Nazmican Çalık
* [ ] İlyas Demirkıran
* [x] Yusuf Kalaycı
* [x]  Serkan Özel
* [x] Kemal Tulum
* [x] Galip Ümit Yolcu
* [ ] Oğuz Kaan Yüksel

**Comment by byklyci** [comment]
Good job :+1:

**Comment by serkan-ozel-2015400123** [comment]
I have read all the report thank you it is reflects what was actuaally happen
