### ISSUE TITLE
Clean Up Unused & Completed Branches

### ISSUE THREAD

**Issue by kemaltulum** [bounswe/bounswe2018group9#128]
We have 13 branches in total, at the end of the semester, we should merge all the changes to our master branch. We can delete other branches, if there is no problem with it.

I will be working on this asking for your suggestions if needed.

**Comment by kemaltulum** [comment]
Deleted branches so far, (I deliberately deleted them, since they are merged with TwitterAPI)
* media-yusuf
* twitterApi-Didem
* account-ümit
* retweet

**Comment by serkan-ozel-2015400123** [comment]
I have deleted my own latest pull request branch just recently

**Comment by byklyci** [comment]
I forgot about delete branch of media-yusuf.Thank you for deletion.TwitterAPI branch is the place where we merge them. :+1:

**Comment by nazmicancalik** [comment]
@serkan-ozel-2015400123 
I see a branch called serkan özel patch, if it is done can you delete it too @serkan-ozel-2015400123 thanks.

**Comment by nazmicancalik** [comment]
@gkhntkl You can also delete geo-gokhan branch if it is merged with the Twitter API

**Comment by serkan-ozel-2015400123** [comment]
@nazmicancalik  Okay, I will. Thanks for reminding.

**Comment by gkhntkl** [comment]
@nazmicancalik thank you for reminding of that.

**Comment by okyksl** [comment]
Are that anything we need to do on this issue @bounswe/bounswe2018group9 folks?

@kemaltulum I remember that we had a problem in some branch's history where we accidentally exposed our private key. Do you remember anything related, did we solve that issue?

**Comment by nazmicancalik** [comment]
Can we again check out the unused branches, there were some unused stale branches that is from the last season. I cleaned up some of the branches, we should clean the other ones also.

**Comment by serkan-ozel-2015400123** [comment]
I suppose resources branch is not used if so, can I delete it @gumityolcu

**Comment by serkan-ozel-2015400123** [comment]
@okyksl  Is config branch, gh-pages are used ? Can we merge their small changes to master and delete them? How do we do this?

**Comment by serkan-ozel-2015400123** [comment]
Yes, I will do it now

**Comment by okyksl** [comment]
We have closed up all unused branches.
