### ISSUE TITLE
Report Broken Or Empty Links In Wiki

### ISSUE THREAD

**Issue by kemaltulum** [bounswe/bounswe2018group9#129]
We have a number of broken or empty links in our wiki, which is a problem hiding some work we have done. As a task for all of us, we can deal with them.
If there is a situation that you are not sure what to do, then report the link here please.

**Comment by kemaltulum** [comment]
On the main page, the link **https://github.com/bounswe/bounswe2018group9/wiki/Project** for Project headline is empty. What do you think? Should this be a link? Or, what should it link to?

**Comment by serkan-ozel-2015400123** [comment]
@kemaltulum I think we can remove that link and refer to the description pdf in wiki for the project info if needed.

**Comment by kemaltulum** [comment]
It seems like we did a decent job on this issue, as a last step I checked most of the links and made some small corrections. For this semester, we can close the issue
