### ISSUE TITLE
Team or Project Name Selection

### ISSUE THREAD

**Issue by byklyci** [bounswe/bounswe2018group9#13]
Are we _**select a team name or choose project name**_?  Its will take form with our discussion commits.Please can you suggest something about that situation.Thank you....

**Comment by byklyci** [comment]
Actually we should have both of them. But mainly, the project name will be obligation.So, first of all we need a team name.

**Comment by serkan-ozel-2015400123** [comment]
Byte Me?

**Comment by byklyci** [comment]
It is a good offer but actually we can find soul-shattering name!

**Comment by byklyci** [comment]
I agree with you @okyksl about removing the milestone.

**Comment by okyksl** [comment]
I was thinking about **Cultr** but there is a product with that [name](https://www.cultr.com). In case we blow up the market, thats a problem :)

**Comment by okyksl** [comment]
@byklyci why not we make a list of offered names on the first comment, so that we can track them more easily.

**Comment by byklyci** [comment]
But first of all we should find some soul-shattering name!

**Comment by gkhntkl** [comment]
ctrl+A comes into my mind.

**Comment by dkilyas** [comment]
I think ctrl+A looks meaningful. But, there is a problem with it. As we all know, it is a shortcut in computer. It may cause the people to misunderstand. I mean they would think that our app is about the technology.

**Comment by dkilyas** [comment]
My suggestion is "WeAct". "Act" comes from the first three characters of the activity and "We" represents the group of the people that do cultural activities.

**Comment by akaogluozgur** [comment]
I think "WeAct" is a good one.

**Comment by serkan-ozel-2015400123** [comment]
Group Name Ideas : Collab9raTeD , GroupEff9rt, WePutEff9rt

**Comment by byklyci** [comment]
**_Actopus_** comes into my mind. As we know that Octopus is a creature that has lots of arms and we can think that our project just like that.I change the first letter of Octopus to **Actopus**.People will connect each other and communicate with each other. Octopus Hands is an idiom and meaning is when a person's hands are all over another person. We can also easily add a logo and find creative things.

**Comment by okyksl** [comment]
Just in case you guys like it,  _**Actipus**_ emphasize _activity_ more. 
However, _**Actopus**_' that **opus** part feels more natural. I really like _**Actopus**_ - Let's go for it :)

**Comment by serkan-ozel-2015400123** [comment]
I agree Actopus

**Comment by gumityolcu** [comment]
I think Actopus sounds good 😄👍

**Comment by byklyci** [comment]
We decided our project name and it is _**Actopus**_ after voting on WhatsApp and face to face communication this is our selection. 🐙🎉🎊🎈
Project Name: Actopus
Group Name: Actopus Team
I am closing this issue because it is done successfully...
