### ISSUE TITLE
Issues, github,proto,xtensio, lucidchart for report

### ISSUE THREAD

**Issue by serkan-ozel-2015400123** [bounswe/bounswe2018group9#130]
I have written some reflection about those in the header. You can review and add some more statements in it. I have thought to make them in the same format with the milestone reports(status, acquirements, difficulty and suggestions) but then realized it is not necessary and causes a lot redundant sentences. Therefore, I have combined all the categories into one category.

Here is the link to the files: [onedrive](https://1drv.ms/f/s!AmIQ5c_wmGx3km1llMS4cDZ5Kaac)

**Comment by serkan-ozel-2015400123** [comment]
Added three more you can check the link

**Comment by gumityolcu** [comment]
Added TeamGantt

**Comment by gumityolcu** [comment]
@serkan-ozel-2015400123 For you information: I merged GitHub and Issues files, as issues are part of GitHub. I also hadn't noticed we had a communication document. I merger the Google Hangouts document I created with that file.

**Comment by serkan-ozel-2015400123** [comment]
Thank you umit closing the issue

**Comment by okyksl** [comment]
I believe there is still work to be done here, but it seems like no-one has the energy to do it. We have to check the language if its consistent, we have to detail out project management reviews a bit to have a comprehensive coverage of the different parts of the project management and we have to give more concrete and detailed suggestions on how to fix problems we're facing on project management.
