### ISSUE TITLE
Status Report #1 - Acceptance Testing

### ISSUE THREAD

**Issue by byklyci** [bounswe/bounswe2018group9#131]
[Acceptance Testing](https://github.com/bounswe/bounswe2018group9/wiki/Status-Report-%231-Acceptance-Testing) review is under maintanence. Please add here if you have any comment and question about the Acceptance Tests.  #122

**Comment by byklyci** [comment]
The acceptance testing is done.Please check it and if you want any change just do it :smile: 
[Milestone #6.1 Acceptance Testing](https://github.com/bounswe/bounswe2018group9/wiki/Milestone-%236.1-Acceptance-Testing)

**Comment by byklyci** [comment]
## HERE IS THE FINAL VERSION PLEASE CHECK IT AND CHANGE THE MISSING OR WRONG PLACE :+1: 

## Description
Create acceptance tests which include the project

#### Timeline: 02.04.2018

### Objectives
* Provide one of the main test documents for quality assurance: Test cases for our Course Project.
* Learn how to test the system 
* Get familiarity of test cases

### Deliverables
* [Acceptance Tests](https://github.com/bounswe/bounswe2018group9/wiki/Acceptance-Tests)

## Review #1 (12.05.2018)

### 1. Status

* **1.1** In our weekly meeting ;the meaning of acceptance test is discussed 
* **1.2** 10/10 members directly contribute to the acceptance tests and some people take the responsibilty of prepearing the cases.
* **1.3** The team tried open issues and discuss the development process.
* **1.4** The requirenment analysis scanned again and again.
* **1.5** The test case format and the platform decided after the analysis and scan part.
* **1.6** The assumption of each test cases are decided.
* **1.7** The scenerio of test case contains : 1-Test step number 2-Test step description 3-Test data 4-Expected result 5-Actual result 6-Pass/Fail. 
* **1.8** The 6-Pass/Fail will happen after the real tests of our implementation.
* **1.9** The twenty-one acceptance test cases prepared and ready for the test.

### 2. Acquirements

* **2.1.** The most of team members utilized GitHub for the first time and attend a real project.
* **2.2** The notion of Test cases are discovered
* **2.3** Some real up and useful test cases created at the end.


### 3. Difficulties
This is a course which teaches the stages of software development, working as a team, systematic scheduling and distribution of tasks. However, the fact that the course itself teaches us how to make test cases, implies that the test cases we make will neither be realistic nor useful. Since we didn’t yet know which stages must be passed or what the dependencies between these stages are, the acceptance tests we prepared didn’t correspond well to the homeworks and milestones given to us by the Boss. We tried to look at the test cases of the former years’ projects -which helped but since we weren’t aware of the meaning of the tasks and the milestones-, it didn’t mean much at the time. This is natural, inevitable.

* **3.1.** The acceptance test case preparation is hard because the project is in progress.In real life as all know that the plan and the test cases should be prepare before project's end.So it is a hard part for us to prepare and very thoughtful.
 
* **3.2.** It created the obligation to regularly check and correct the Requirenment Analysis.We actually prepare the acceptance test 2 weeks.Second, this fact made the Requirenment Analysis feel like a burden rather than a guide on how we will develop our software.

* **3.3.** Actually, we dont know this cases are pass or fail after the real test case happen.So it is a food for thought for us.  
* **3.3.** We have learned what the important aspects of test cases, what are the logic behind them and how to use them.


### 4. Suggestions

* **4.1.** Next year, we will be starting to develop the real thing, to write the code. Which –surely there will be differences but- is a process we are more familiar with than the tasks we worked with this semester. Thus, it may be easier to produce a more realistic plan and use it without modifying it every 3 weeks. Furthermore, because our job will demand even more collaboration and communication, after all of these we test our prepared cases. Thus we must –even if the same difficulties persist- find a way to make it useful and we must follow it.

* **4.2.** While we are doing implementation we should be aware of the testing them.The acceptance test should be pass.This is the reason why we prepared them before the job finished.

**Comment by gumityolcu** [comment]
I don't understand the first paragraph under 3. Difficulties

**Comment by byklyci** [comment]
I removed it :+1:

**Comment by byklyci** [comment]
I am closing this issue because it is done :+1:
