### ISSUE TITLE
Status Report #1 - Requirements Analysis Review

### ISSUE THREAD

**Issue by serkan-ozel-2015400123** [bounswe/bounswe2018group9#132]
[Status Report #1 Requirements Analysis](https://github.com/bounswe/bounswe2018group9/wiki/Status-Report-%231-Requirements-Analysis) is done. You can state your ideas about it below. Please read the report once since it is important to know what I, as a team member of you, have written to the report. 
@bounswe/bounswe2018group9

* [ ] Gökhan Tekel
* [ ] Didem Öngü
* [x] Hamdi Özgür Akaoğlu
* [ ] Nazmican Çalık
* [ ] İlyas Demirkıran
* [x] Yusuf Kalaycı
* [x] Kemal Tulum
* [ ] Galip Ümit Yolcu
* [x] Serkan Özel
* [ ] Oğuz Kaan Yüksel

**Comment by byklyci** [comment]
@serkan-ozel-2015400123 good job :+1:

**Comment by kemaltulum** [comment]
This would be the most cumbersome milestone, probably the most important as well. Thanks for your precious effort @serkan-ozel-2015400123
