### ISSUE TITLE
Status Report #1 - Repository Overview 

### ISSUE THREAD

**Issue by gumityolcu** [bounswe/bounswe2018group9#133]
[Status Report #1 Repository Overview](https://github.com/bounswe/bounswe2018group9/wiki/Status-Report-%231-Repository-Overview) has a review now. Please check and contribute if you have something to add.

**Comment by kemaltulum** [comment]
Seems very comprehensive! I just wonder if [Our Favourite Repositories](https://github.com/bounswe/bounswe2018group9/wiki/Our-Favorite-Repositories) is one of the deliverables of this milestone
