### ISSUE TITLE
Milestone Review #7.1

### ISSUE THREAD

**Issue by kemaltulum** [bounswe/bounswe2018group9#135]
I think, I covered our main concerns in this milestone. All the suggestions and additions are welcome.

[Milestone #7.1 Twitter API](https://github.com/bounswe/bounswe2018group9/wiki/Milestone-%237.1-Twitter-API)

**Comment by gumityolcu** [comment]
I will add the brief explanations on everyone's coding work.

**Comment by nazmicancalik** [comment]
Good job @kemaltulum  and @gumityolcu . You can close this issue if there is no need for more contribution.

**Comment by kemaltulum** [comment]
Yes you are right @nazmicancalik Closing the issue
