### ISSUE TITLE
REPORT DEADLINE 17.00

### ISSUE THREAD

**Issue by serkan-ozel-2015400123** [bounswe/bounswe2018group9#137]
[link](https://tr.sharelatex.com/6723986469yhwqpyzvjwtn )
In this link you can see our report's last status. We need to copy milestones into the 3rd chapter. Write evalutaions for chapter 4 including:  
* \subsection{ Meetings} 
* \section{Further Suggestions}
    * \subsection{Requirements Grooming}
    * \subsection{Backlog Grooming}
    * \subsection{SMART Goals}
    * \subsection{Workflow}

@okyksl You have written the further suggestions part. Can you evaluate what are those so that we can write some feedback. @bounswe/bounswe2018group9

**Comment by serkan-ozel-2015400123** [comment]
Update: 

Chapter 4 is now finished, we need assistance in other chapters

**Comment by serkan-ozel-2015400123** [comment]
Good work everyone

**Comment by okyksl** [comment]
I think we had lot of last day & deadline crisis which is telling, I don't see why we are not even discussing let alone trying to solve this issue?
