### ISSUE TITLE
Requirement Analysis Format 

### ISSUE THREAD

**Issue by serkan-ozel-2015400123** [bounswe/bounswe2018group9#14]
Let us decide subheadings of requirements together.  You can add another topic to a certain heading or add another heading. If you don't think a heading's position is not correct, state it so that we can change it.
1. Functional Requirements
1.1 User Requirements
1.1.1 Member Users -- What they can do
1.1.1.1 Sign Up -- How they will sign up.
1.1.1.2 Communication -- Relation between users in terms of communication.
1.1.1.3 Profile -- How each users' profile will be.
1.1.1.4 Contribution -- How each user will contribute to data collection of the project.
1.1.1.5 Tagging -- Users can tag their content. Properties of tags.
1.1.1.6 Searching -- How users will search content
1.1.1.7 Attendance -- How users will attend to events.
1.1.1.8 Voting -- Users will vote what and how.
1.1.1.9 Recommendation -- System recommends what based on what.
1.1.1.10 Annotation -- How users annotate and what they can annotate
1.1.2 Guest Users -- What they are able to do
1.2 System Requirements
2. Non-Functional Requirements
2.1 Availability - Platforms the project is going to have, System language of the project
2.2 Annotations - What will be used for annotations, How annotations will be
2.3 Security - Data security and data access rights

**Comment by byklyci** [comment]
Actually in my perspective, add it right now then we can write under it some time later.

**Comment by gkhntkl** [comment]
The existence of the Sing-up system could be interpreted as  a demonstration of the security.

**Comment by gumityolcu** [comment]
@serkan-ozel-2015400123 We could add "2.3 Security - Data security and which data access rights" right now so that we won't forget it later when we detail each section down.

@gkhntkl I was thinking about protection of passwords, e-mail addresses and -maybe even chats, photographs etc.- of the users. Plus, maybe even data access rights between users. Requirements like "A guest should not be able to see the e-mail of a member."

**Comment by serkan-ozel-2015400123** [comment]
@byklyci @gkhntkl I am adding security section according to this.

**Comment by gkhntkl** [comment]
What about supporting different languages...We are trying to encompass all of the world,right?

**Comment by nazmicancalik** [comment]
Even if we make it only in english, I think we should add this question to the list of questions that we are going to ask to the customer this thursday, because it is unclear.

**Comment by serkan-ozel-2015400123** [comment]
The four groups we will set up can show their format here.  That way we can review them before they decide on final form.

**Comment by okyksl** [comment]
I renamed `Guest Users` part to `Guests` and integrated it into `User Requirements` to have better organization.

**Comment by serkan-ozel-2015400123** [comment]
Now that we switch to seperate issues we can close this issue. Moreover, first post is not up-to-date anymore.
