### ISSUE TITLE
Annotation related User Scenarios

### ISSUE THREAD

**Issue by okyksl** [bounswe/bounswe2018group9#145]
We have 3 assigned annotation related user scenario deliverables. Remember to be specific and clear. Let's use different types of annotation in each of the scenarios and possibly some project features that we like and found relevant.

Do not forget to add **acceptance criteria** (or, _definition of done_) to your user scenarios. You can utilize our previously prepared 3 specific user persona & scenario examples [here](https://github.com/bounswe/bounswe2018group9/wiki/User-Personas-&-Scenarios) as guide.

**Comment by serkan-ozel-2015400123** [comment]
I am going to modify the one I wrote today ; to add acceptance criteria and a pic maybe. Anything else?

**Comment by okyksl** [comment]
@serkan-ozel-2015400123 I think it is okay.

**Comment by okyksl** [comment]
I don't think they are necessary, let's focus on the characteristics of the scenarios.

**Comment by okyksl** [comment]
@gumityolcu can we track the requirements related with the scenarios?

**Comment by okyksl** [comment]
I'm closing this issue since we have finalized our user scenarios.
