### ISSUE TITLE
Configuration of Communication Plan

### ISSUE THREAD

**Issue by nazmicancalik** [bounswe/bounswe2018group9#15]
Communication plan will be decided and documented on wiki.

**Comment by byklyci** [comment]
Will we make a log or a folder that includes our communications? For example Yusuf make phone call with Nazmican about ...... , Ümit write something in Slack for Oğuz!  etc. I mean some remarkable topics.

**Comment by serkan-ozel-2015400123** [comment]
@byklyci  I don't think that we should not add this because it is not specified in format of communication plan.

**Comment by nazmicancalik** [comment]
@byklyci I think for now we don't have to make a log of our phone calls, however if we ever take crucial decisions on those calls we better log those calls. That way we can refer to those calls or any type of communication in the future.

**Comment by nazmicancalik** [comment]
Guys I need help of everyone. I'm thinking we add another delivery purpose to our communication plan like following :
* We check the current progress of distributed works, everybody reports their status on a platform that we will decide (Projects tab can be used for this). That way everybody will know what is the progress of each task.
Any thoughts ?

**Comment by byklyci** [comment]
@nazmicancalik ı agree with your idea. In projects tab we can add in progress section which title is current progress and at the end Of the week we can add it done section.

**Comment by okyksl** [comment]
@nazmicancalik I added a simple glossary part which can grow if need arises.
