### ISSUE TITLE
Review of the class diagram

### ISSUE THREAD

**Issue by nazmicancalik** [bounswe/bounswe2018group9#150]
As a backend team we should review the data we have in order to create the necessary data models. 
We should finalize this issue face to face this week.

TO DO Until meeting : 
* Review, (be prepared for the meeting) the class diagram.
* Try to search for missing data components in the class diagram.

**Comment by okyksl** [comment]
I think we need to change annotation structure to cover these functionalities:

* Annotation can be an image or also a link.
* Annotation can be defined on the multimedia supported in the event description, by selecting a specific area. 

Also, with the latter annotation functionally we also need:
* An event or event description structure that is capable of representing the multimedias.

**Comment by okyksl** [comment]
Is there any progress on data model designs @nazmicancalik?

**Comment by nazmicancalik** [comment]
We haven't made any changes to the data models. We decided to change the data models on the go when building the app and getting in touch with the frontend team. Because our data model depends heavily on their design. We like to keep the data models simple and stable along the process. @okyksl

**Comment by okyksl** [comment]
As I see from the following piazza [post](https://piazza.com/class/jlf0sl8gc3p748?cid=21) on milestones, that we need have a some form of report on **design** of the application. I guess this might include the our data model design or our class diagrams. What do you think, should we prepare some sort of document - even if sketchy - to display our current understanding and status?

**Comment by nazmicancalik** [comment]
You are right, however as far as I understand from Suzan Hoca, we need to show the data model of the objects that we can show on the frontend for now. For example, events are a perfect match for this purpose. We can try to finalize Event data model so that we can get a feedback from the customer after or during the presentation. (For example, this field is missing, I want to see the attendee count also etc.)
