### ISSUE TITLE
User Story #1 - Sign-up

### ISSUE THREAD

**Issue by okyksl** [bounswe/bounswe2018group9#157]
> As a user, I want to sign up to Actopus so that I can join the community of the Actopus.

**Acceptance Criteria:**

- [x] **1.** User shall be able to sign-up with a **name, surname, email and password**.
- [x] **2.** System shall be able to save a user information.
- [x] **3.** System shall be able to encrypt the password securely.

**Comment by serkan-ozel-2015400123** [comment]
This is done, looks like.

**Comment by byklyci** [comment]
Sign up page is actually ok.So I am closing this issue. :+1:

**Comment by okyksl** [comment]
I think related tests are going to be reviewed in #315. I'm closing this issue as we have no longer follow _story based workflow_.
