### ISSUE TITLE
User Story #2 - Sign-in

### ISSUE THREAD

**Issue by okyksl** [bounswe/bounswe2018group9#158]
> As a user, I want to sign in so that I can join and interact with the Actopus ecosystem so I can create various event.

**Acceptance Criteria:**

- [x] **1.** User shall be able to sign-in with an **email and password**.
- [x] **2.** User shall be able to sign-out at any time from the application.
- [x] **3.** User shall be able to see the information she provided (name, surname) after sign-in.
- [x] **3.** System shall be able to check email-password combination.
- [x] **4.** System shall be able to track user authentication status for further requests.
- [x] **5.** System shall be able to serve a user information (name, surname).

**Comment by serkan-ozel-2015400123** [comment]
Actually we should check these if both frontend and backend are finished & tested ?. @byklyci

**Comment by byklyci** [comment]
Is there still necessary **3. User shall be able to see the information she provided (name, surname) after sign-in.** ?? @okyksl

**Comment by serkan-ozel-2015400123** [comment]
Actually we can show user information on branch feature/frontend/profile-page 
I have opened a pr #261

**Comment by okyksl** [comment]
Related tests are going to be reviewed in #315. I'm closing this issue as we have no longer follow _story based workflow_.
