### ISSUE TITLE
User Story #3 - Facebook Sign-in

### ISSUE THREAD

**Issue by okyksl** [bounswe/bounswe2018group9#159]
> As a user, I want to utilize my Facebook account to sign in so that I can easily interact with the Actopus ecosystem.

**Acceptance Criteria:**

- [ ] **1.** User shall be able to allow her Facebook account to be used in sign-in process.
- [ ] **2.** User shall be able to sign-in via Facebook account after permission.
- [ ] **3.** System shall be able to retrieve **email, name, surname** information from the Facebook API.
- [ ] **4.** System shall be able to save necessary Facebook API information for further sign-in requests.
- [ ] **5.** System shall be able to utilize Facebook API to allow user to sign-in.

**Comment by byklyci** [comment]
Is there any progress for this issue? The assignees please inform us.

**Comment by okyksl** [comment]
@akaogluozgur

**Comment by okyksl** [comment]
@dkilyas is working on this issue right now.

**Comment by okyksl** [comment]
We're going to follow this from #330.
