### ISSUE TITLE
Delete homework descriptions from the wiki page

### ISSUE THREAD

**Issue by nazmicancalik** [bounswe/bounswe2018group9#16]
Should we add homework descriptions to the wiki system or not ? What are your thoughts ?
Please put a tick near your name if you want homework descriptions to be deleted from the wiki system.

- [x] Gökhan Tekel
- [ ] Didem Öngü
- [ ] Hamdi Özgür Akaoğlu
- [x] Nazmican Çalık
- [ ] İlyas Demirkıran
- [x] Yusuf Kalaycı
- [x] Serkan Özel
- [ ] Kemal Tulum
- [x] Galip Ümit Yolcu
- [x] Oğuz Kaan Yüksel

**Comment by gumityolcu** [comment]
It would be good to be able to access the homework documents from anywhere, but it makes the wiki crowded. So I think we should add the documents to the repo under docs.

**Comment by byklyci** [comment]
Because this is not a part of our projects after we make something that for customers , they wont care about it.

**Comment by nazmicancalik** [comment]
Since we have reached a consensus, I'm deleting the homework description page and closing the issue.
