### ISSUE TITLE
Setup Development Environment

### ISSUE THREAD

**Issue by okyksl** [bounswe/bounswe2018group9#162]
We have to finalize development environment setups. Everyone should be able to **build and run** the project in their development environment.

- [ ] Gökhan Tekel
- [x] Didem Öngü
- [x] Hamdi Özgür Akaoğlu
- [x] Nazmican Çalık
- [ ] İlyas Demirkıran
- [x] Yusuf Kalaycı
- [x] Serkan Özel
- [ ] Kemal Tulum
- [x] Galip Ümit Yolcu
- [x] Oğuz Kaan Yüksel

**Comment by okyksl** [comment]
@gkhntkl @didemongu @dkilyas @serkan-ozel-2015400123 @kemaltulum can you please report on whether you have setup development environment?

**Comment by nazmicancalik** [comment]
@gkhntkl @didemongu @dkilyas @serkan-ozel-2015400123 @kemaltulum

**Comment by serkan-ozel-2015400123** [comment]
Yeah, I have

**Comment by okyksl** [comment]
I assume everyone set up their development environment. Ask any specific issues you have related with _backend development_ to @nazmicancalik and _frontend development_ @kemaltulum.
