### ISSUE TITLE
User Story #4 - Event Creation

### ISSUE THREAD

**Issue by okyksl** [bounswe/bounswe2018group9#168]
> As a user, I want to create events so that I can share my enthusiasm about cultural activities.

**Acceptance Criteria:**

- [x] **1.** User shall be able to create an event with a title, text description, performing artists, date and price.
- [x] **2.** User shall be able to view an event by accessing it with its unique identifier.
- [x] **3.** System shall be able to save an event information and assign unique identifier to each event.
- [x] **4.** System shall be able to serve an event information.

**Comment by nazmicancalik** [comment]
Backend  part of this story is done.

**Comment by serkan-ozel-2015400123** [comment]
When we press create button a post request is done in event-create page, however we get 503 @nazmicancalik @gumityolcu. Can you see why?

**Comment by serkan-ozel-2015400123** [comment]
This is done

**Comment by byklyci** [comment]
Is this done? @gumityolcu

**Comment by okyksl** [comment]
Related tests are going to be reviewed in #301. I'm closing this issue as we have no longer follow _story based workflow_.
