### ISSUE TITLE
Description of the Project

### ISSUE THREAD

**Issue by gumityolcu** [bounswe/bounswe2018group9#17]
Now that we have the project description, we can update the `README.md` file to include the general description of the project.

**Comment by serkan-ozel-2015400123** [comment]
We can also edit wiki home page.

**Comment by byklyci** [comment]
Now we also have the project name , we can update the `README.md` file and add the project name on there.
Team Actopus,Yusuf.

**Comment by okyksl** [comment]
If @dkilyas finish his magnificent art, we can also add our **Actopus**.

**Comment by dkilyas** [comment]
@okyksl Thanks for your comment about my drawing. I finished it. If everyone likes it, we can put it on the description.
![actopus](https://github.com/dkilyas/cmpe352/blob/master/resources/images/actopus.png?raw=true)

**Comment by nazmicancalik** [comment]
@dkilyas this is great work, I think we can add this to our Readme file now, so that it would look prettier and more interactive.

**Comment by okyksl** [comment]
I'm closing this issue as description and logo of the project is added to `README.md`.
