### ISSUE TITLE
User Story #5 - Event Feed

### ISSUE THREAD

**Issue by okyksl** [bounswe/bounswe2018group9#171]
> As a user, I want to see events on the platform so that I can explore the contents provided in the platform.

**Acceptance Criteria:**

- [x] **1.** User shall be able to view multiple events (only sees title, price, date) within the same page that can list further events as user request.
- [x] **2.** System shall be able to serve multiple event information with an indexing (i.e it can serve events within an arbitrary index range).

**Comment by nazmicancalik** [comment]
@gumityolcu Ümit, I will check the endpoints now but just to make sure are we missing something for the backend part of this task?

**Comment by gumityolcu** [comment]
@nazmicancalik With indexing done now, I don't think we have. We need only reviews :smile:

**Comment by serkan-ozel-2015400123** [comment]
In frontend this part is not done :  that can list further events as user request.

**Comment by nazmicancalik** [comment]
@serkan-ozel-2015400123 Do we have a proper styling on this event feed page?

**Comment by okyksl** [comment]
We have a styling that looks better for sure. However, we need to implement **infinite scroll** like structure for this user story.

**Comment by okyksl** [comment]
We are going to follow this from #252.
