### ISSUE TITLE
Frontend Task Distribution

### ISSUE THREAD

**Issue by serkan-ozel-2015400123** [bounswe/bounswe2018group9#174]
We have discussed with backend team and Suzan teacher and agreed on: 
**Until next week:** 
(Design is not very important)
- Sign in frontend & functionality
- Sign up frontend & functionality 
- Event Creation frontend page & functionality

**Comment by okyksl** [comment]
@serkan-ozel-2015400123 isn't it the case that **frontend team** already finished #157 and almost #158. We also agreed upon #168 and #171 as of `Sprint #2`. Let's discuss the details of your talk with **The Boss** on meeting tomorrow.

**Comment by nazmicancalik** [comment]
@serkan-ozel-2015400123 Has the frontend team already distributed the tasks or what is the status?

**Comment by serkan-ozel-2015400123** [comment]
We have not yet. We will do it soon

**Comment by okyksl** [comment]
We have finalized the task distribution among the **frontend team**.
