### ISSUE TITLE
Continuous Integration 

### ISSUE THREAD

**Issue by okyksl** [bounswe/bounswe2018group9#177]
We have to start `Continuous Integration` process to improve our development quality and efficiency. This needs to work in conjunction with #172.

**Comment by nazmicancalik** [comment]
This issue can be reopened later, however for now as we discussed we will hold on to heroku continuous deployment.

**Comment by okyksl** [comment]
@nazmicancalik can we do the setup together for `CircleCI`?

**Comment by okyksl** [comment]
We talked with @gumityolcu and we're setting up **continuous integration & deployment** with `CircleCI` to our newly deployed server.

**Comment by gumityolcu** [comment]
We have finally managed to get past all the details and can succesfully build and host the project automatically. We now need to apply configurations so that tests will be ran before PRs and deployment will be done after PRs. We then will integrate CircleCI with our repo.
