### ISSUE TITLE
Customer Meeting Questions

### ISSUE THREAD

**Issue by kemaltulum** [bounswe/bounswe2018group9#18]
We have been accumulating the ideas for the requirements we would have for our project. This issue is the place where we discuss and collect the points we should ask to our customer, who is @mericturan .

Please every one of us puts the questions in this mind here, Also, we should discuss the questions we come up with so that we prepare consistent and effective questions for our customer.

Then, we can start....

**Comment by serkan-ozel-2015400123** [comment]
Our customer is @mericturan instead of @cantunca. @nazmicancalik Nazmi can add his question about language support

**Comment by nazmicancalik** [comment]
We can add this question :
Do we need to support multiple languages on the platform ?

**Comment by mericturan** [comment]
@nazmicancalik actually, I didn’t think to add such feature while I was preparing your project. Yet, it seems like a quite necessary and nice feature to have. Therefore, I expect you to support at least 2 languages :)

Also, your application/web site should select the default language based on the language of the device (mobile device or pc). If the language of the device is not supported by your project (I.e., language of mobile phone is Chinese), then the language of the application/web site is expected to be English.

**Comment by gkhntkl** [comment]
what sort of information are  we allowed to gain about our customer? Lets say we wanna be informed of his\her gender,birthdate to serve them in better conditions,are we allowed?

**Comment by mericturan** [comment]
You can use personal information (i.e., gender, age, and homeland) of your users by keeping them anonymous.

Let me give an example to clarify: Ayşe is a female who is 22 and lives in Istanbul. You can see the actions (i.e., events that Ayşe participated) of Ayşe, her age, gender and homeland in order to recommend her better events, but as the developer, you shouldn't know that this particular person is Ayşe.

**Comment by byklyci** [comment]
About the rating system,  what should we do? For example: Top 10 activities in İstanbul or Best Activities about people's personel interest. And also , what will we look selecting best rated activities? Vote or Comment based!?

**Comment by mericturan** [comment]
I think you should not keep your customer busy for every single detail :)

You may give some weight to the comments, likes, likes of the comments, ratings of the people who comment etc.

Why don't you all argue this question in your next meeting and come up with a proposal?

**Comment by byklyci** [comment]
Yes, we will add this topic our agenda for talking next meeting.

**Comment by serkan-ozel-2015400123** [comment]
Question 1 and 9 are similar. I think one of them should be deleted.

**Comment by gumityolcu** [comment]
@serkan-ozel-2015400123
You are right. I handled it

**Comment by nazmicancalik** [comment]
Since we have done with customer meeting, I am closing the issue

**Comment by okyksl** [comment]
@nazmicancalik Should we close this after we add other team's questions about the project?

**Comment by nazmicancalik** [comment]
@okyksl Okay, that's actually a good idea. I will reopen the issue.

**Comment by serkan-ozel-2015400123** [comment]
@okyksl What do you mean by adding other teams questions? Where to? You know I wasn't at the meeting so it may be normal not to understand for me.

**Comment by okyksl** [comment]
@serkan-ozel-2015400123 Customer meeting is done together with all the three teams doing the same project. There were also some questions raised by other teams. I suggest we should also add them to the `Customer Meeting` questions sheet.

**Comment by byklyci** [comment]
We should also prepare Costumer Meeting page. This page should include date,where,when,what etc. informantion. Question and answer part and some other information. Please dont forget this situation because the T.A's said that in the PS time. 
Team Actopus,Yusuf

**Comment by okyksl** [comment]
@bounswe/bounswe2018group9 Are there any additional questions you noted on `Customer Meeting #1`? If so please add them [here](https://github.com/bounswe/bounswe2018group9/wiki/Customer-Meeting-%231). 

There are 3 questions here that is not included on the document:
* Do we need to support multiple languages on the platform?
* What sort of information are we allowed to gain about our customer?
* About the rating system, what should we do?

I'm also adding these questions to the document as well. I'm closing the issue, if you think there are missed questions please re-open the issue and start discussion here.
