### ISSUE TITLE
Events CRUD: Delete

### ISSUE THREAD

**Issue by nazmicancalik** [bounswe/bounswe2018group9#180]
Delete operation for the Events collection endpoint should be implemented.
DELETE to /api/events/:id

**Comment by nazmicancalik** [comment]
After @gumityolcu merge the f-events branch then @akaogluozgur can work on this issue.

**Comment by nazmicancalik** [comment]
@akaogluozgur @gumityolcu has already merged his branch, you can start working on this issue now.

**Comment by okyksl** [comment]
@akaogluozgur are we done here?

**Comment by akaogluozgur** [comment]
@okyksl yes we are done.

**Comment by okyksl** [comment]
Can we merge and close the issue?
