### ISSUE TITLE
Wiki Design - Project Plan Header

### ISSUE THREAD

**Issue by okyksl** [bounswe/bounswe2018group9#19]
With the coming `Requirements Analysis` page and a `Customer Meeting` pages, there will be documents relating to **project plan & description**. I suggest we move these files to a separate header called `Project Plan` or directly under the `Home` page. I believe reserving `Resources` for both external and internal documents will make navigation less fluent. Moreover, `Home` page could include `Project Plan` documents to form a secondary navigation.

**Comment by nazmicancalik** [comment]
I think this would be a really good way to organize project related wiki pages.

**Comment by okyksl** [comment]
I'm added the extra `Project` header to track documents relating to **project plan & description**.
