### ISSUE TITLE
Endpoint Documentation

### ISSUE THREAD

**Issue by okyksl** [bounswe/bounswe2018group9#190]
Dear **backend team**, we need a consistent naming for the endpoints and **a simple document** _listing the endpoints and their development statutes_ in our project. @nazmicancalik @akaogluozgur can you handle this?

**Comment by nazmicancalik** [comment]
I don't think we need to create another convention document for this purpose. We can use already prepared ones. Here is an example: https://restfulapi.net/resource-naming/
We will document our endpoints when we create the api docs.

**Comment by okyksl** [comment]
I meant **api docs** which lists the endpoints and whether they are implemented and what parameters they have and etc. Should we open a running document that can be modified from our wiki?

**Comment by okyksl** [comment]
@gumityolcu @byklyci could you please prepare a **document for endpoints** that lists _names of the endpoints and the inputs_.

**Comment by okyksl** [comment]
@bounswe/bounswe2018group9 @nazmicancalik should we also prepare a **data model documentation** with the **endpoint documentation**?

**Comment by serkan-ozel-2015400123** [comment]
This would be very beneficial. I am looking forward to see. Thank you in advance guys

**Comment by gumityolcu** [comment]
https://github.com/bounswe/bounswe2018group9/wiki/Endpoint-and-Data-Model-Documentation

Here is the document. It will be updated. For now I have included the endpoints that are implemented but not tested and merged, I have indicated this situation in those endpoints' sections.

Sorry for the delay.

**Comment by gumityolcu** [comment]
I am closing the issue since it is dealt with. The document will be updated parallel to the progress.
