### ISSUE TITLE
Frontend Auth & Data Service Testing

### ISSUE THREAD

**Issue by okyksl** [bounswe/bounswe2018group9#191]
I have written **an auth and a data service** that is responsible with _interacting with backend and handle data communication_. This services needs to be tested, so that we can start to develop any user interface for appropriate user functionalities.

**What you need to test these services:**
1. Run backend on your machine or utilize deployment on heroku (@nazmicancalik can help you with that), and **get the endpoint of a running backend application**.
2. **Configure endpoint** from `src/environments` files.
3. Communicate with backend team and **settle on the endpoint names**.
4. The `DataService` which is available in `src/app/services` utilizes a **strict api endpoint format** which **might need to be adjusted** according to **3.**
5. Utilize `EventService` to try various functionalities such as **get, post, put, delete** and check whether we get appropriate results.
6. Utilize `AuthService` to try **sign-in and sign-up functionalities**. (You may need to iterate **3.** and **4.** for the `AuthService` as well.)

**Comment by nazmicancalik** [comment]
https://boun-actopus.herokuapp.com/api/events

**Comment by serkan-ozel-2015400123** [comment]
@okyksl  With the code in f-services branch I get the path as "https://boun-actopus.herokuapp.com/api//5bd21fc8703e1f002ff2edfd" i.e events is missing. Is this due to inheritance, i.e this.api refer to data.service's property, not event.service's one?

**Comment by okyksl** [comment]
@serkan-ozel-2015400123 did `f-services-deploy` solved your problem?

**Comment by serkan-ozel-2015400123** [comment]
Yes, it did. I can play with events

**Comment by okyksl** [comment]
We now have working providers/services that talks with our backend. @serkan-ozel-2015400123 thanks for your efforts on this issue.
