### ISSUE TITLE
User Interface - Sign-up

### ISSUE THREAD

**Issue by okyksl** [bounswe/bounswe2018group9#193]
We have to implement user interfaces for **sign-up** functionality to satisfy the needs of #157.

**Comment by serkan-ozel-2015400123** [comment]
@nazmicancalik @gumityolcu Which endpoints we will use for signup and is backend system for it ready?

**Comment by okyksl** [comment]
We have finalized the first version of sign-up user interface. Thanks @kemaltulum @didemongu for their efforts!
