### ISSUE TITLE
User Interface - Sign-in

### ISSUE THREAD

**Issue by okyksl** [bounswe/bounswe2018group9#194]
We have to implement user interfaces for **sign-in** functionality to satisfy the needs of #158.

**Comment by serkan-ozel-2015400123** [comment]
@nazmicancalik @gumityolcu Which endpoints we will use for signin and is backend system for it ready?

**Comment by okyksl** [comment]
We have finalized the first version of sign-in user interface. Thanks @kemaltulum @didemongu for their efforts!
