### ISSUE TITLE
Milestone #12 Presentation Preparation

### ISSUE THREAD

**Issue by okyksl** [bounswe/bounswe2018group9#197]
We need to prepare our stories for the `Customer Presentation` we have on **Tuesday, 30 October**.

**Comment by serkan-ozel-2015400123** [comment]
Do we need to write completely new stories? 

Also should we prepare some kind of a powerpoint like mockups last term, showing some details not implemented yet ? 

@bounswe/bounswe2018group9

**Comment by okyksl** [comment]
I don't think so, this involves a preparation for presenting the user stories that we have talked so far, namely #157, #158, #168, #171 and maybe a general story involving all four.

**Comment by okyksl** [comment]
I guess everyone knows what happened at the presentation and, hopefully **some of us take a little bit of responsibility next time**.
