### ISSUE TITLE
Research About Good Repositories

### ISSUE THREAD

**Issue by serkan-ozel-2015400123** [bounswe/bounswe2018group9#2]
Due: 12.05.2017
  Our first week assignment is researching about git and some repositories that we like. For doing this homework we have a wiki page called
>  **Repository Research Page** 

on the sidebar. We, all of us, should decide on a specific format and add our research information to that page.

- [ ] Gökhan Tekel
- [ ] Didem Öngü
- [x] Hamdi Özgür Akaoğlu
- [x] Nazmican Çalık
- [x] İlyas Demirkıran
- [x] Yusuf Kalaycı
- [x] Serkan Özel
- [x] Kemal Tulum
- [x] Galip Ümit Yolcu
- [x] Oğuz Kaan Yüksel

**Comment by byklyci** [comment]
@serkan-ozel-2015400123 about the good repositories, how can we decide it is good or bad?

**Comment by serkan-ozel-2015400123** [comment]
I decided it based on my intutions. In general, I have written visually nice features to research page. Another criteria may be practicality.

**Comment by nazmicancalik** [comment]
I think everybody should serach for their favourite repositories based on their instincts and how the repository is documented, structured etc. 
After that we should add our researches without including our name ( who edited which lines already can be seen), creating a mutual page. But being make sure that everybody contributes.

Template:
- [Name of the repo](link) - Comment about why you picked this repo.

**Comment by serkan-ozel-2015400123** [comment]
@nazmicancalik Nazmican I think you accidentally deleted our(Oguz's and mine) research text. I am adding them to the page in the latest form.

**Comment by serkan-ozel-2015400123** [comment]
Because I think we should put all research info to the same page

**Comment by serkan-ozel-2015400123** [comment]
Btw, I added our names to our individual contribution because it is going to be hard to find research texts' writer.

**Comment by nazmicancalik** [comment]
I haven't deleted the page but maybe by a mistake it got deleted. Yes please, you add deleted text. For writing our names I am open to both solutions we can write our names or not. Sorry for inconvenience.

**Comment by okyksl** [comment]
@nazmicancalik I'm moving your checklist to the first comment on the issue, so that we can track the checklist from Issues panel.

**Comment by okyksl** [comment]
I'm closing this issue, anyone who wants to add additional repositories can edit the wiki page.
