### ISSUE TITLE
Necessary Labels for Project

### ISSUE THREAD

**Issue by didemongu** [bounswe/bounswe2018group9#20]
_Due by Feb 18,2018_

About last meeting (meeting 2) we discussed labels and tags I will add `Platform` label type which specifies what the issue is on specifically, would be beneficial to add. `Platform: Documentation`, `Platform: Frontend`, `Platform: Backend` are considered. Is there any suggestion?

**Comment by kemaltulum** [comment]
I think `Type: Meeting` would be useful in that we can simply label the issues to be discussed in the meeting.

Another suggestion of mine is `Platform: CustomerReview` or `Platform: CustomerMeeting`. Actually I am not sure yet but for some issues we can specify it as things that should be discussed with the customer.

**Comment by gumityolcu** [comment]
We could also add a label similar to Platform: CodeReview since we decided do code review and master branch protection.

**Comment by didemongu** [comment]
@kemaltulum @gumityolcu I think header `Type` is more suitable for `Customer Review` and `Code Review` labels.

**Comment by gumityolcu** [comment]
@didemongu You are right. "Type: Code Review, Platform: Frontend" seems better than "Platform: Code Review, Platform: Frontend"

**Comment by byklyci** [comment]
Actually our tags and labels are very useful seperation style. We can add some time later other specific things when the project is coming mature.

**Comment by didemongu** [comment]
I added `Type: Meeting` , `Type: Code Review` and `Type: Customer Review` labels.

**Comment by nazmicancalik** [comment]
If we don't have any more additions to labels we can close this issue Didem. @didemongu

**Comment by okyksl** [comment]
@didemongu I agree with @nazmicancalik.

And, additional side notes about labels:
* One trend we are going towards is that, sometimes we select **5 labels** even though we have only **4 types** - _which causes a bit overhead to issues_.
* We should clarify the usage of each label, so that we can pick the right ones for the issue at hand.
* **_Maybe_** (_and thats a 50-50 maybe_) we should restrict usage of labels such that _only single label per type_ is allowed.

**Comment by nazmicancalik** [comment]
I definitely aggree with @okyksl . Our labels are pretty helpful but sometimes using too many labels makes the issue seem confusing more than it should be. So my suggestion is same as @okyksl : 
- We can limit usage of labels.

**Comment by byklyci** [comment]
I added Issue Summary and Guide on the Wiki page Sidebar Issues 1section. If we decide another label please inform me individually to edit there again. Thank you.
Team Actopus,Yusuf

**Comment by gumityolcu** [comment]
@okyksl You are right. I think this specification should be included in the Contribution Guide #11

**Comment by didemongu** [comment]
I am closing this issue because discussed labels are added.
