### ISSUE TITLE
Media Field in Data Model

### ISSUE THREAD

**Issue by serkan-ozel-2015400123** [bounswe/bounswe2018group9#209]
@nazmicancalik  @gumityolcu  Dear backend team, can you please add a image property to events' model so that I can show the image later on? 

Thanks

**Comment by okyksl** [comment]
We may bypass storage of **multimedia**s altogether. **The Boss** also suggested to store them online elsewhere instead of in our own platform.

A possible suggestion:
```
multimedia: [
  type: 'image' | 'video',
  source: string // (validate as link) 
]
```

**Comment by gumityolcu** [comment]
We need to decide this together. I suggest talking about this first in the backend team meeting and then discussing the resulting ideas in Actopus meeting.

**Comment by nazmicancalik** [comment]
@okyksl You have mentioned video element in multimedia. Do we have video in requirements? It could be easier just to focus on images at first in my opinion. What do you say?

**Comment by okyksl** [comment]
The requirements uses the word **multimedia**. I think we can go with only **images** for now.

**Comment by okyksl** [comment]
@gumityolcu I still didn't had the opportunity to check your research. I will dive into this issue **ASAP**.

**Comment by okyksl** [comment]
We will have **multimedia** in three different ways: **user profile image**, **post attached multimedia**, **event attached multimedia**. I think we only need annotations for the third case. We can create **a separate data schema for multimedia** but i think that **if it lives inside `associated_object` then it will be more efficient**.

**Comment by gumityolcu** [comment]
Reviving this issue. I have created a branch for this feature.

**Comment by gumityolcu** [comment]
This is handled and is in PR #359
