### ISSUE TITLE
Important Things About Individual Notes

### ISSUE THREAD

**Issue by kemaltulum** [bounswe/bounswe2018group9#22]
Let's put things that are important for grading here, then we get all AAs easily.

**Comment by okyksl** [comment]
@kemaltulum should we turn this into a wiki page?

**Comment by serkan-ozel-2015400123** [comment]
@okyksl Because of this issue is about opening issues this issue should stay. 👍

**Comment by byklyci** [comment]
Actually, the best thing about this topic is team work. And I am sure that **_Team Actopus_** is a very coordinative,fixer,helpful and very staidly working team.

**Comment by okyksl** [comment]
@byklyci Indeed a very **soul-shattering** comment :)

**Comment by byklyci** [comment]
Especially, our wiki page and code page should look over again and again.We should add always new and brain labor updates in these parts.

**Comment by kemaltulum** [comment]
@okyksl I can convert this issue into a wiki page soon. 

I think if the number of issues opened by a single member is important we can observe statistics of us and somehow let everyone open issues, which would be engaging as well.

I am closing this issue for now, if you hear something about grading, please reopen this issue and mention the trick so that we can all benefit.
