### ISSUE TITLE
Branch Naming Convention

### ISSUE THREAD

**Issue by okyksl** [bounswe/bounswe2018group9#222]
Should we settle on a **branch naming convention** guys?

**Comment by serkan-ozel-2015400123** [comment]
I think there is a convention in the meeting document

**Comment by okyksl** [comment]
@serkan-ozel-2015400123 did we agreed on something? Is it `<task-type>|<main-scope>|<sub-scope>`, e.g `feature/frontend/routing`? I'm unaware of such convention.

**Comment by serkan-ozel-2015400123** [comment]
I said what is written to document but we can settle it on whatsapp if any other question arises @okyksl

**Comment by okyksl** [comment]
I wrote this convention in the [Workflow - Contribution Guide](https://github.com/bounswe/bounswe2018group9/wiki/Workflow) as `<type>/<platform>/<scope>`.
