### ISSUE TITLE
Possible bug in backend while creating event

### ISSUE THREAD

**Issue by serkan-ozel-2015400123** [bounswe/bounswe2018group9#227]
Hey team, I get 503 when I want to create a event in event create page. I suppose there is a problem with the backend since it does not respond for about 10 seconds. Same with postman : 

![screenshot from 2018-10-29 23-41-09](https://user-images.githubusercontent.com/32355782/47679053-532fee80-dbd4-11e8-8f6c-3c45a0d5beb3.png)

EDIT: 

**Can it be due to the fact that we don't send exactly these properties in eventAdd() function in Event controller?**:  
```
var event = new Event({
    name: req.body.name,
    price: req.body.price,
    owner: req.body.owner,
    description: req.body.description,
    date: req.body.date
  }); 
```

**Comment by gumityolcu** [comment]
I used the string "Wed Oct 17 2018 15:12:52 GMT+0300" while testing. This format should work.

**Comment by serkan-ozel-2015400123** [comment]
Issue was due to we were sending artists data field which backend does not have. The issue is resolved when I changed it to owner, to match event model in backend
