### ISSUE TITLE
Requirement Elicitation Task Seperation 

### ISSUE THREAD

**Issue by byklyci** [bounswe/bounswe2018group9#23]
We should seperate our requirenment eliciation. As we talked in Meeting 2 there should be an actions about requirenment. The team leaders select additional people under its work and help needed.Lets talk about !!

**Comment by gumityolcu** [comment]
We decided on 4 groups so we need to separate the requirements to 4 sub section. I think this(https://github.com/bounswe/bounswe2018group9/wiki/Requirements-Analysis) is a very good start. 

This is my proposition:
2 Groups for Functional Requirements/Member User Requirements
1 Group for Functional Requirements/Guest User Requirements
1 Group for Nonfunctional Requirements

If we accept this, we should decide how to divide the subsections of the member user requirements to 2 Groups

**Comment by akaogluozgur** [comment]
This suggestion sounds good to me. @gumityolcu

**Comment by okyksl** [comment]
@gumityolcu how about group for `Functional Requirements / System Requirements`? Maybe we could integrate `Guest User` with `Member User` so that we have a room for another team?

**Comment by gumityolcu** [comment]
@okyksl You are right, but I think the Member User part will be hard/long/complicated enough for 1 group. What do you think? We should pick the easiest of System Req.s/Member User Req.s/System Req.s and integrate it with Guest User Req.s

**Comment by okyksl** [comment]
How about this:
* 2 groups for `Functional Requirements / User Requirements`
* 1 group for `Functional Requirements / System Requirements`
* 1 group for `Non Functional Requirements`

2 groups can share the burden of `Member User Requirements`.

**Comment by nazmicancalik** [comment]
This sounds good to me @okyksl

**Comment by okyksl** [comment]
And also note that,
* Everyone should feel free to _(and in our team probably will)_ edit any kind of requirements.
* This separation of tasks is only for management purposes _i.e just in case requirements get out of hand at some point of the project_.

**Comment by serkan-ozel-2015400123** [comment]
I guess requirements are not in its final form. I don't know what Meriç assistant mentioned at customer meeting, so I don't know what to edit.

**Comment by kemaltulum** [comment]
Seems that there is just one step to go here to share titles between team leaders, then we can all contribute

**Comment by gumityolcu** [comment]
I will take the Nonfunctional Requirements part. I am opening a new issue for it. You can contribute in the comments.

**Comment by okyksl** [comment]
We couldn't handle the distribution of the tasks as expected. I think we should be more clear and specific on meetings to avoid this kind of situations. I'm closing this issue as first draft of `Requirement Analysis` somehow popped out of our collaborative efforts.
