### ISSUE TITLE
Heroku Deployment Link

### ISSUE THREAD

**Issue by serkan-ozel-2015400123** [bounswe/bounswe2018group9#230]
Planning to open a new branch for just this commit and merge into master

**Comment by okyksl** [comment]
Where is the link @serkan-ozel-2015400123?

**Comment by okyksl** [comment]
I added the deployment link to the home page of the wiki.

**Comment by serkan-ozel-2015400123** [comment]
Ok, thank you. But I was planning to add the link to readme of the repository, because of that I had closed this issue. @okyksl  Should we still consider doing it? Or wiki is enough ?

**Comment by okyksl** [comment]
Let's add to the **README** as well.
