### ISSUE TITLE
Scenarios for Presentation 

### ISSUE THREAD

**Issue by serkan-ozel-2015400123** [bounswe/bounswe2018group9#231]
**First Scenario**
1. User comes to site and sees sign in page and sign up button.
2. Presses sign up button.
3. User signs up with a name, surname, email and password. Acceptance 1
4. Backend system saves user information and encrypts the password securely. Acceptance 2,3
5. After sign in she sees sign in page again.
6. She enters the e-mail and password she was entered to sign up.
7. She logs in and sees feed the page. 
8. She can scroll down to browse all events that was created before.
9. She presses like button on events she liked and comment button on events she want to comment about.

**Second Scenario**
1. A signed user directly signs in. Acceptance 1 
2. User cannot see her related info right now. Acceptance 3 (by mistake there are two Acceptance 3)
3. System is able to check password email combination. Acceptance 3 
4. System tracks user until it logs out for further calls. Acceptance 4
5. System is not be able to serve user info. Acceptance 5
6. Signed user logs out whenever she wants. Acceptance 2

**Third Scenario**
1. A signed user comes and logs in.
2. She presses create button at the right bottom corner of the feed page.
3. By providing title, description, owner, date and price, she creates an event. Acceptance 1
4. A user can access an event in the feed by clicking it or by its id. Acceptance 2
5. System is able to save an event information and assign unique id to each. Acceptance 3
6. System can serve an event's detailed information. Acceptance 4

**Comment by serkan-ozel-2015400123** [comment]
Actuaaly these were not very not accurate xD

**Comment by okyksl** [comment]
Hopefully, we will **prepare an actual presentation for next customer meeting** instead of waiting everything to resolve by itself.
