### ISSUE TITLE
GET User Endpoint

### ISSUE THREAD

**Issue by serkan-ozel-2015400123** [bounswe/bounswe2018group9#232]
Can you please add endpoints to reach all controllers implemented in backend ?

**Comment by okyksl** [comment]
I speak with @nazmicancalik, we have a small bug to fix on this issue.

**Comment by gumityolcu** [comment]
I have resolved the bug and tested the endpoint locally. @nazmicancalik I have pushed my changes, it seems to work now. Can you review and generate a PR if you see fit?

**Comment by nazmicancalik** [comment]
@gumityolcu which branch are we talking about Ümit ?
Or is this already merged.

**Comment by gumityolcu** [comment]
@nazmicancalik It's the branch feature/bacjend/get-user

**Comment by serkan-ozel-2015400123** [comment]
You can merge after testing I think, so plaease open a pr thanks

**Comment by nazmicancalik** [comment]
I will create the pr now

**Comment by serkan-ozel-2015400123** [comment]
Here do we need this endpoint? The token gives everything we need ? @nazmicancalik  @okyksl

**Comment by okyksl** [comment]
The token only gives information of the **user logged**. We need to have some information related with **other users** so that we can display them to the user logged.
