### ISSUE TITLE
Preperation of Milestone 1 Report

### ISSUE THREAD

**Issue by akaogluozgur** [bounswe/bounswe2018group9#235]
We are creating the Milestone 1 Report. You can see and contribute the process from [here](https://github.com/bounswe/bounswe2018group9/wiki/Milestone-1-Report).

**Comment by nazmicancalik** [comment]
I will add the coding work part now. Also, last two points for the milstone report will be added.

**Comment by okyksl** [comment]
I think it's okay to close now.
