### ISSUE TITLE
Bug: JWT Token Includes Hashed Password

### ISSUE THREAD

**Issue by okyksl** [bounswe/bounswe2018group9#237]
When I decode the token on the frontend side, I see a password field which contains hashed long string. I think `password` field should be **marked as hidden in mongoose** to avoid any **GET related issues**.

**Comment by okyksl** [comment]
One more note guys, do we need to send both **token** and **user payload**? **Token** already includes necessary **user information**.

**Comment by nazmicancalik** [comment]
@okyksl  We don't actually need to send the user information seperately, but at that time we were asked to send the user to the frontend.

**Comment by byklyci** [comment]
I will handle this issue but I am trying to understand problem for now.

**Comment by byklyci** [comment]
For Laravel $hidden array in Eloquent models, which automatically hides the given list of properties before sending the object in the response.However, there is no out-of-the-box solution for this in Mongoose (yet).I am looking for the solution.

**Comment by okyksl** [comment]
I think there is **select** attribute for this purpose. As far as I remember, it was something like:

`password: { type: String, select: false }`

Can you try **select** attribute to see whether it actually works? There is also a **select** method you can call after **find**, **findOne** type of queries on the returned object.

**Comment by byklyci** [comment]
{
    "user": {
        "_id": "5bd328c98b70590becb953b8",
        "email": "admin@admin.com",
        "firstName": "Nazmican",
        "lastName": "Çalık",
        "password": "$2b$10$YnXvgdwz7eUM61Vf0sX.JuA8peoqBZ6xXA5kqEAeiurrMssHU2MmO",
        "__v": 0
    },
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1YmQzMjhjOThiNzA1OTBiZWNiOTUzYjgiLCJlbWFpbCI6ImFkbWluQGFkbWluLmNvbSIsImZpcnN0TmFtZSI6Ik5hem1pY2FuIiwibGFzdE5hbWUiOiLDh2FsxLFrIiwicGFzc3dvcmQiOiIkMmIkMTAkWW5Ydmdkd3o3ZVVNNjFWZjBzWC5KdUE4cGVvcUJaNnhYQTVrcUVBZWl1cnJNc3NIVTJNbU8iLCJfX3YiOjAsImlhdCI6MTU0MTY4MDgxN30.6eaRBZgIfSTtZGHxty9XKaUmFEDJUnYvoVnvKcCaN8w"
}

**Comment by byklyci** [comment]
Do you ask why token lenght is too long ? or anything else

**Comment by byklyci** [comment]
{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1YmU0M2Q5YTVjYWFlZDBmZjg2MjYyNzQiLCJlbWFpbCI6Inl1c3VmQGFjdG9wdXMuY29tIiwiZmlyc3ROYW1lIjoiWXVzdWYiLCJsYXN0TmFtZSI6IkthbGF5Y2kiLCJwYXNzd29yZCI6IiQyYiQxMCRBb2Y1dFR1TVRwWmF2dkRqM2JFLmR1UElYVWMybjFNakVOUXhlckhHQ3QvYVVlcDJPWXZtZSIsIl9fdiI6MCwiaWF0IjoxNTQxNjg0NzU3fQ.ckD3rqzsqw9_cGBJySsoygUZJqaHdDN02_EufDP8fRA"
}

**Comment by byklyci** [comment]
For now we just see the token not the user info. We talked @okyksl and he said that when he decoded the jwtjsontoken (inspecting the frontend side) he see the hashed password inside the token's decrypted form. Is it normal ? Or, how can we handle this ? @nazmicancalik

**Comment by byklyci** [comment]
I talked @nazmicancalik and we tried to hide password inside token payload, but our architecture is based on password and we have to control in the backend the correct password or not.If there is a solution from the frontend side (for example not allowed decoding the token payload or sth.), it will be easy solution.However we have to re-implement all the backend side user including implementation.

**Comment by byklyci** [comment]
I solved the problem and this issue is done. :+1:

**Comment by okyksl** [comment]
Thanks @byklyci!
