### ISSUE TITLE
Feat: JWT Token Expire Date

### ISSUE THREAD

**Issue by okyksl** [bounswe/bounswe2018group9#238]
The frontend side can't **extract any expiration date from the token** received from the backend. This might be a frontend bug or we might need to specify a `expiresIn` option as stated on [node-jsonwebtoken repo](https://github.com/auth0/node-jsonwebtoken).

**Comment by byklyci** [comment]
I need to talk any frontend team member.Right now, I also cant sign in. I am searching this issue right now.

**Comment by okyksl** [comment]
I can help you @byklyci, what do you need to proceed?

**Comment by byklyci** [comment]
**We handle this issue so I am closing the issue.**
