### ISSUE TITLE
Structure of the Resource Files

### ISSUE THREAD

**Issue by akaogluozgur** [bounswe/bounswe2018group9#24]
We decided to put external resources to our repo so that if anything happens to the external source, we are not affected by this. We accepted that images go under resources/images. What else we can put there? Is there something I missed?

**Comment by nazmicancalik** [comment]
I think for now the images will do. We can add other files as we follow along the course.

**Comment by okyksl** [comment]
Should we host the _resources for the wiki_ under folder `wiki`? I think `resources` might be used for some development purpose later on.

**Comment by gumityolcu** [comment]
Once the project logo is finished, we should put it there.

**Comment by nazmicancalik** [comment]
Seperating the wiki resources from other resources can be very useful, I agree with you @okyksl. Since there will be photos for wiki pages in the future we better not to mix them with other resources that are related specifically to the project.

**Comment by okyksl** [comment]
@akaogluozgur should I handle this with a PR?

**Comment by akaogluozgur** [comment]
@okyksl doesn't matter you or I can do it. Your choice
