### ISSUE TITLE
System Connection Error 

### ISSUE THREAD

**Issue by byklyci** [bounswe/bounswe2018group9#246]
The Ionic app does not connect via sign in or sign up right now. I dont understand the reason. Could you please help as a team leader to understand the situation. I dont know this is the frontend or backend fault.

**Comment by serkan-ozel-2015400123** [comment]
Plus, server is down for now with 503

**Comment by okyksl** [comment]
@byklyci did you try signing-in with `Postman`?

**Comment by okyksl** [comment]
It might be related with **CORS issues** we having. @nazmicancalik @kemaltulum should we enable **CORS**? [Here](https://github.com/expressjs/cors) is a simple package for express server to deal with this issue @nazmicancalik.

**Comment by gumityolcu** [comment]
I am looking into this issue.

**Comment by nazmicancalik** [comment]
What is the status of this issue ? Are we able to connect using cors middleware? Because, if it is the case we should close the issue.

**Comment by byklyci** [comment]
In the last PR is the solution but not merge yet. I guess.

**Comment by serkan-ozel-2015400123** [comment]
We were able to actually @nazmicancalik, but I am commiting the missing semicolon issue if @okyksl  did not fix it, and merging the branch and we can see that it will work hopefully. (because we tested it and it is working )

**Comment by serkan-ozel-2015400123** [comment]
Proxy is not working properly maybe ? I get this when I do  **ionic serve -- --proxy-config=proxy-dev.conf.json** 
and **npm run dev** locally 

![screenshot from 2018-11-08 22-13-47](https://user-images.githubusercontent.com/32355782/48221611-9859da80-e3a3-11e8-8d17-e61d4cc9f8a2.png)


This the output of **ionic serve -- --proxy-config=proxy-dev.conf.json**  when signing in 
![screenshot from 2018-11-08 22-14-55](https://user-images.githubusercontent.com/32355782/48221688-cd662d00-e3a3-11e8-9997-287684d4c2ac.png)

**Comment by serkan-ozel-2015400123** [comment]
Wrong alarm :)
