### ISSUE TITLE
Be aware of cors proxy

### ISSUE THREAD

**Issue by serkan-ozel-2015400123** [bounswe/bounswe2018group9#249]
@okyksl  said that he will prepare a document for local and production testing but, let me say in advance if you are working locally, that is you are going to start both backend and frontend, you should start backend via **npm run dev**  , you should use this command for frontend: **ionic serve -- --proxy-config=proxy-dev.conf.json**

If you use normal ionic serve, backend will be that in heroku 

Please be aware this when testing our system, thanks @bounswe/bounswe2018group9

**Comment by serkan-ozel-2015400123** [comment]
The document is ready

**Comment by okyksl** [comment]
We have to continue updating our **development documents**.
