### ISSUE TITLE
Actopus Team Logo Selection 

### ISSUE THREAD

**Issue by byklyci** [bounswe/bounswe2018group9#25]
Guys, we decided our team and project name.Then we should find a logo pictures, background and something else according to our project.Please comment your opinion about this situation.The logo in my opinion has huge affect to people's interest. As all of knows **_"First impression is an impact."_** 
I need your help....
Yusuf from Team Actopus.

**Comment by nazmicancalik** [comment]
@byklyci Yusuf you are right. Let's search for octopus icons maybe.

**Comment by serkan-ozel-2015400123** [comment]
![Image](http://mocomipullzone.anibraindigitalt.netdna-cdn.com/wp-content/uploads/2012/03/Mocomi_Activities_Cutouts_Octopus_vi_v02.jpg)

Cute octopus images? Maybe some more editing to it ? What do you think?

**Comment by okyksl** [comment]
![Image](https://cdn3.iconfinder.com/data/icons/aquatic-creatures/256/Octopus-256.png)

**Comment by serkan-ozel-2015400123** [comment]
@dkilyas What is the situation of your work?

**Comment by dkilyas** [comment]
Sorry for the latency. I made some improvements on the drawing, but I wasn't able to do much. Here is the last version.
![actopus](https://github.com/dkilyas/cmpe352/blob/master/resources/images/actopus.png)

**Comment by serkan-ozel-2015400123** [comment]
Good Work! If we want to add more activity later, we can edit. Let's put this logo to our wiki page and readme page (or only to wiki).
@dkilyas
