### ISSUE TITLE
Codacy Bot Proper Config

### ISSUE THREAD

**Issue by nazmicancalik** [bounswe/bounswe2018group9#254]
Which conventions do we follow in codacy bot? Do we have to apply if we use a proper eslint linter for development. In my opinion it makes the process slow. 

I have a suggestion: Let's use eslint for linting our code. We can use airbnb syntax as a template, since it is the most common one that is being used in Javascript environments. 

Refer here for more info: https://github.com/airbnb/javascript

**Comment by serkan-ozel-2015400123** [comment]
Dont have too many ideas about code review :S

**Comment by serkan-ozel-2015400123** [comment]
Better @okyksl set the config into final and good form

**Comment by okyksl** [comment]
@nazmicancalik @serkan-ozel-2015400123 I have set the **single quote** as preferred option. We are using `ESLint 5.7.0`. I added @nazmicancalik to the `Codacy` platform, and I welcome anyone who is interested to join `Codacy` dashboard.

@nazmicancalik @serkan-ozel-2015400123  Is there any further issues regarding with **automatic code review**?

**Comment by serkan-ozel-2015400123** [comment]
I guess no. @okyksl  thanks.

**Comment by serkan-ozel-2015400123** [comment]
Okay to close ?

**Comment by okyksl** [comment]
@nazmicancalik?

**Comment by okyksl** [comment]
Any suggestion on code convention can be followed-up here.
