### ISSUE TITLE
Possible bug about returning feed ?? 

### ISSUE THREAD

**Issue by serkan-ozel-2015400123** [bounswe/bounswe2018group9#255]
When I try to sign in it goes to this adress and nothing happens even though my credentials are true: http://localhost:8100/signin?return=%2Ffeed

EDIT: Why this works at heroku? i.e It does happen in local only

**Comment by okyksl** [comment]
@serkan-ozel-2015400123 did you updated your **backend**, specifically we need **expiresIn** field in JWT token to ensure that **frontend** can detect whether token is outdated or not. If you didn't, probably **expiresIn** field is missing and **frontend** thinks that your newly acquired token is already outdated.

**Comment by serkan-ozel-2015400123** [comment]
How to update my backend? I have pulled the commits and run npm install in case it is needed, what else?

**Comment by okyksl** [comment]
Did you restart all your local development processes? It may be related with caching or something.

**Comment by serkan-ozel-2015400123** [comment]
No, Its same. Does not matter if I do --proxy-config=.. or not

**Comment by serkan-ozel-2015400123** [comment]
I stopped backend and frontend processes then restarted them 

> Did you restart all your local development processes? It may be related with caching or something.

**Comment by okyksl** [comment]
@serkan-ozel-2015400123 does this issue persist?

**Comment by serkan-ozel-2015400123** [comment]
Yes, I will check if jwt returns a expiration date.

**Comment by nazmicancalik** [comment]
Are we done here @serkan-ozel-2015400123 ?

**Comment by serkan-ozel-2015400123** [comment]
Yes I deleted localstorage 'token' entry to solve
