### ISSUE TITLE
Errors frontend and backend integration

### ISSUE THREAD

**Issue by serkan-ozel-2015400123** [bounswe/bounswe2018group9#257]
I am going to handle errors such as
1 - If something wrong with client such as network error
2-  If something is wrong with backend such as : password was wrong, 

I suppose we need to have a consensus on return codes and errors. @okyksl should clearify what is needed to be settled, I think.

**Comment by nazmicancalik** [comment]
@akaogluozgur is working on the subject as of this week. This doesn't have to be a seperate issue. You can checkout @akaogluozgur 's job from here: #192 We will use express validator for database related validation and error handling. Basic error structure will be assumed as the express-validator error structure. 

Please refer here: https://express-validator.github.io/docs/

If you think the error format is okay for you please close the issue @serkan-ozel-2015400123 .

**Comment by serkan-ozel-2015400123** [comment]
Thanks

**Comment by okyksl** [comment]
We have both **mongoose errors** and **express errors**. Additionally, there are some edge case errors that **mongoose can't catch** such as _duplicate id_ (**mongodb returns raw error message**). Are we covering all that in #192?
