### ISSUE TITLE
Next Week's (19.02.2018) Agenda 

### ISSUE THREAD

**Issue by nazmicancalik** [bounswe/bounswe2018group9#26]
I think we should create the next week's meeting template and start to fill out the agenda. That way we can be prepared for the meeting. You can add your agenda items here when you find time. Then we can copy it to the meeting doc. (I think one agenda item is discussed in issue #18 by @byklyci )

__Add your agenda items here:__

- Actopus Project Logo Design (Actopus Team,Yusuf)
- The review session about our wiki page, sidebar,Readme etc. (Actopus Team,Yusuf)
- About the rating system, what should we do? For example: Top 10 activities in İstanbul or Best Activities about people's personel interest. And also , what will we look selecting best rated activities? Vote or Comment based!? Feedback from @mericturan in issue #18 (Actopus Team,Yusuf)
- Domain name selection.

**Comment by byklyci** [comment]
We should add Actopus project logo design in next meeting agenda also we have an issue about this situation and write your thoughts in there.

**Comment by nazmicancalik** [comment]
@byklyci We will definitely contribute to that issue. Yusuf could you also add your agenda item about logo design to the first post of this issue (issue body), that way it would be easy to collect agenda items and document them later. Thanks ._.

**Comment by byklyci** [comment]
Also we can add next meeting agenda, the review session about our wiki page, sidebar,Readme etc.Because the main importance for our Costumers are these topics right now.

**Comment by okyksl** [comment]
@byklyci can you add the items @nazmicancalik was talking about here?

**Comment by byklyci** [comment]
@okyksl I added the items about the next meeting agenda.

**Comment by nazmicancalik** [comment]
I have created the wiki page for the next week's meeting. You can add your agenda items to the Meeting 3 draft from [here](https://github.com/bounswe/bounswe2018group9/wiki/Meeting-%233-(19.02.2018))

**Comment by akaogluozgur** [comment]
I added the issue about whether we need the domain or not. If so which extension should be used.

**Comment by okyksl** [comment]
All the items here are added to [Meeting #3](https://github.com/bounswe/bounswe2018group9/wiki/Meeting-%233-(19.02.2018)), I'm closing this issue as [Meeting #3](https://github.com/bounswe/bounswe2018group9/wiki/Meeting-%233-(19.02.2018)) will be on tomorrow (19.02.2018) at 15:00.
