### ISSUE TITLE
Documents must be returned  populated in necessary cases

### ISSUE THREAD

**Issue by nazmicancalik** [bounswe/bounswe2018group9#260]
We need to return the events with the populate method, as we need to send the reference fields as a single unified document that is joined. 

**For example:** One event get request to /api/events/:id must return the event with all attendees in a single document.

Please refer here for more info: https://mongoosejs.com/docs/populate.
This page has a proper explanation, if further issues you can contact me.

**Comment by okyksl** [comment]
@gumityolcu I guess in future, there will be votes, comments & etc. too

**Comment by nazmicancalik** [comment]
We will reference this later.
