### ISSUE TITLE
User name field change-code review

### ISSUE THREAD

**Issue by byklyci** [bounswe/bounswe2018group9#263]
We want to change the user fields with the basic one , just include **name**. I will erase the lastName and the firstName.I will handle the problem. ***Frontend Team***, please be aware of this.

**Comment by byklyci** [comment]
I change the code and test it with the postman and everthing is cool.

**Comment by okyksl** [comment]
This is also addressed by **frontend team**.

**Comment by okyksl** [comment]
Upppsss, this is probably not **addressed by** @serkan-ozel-2015400123 in **profile page**.

**Comment by byklyci** [comment]
We handle this issue so I am closing it.
