### ISSUE TITLE
Interests Endpoints

### ISSUE THREAD

**Issue by nazmicancalik** [bounswe/bounswe2018group9#269]
We need to be able to hold the interests of a user. This is needed for feed #268 .
We should be able to get/save/update/delete the interests of the user.

**Comment by serkan-ozel-2015400123** [comment]
I am also going to use this endpoint to implement profile interest page

**Comment by okyksl** [comment]
What is the status here @gkhntkl?

**Comment by serkan-ozel-2015400123** [comment]
Interests are in user data model and user can be updated deleted accesed via get
