### ISSUE TITLE
Item Enumeration for References

### ISSUE THREAD

**Issue by okyksl** [bounswe/bounswe2018group9#27]
**The Boss** pointed out the importance of the enumeration of the items for `Requirements` document. 
I suggest we _utilize this idea more_:

* If there are any document which will be referenced later on, enumerate its items so that reference to the specific item can be done simply by numbers.
* Accordingly, update `Meeting Template` to utilize enumerable items.

One concern here to give attention: Should we enumerate **section by section** or should we **also enumerate sections** themselves?

A simple example on `Meeting Document` to clarify:
* Agenda has items numbered from 1 through 4. To refer to _second sub-item of the third item_, we say **3.2. of Agenda - Meeting #x**.
* Agenda is _already numbered with 2_ (Details is numbered with 1). To refer to _second sub-item of the third item_, we say **2.3.2. of Meeting #x**.

**Comment by gumityolcu** [comment]
I think the latter is better because we can just type "2" instead of "Agenda" 😄

**Comment by kemaltulum** [comment]
I think we can enumerate everything like Agenda, Discussion and Actions. It would be very simple as well as systematic. The latter is a decent choice for me as well

**Comment by serkan-ozel-2015400123** [comment]
If we can understand everytime we write 2.x.x of Meeting y, 2 corresponds to agenda then that's better. Because it is shorter.

Serkan -- An actopus member 😄

**Comment by okyksl** [comment]
I'm closing the issue, following style is adopted: 

> Agenda is already numbered with 2 (Details is numbered with 1). To refer to second sub-item of the third item, we say 2.3.2. of Meeting #x.
