### ISSUE TITLE
Interest Types

### ISSUE THREAD

**Issue by nazmicancalik** [bounswe/bounswe2018group9#270]
We need to define interest types so that we can fill our data model accordingly. Please create a document in wiki or simply document here the interest types.

**Comment by didemongu** [comment]
I determined a few interest types. Here these are
- Movie
- Music
- Jazz
- Biennial
- Theater
- Exhibition
- Modern Art
- Art Movie
- Photography
- Travel
- Festival
- Museum
- Workshop
- Ballet
- Dance
- Classical Music
- Opera
- Blues
- Turkish Folk Music
- Concert

**Comment by okyksl** [comment]
@nazmicancalik even though we talked that _we can store them in frontend client_, I think it would be better if we store them _in backend_. We may want to utilize them in **recommendation system** or possibly in **searching system**. (Related with #269)

**Comment by serkan-ozel-2015400123** [comment]
Music and blues and opera, movie and art movie etc. are subsets of each other should we change a little bit these @didemongu

**Comment by okyksl** [comment]
Are these correspond to our **semantic tags**?

**Comment by okyksl** [comment]
@nazmicancalik @didemongu can you checkout my question above on **semantic tags**? Additionally, are we done here?

**Comment by serkan-ozel-2015400123** [comment]
@okyksl Lets add some requirements if necessary and close this

**Comment by serkan-ozel-2015400123** [comment]
I think we should use them as tags

**Comment by serkan-ozel-2015400123** [comment]
1.3.1.2. Users shall be able to add additional information by providing semantic tags.

This exists already

**Comment by okyksl** [comment]
So these are the semantic tags at hand right? This seems to me a natural solution.
