### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by nazmicancalik** [bounswe/bounswe2018group9#271]
We need to be able to serve an endpoint for searching events. Search strategy can be cumbersome so we need a proper setup and research for this topic.

**Comment by byklyci** [comment]
We are finished the user and event data model. We are working the searching events right now. @nazmicancalik

**Comment by serkan-ozel-2015400123** [comment]
I have started frontend part of this and waiting for backend to finish this

**Comment by okyksl** [comment]
@serkan-ozel-2015400123 you may create a separate issue for the **frontend task**.

**Comment by nazmicancalik** [comment]
I have implemented a basic version on the branch feature/backend/search. You could check it, but I will improve it according to the frontend design needs.

**Comment by serkan-ozel-2015400123** [comment]
I am working on a new branch feature/frontend/search-link. In this branch I will try to make search work by connecting it to back-end. @nazmicancalik 

This is from our auth service provider, the search call I wrote
 `search(searchUser : boolean, searchString : string): Observable<any>{
    const params = new HttpParams()
      .set('isUser', searchUser.toString())
      .set('search', searchString);
    return this.http.get('/api/search', Object.assign(AuthService.options , params));
  }`

**Comment by nazmicancalik** [comment]
I will put the filtering options for advanced search here. Other than that we will perform a simple text based fuzzy search according to given input. We will handle advanced search in another issue. 
@kemaltulum I will decide the filtering options accordingly, so that you can create the frontend interface according to those filters. 

**Things we might need:**

* Location area picker
* Date picker
* Tag picker

**Comment by nazmicancalik** [comment]
Done!
