### ISSUE TITLE
Comment Card User Interface

### ISSUE THREAD

**Issue by okyksl** [bounswe/bounswe2018group9#276]
We have to implement interface for **post card**.

**Comment by serkan-ozel-2015400123** [comment]
Just a question:

Isn't our event card model designed to be used as a event post? What other posts a user can send, not an event?

**Comment by okyksl** [comment]
I would say they are almost identically same. For example, user might share **just text**.

**Comment by serkan-ozel-2015400123** [comment]
In my opinion, we should have post types:

1- Event with event card model 
2- Just text with including one or more of these:
    * photos or videos
    * annotations possible on text and photo 
    * location

What do you think ? @okyksl @dkilyas @didemongu @kemaltulum

**Comment by okyksl** [comment]
I don't think we need a **event card** rather we need to have **event details** page. Let's make a **feed card** which can contain **event link, multimedia & texts**.

**Comment by okyksl** [comment]
We will be consider **posts** as **comments**, thus we're going to create a comment cards interface.

**Comment by okyksl** [comment]
Note that this is done very long ago on `event-module-ui` branch but I'm waiting for the necessary stabilization of _data models_ and _api processes_ and _relevant data source interfaces_ for a long time.

**Comment by okyksl** [comment]
@kemaltulum will we present **comments in feed** page?

**Comment by okyksl** [comment]
This is done by @kemaltulum's new design.
