### ISSUE TITLE
Heroku & Ionic Feedback

### ISSUE THREAD

**Issue by okyksl** [bounswe/bounswe2018group9#278]
We're waiting your decision and suggestions related with `Heroku` & `Ionic` platforms.

**Comment by mericturan** [comment]
As we discussed both this semester (in CmpE451) and last semester (in Cmpe352), I do not want you to use any kind of hybrid platform including Ionic as the customer. However, @okyksl told me that Professor @uskudarli approved Group 9 to use Ionic. If that is truly the case, then I am ok. We are waiting for your comments about this issue Professor @uskudarli.

**Comment by uskudarli** [comment]
Greetings all,

Heroku is okay -- we actually prefer you do not, but we are accepting it.

Iconic is not okay, since this was an issue that had been rejected earlier.

All the best!

@mericturan

**Comment by okyksl** [comment]
We have discussed on this issue further _face-to-face_ and received justified concerns about our design. We have to understand these concerns, recognize potential potholes in our (mobile) design and take necessary actions.

I list couple of points for tracking purposes:

* Mobile location functionalities (GPS)
* Mobile multimedia functionalities (device gallery, device camera)
* Mobile content layout
* Mobile annotation interface

These points need to be addressed with _mobile user experience_ considerations.
