### ISSUE TITLE
Voting Endpoints

### ISSUE THREAD

**Issue by nazmicancalik** [bounswe/bounswe2018group9#279]
We need to implement a voting endpoint for event vote management.

**Comment by byklyci** [comment]
Vote attendance endpoint is required for registering users to the events.

POST to: /api/events/:id/vote

req.body: { voted: user_id, voteType: 0 | 1 | 2 }

0 => downvote
1 => upvote
2 => notvoted

This is the format I have come up with, any feedback or improvements are welcome. @nazmicancalik  @okyksl @serkan-ozel-2015400123 @gumityolcu

**Comment by byklyci** [comment]
I handled the vote endpoints according to our organization schema. We talk about this @nazmicancalik.

**Comment by byklyci** [comment]
I am closing this issue because vote endpoint is finished.
