### ISSUE TITLE
Location Service

### ISSUE THREAD

**Issue by okyksl** [bounswe/bounswe2018group9#281]
We need implement a **location service** that enables us to pick locations from the `Google API`.

**Comment by byklyci** [comment]
Can you inform me about the usage of Google API in the frontend side. @kemaltulum

**Comment by okyksl** [comment]
@kemaltulum ?

**Comment by okyksl** [comment]
I'm taking on this issue due to inactivity.

**Comment by okyksl** [comment]
I think we have handled this issue with our `MapComponent`.
