### ISSUE TITLE
Amazon Setup

### ISSUE THREAD

**Issue by okyksl** [bounswe/bounswe2018group9#299]
We have to transfer our backend application from `Heroku` to `AWS services`.

**Comment by gumityolcu** [comment]
We have applied for AWS Educate. We are waiting for response e-mail.

**Comment by okyksl** [comment]
@gumityolcu any updated on this?

**Comment by gumityolcu** [comment]
Last night we have tried to use DigitalOcean. It said the offer is not available right now. This is currently the status of the DigitalOcean option.

This morning we recieved the approval e-mail from AWS.

**Comment by okyksl** [comment]
Note that we deployed to [here](http://46.101.223.116:3000).
