### ISSUE TITLE
Event Creation Endpoints Update

### ISSUE THREAD

**Issue by nazmicancalik** [bounswe/bounswe2018group9#302]
Event creation endpoint has to be improved because we added new fields to the event data model. We need to make sure that before saving an event we have all the necessary fields created in the database.

**Comment by byklyci** [comment]
I am working on it right now.

**Comment by serkan-ozel-2015400123** [comment]
@byklyci  @nazmicancalik  please also update >> [click](https://github.com/bounswe/bounswe2018group9/wiki/Endpoint-and-Data-Model-Documentation)  after changes in endpoint and event data model

**Comment by byklyci** [comment]
Yeah we will do it ASAP @serkan-ozel-2015400123

**Comment by nazmicancalik** [comment]
I handled the endpoints for comments and in general structure, you can concentrate on #279 @byklyci
