### ISSUE TITLE
User Data Model Date of Birth and Nationality missing

### ISSUE THREAD

**Issue by serkan-ozel-2015400123** [bounswe/bounswe2018group9#307]
In requirements it says 

Users shall have a profile page which includes their information. (name, surname, date of birth, nationality)

we dont have date of birth and nationality in backend. Please add them too
@nazmicancalik @gkhntkl @gumityolcu @byklyci

**Comment by byklyci** [comment]
Ok I am looking this issue right now. :+1:

**Comment by byklyci** [comment]
We don't use surname and name format we just use the **name** format for both of them.I added the birth and nationality.I solved the problem and it is ready to PR whatever you need. @serkan-ozel-2015400123 .

**Comment by serkan-ozel-2015400123** [comment]
Thanks then
