### ISSUE TITLE
User Data Model Improvements needed

### ISSUE THREAD

**Issue by serkan-ozel-2015400123** [bounswe/bounswe2018group9#309]
> 1.1.3.1.2. Users shall be able edit their activity preferences.
> 1.1.3.1.3. Users shall have the choice between showing the activities they will attend or that they have attended in their profile page.
> 1.1.3.2. Settings
> 
> 1.1.3.2.1. Users should be able to select whether they want to take notification or not.
> 1.1.3.2.2. Users should be able to configure their privacy settings.,

According to these in requirements we need to store 
1- Users' settings including privacy settings. Like in twitter. 
2- All messages both read or not
3- Notifications.  Some kind of "A user commented about your event" 
Notification : 
> 1.2.9.1 In home page there shall be a part for notifications.
> 1.2.9.2 Notifications is sent under these circumstances
> 1.2.9.2.1 System should send notification including upcoming event information of the events which a user has indicated that he or she will attend.
> 1.2.9.2.2 System should send notification to event owner if somebody comments on event page.
> 1.2.9.2.3 System should send notification to users if somebody comments under their comment.
> 1.2.9.2.4 System should send notification to users if somebody follows them.

I dont say recommendations because we are willing to implement it through feed as I know. @okyksl @nazmicancalik @byklyci @gumityolcu

**Comment by serkan-ozel-2015400123** [comment]
@bounswe/bounswe2018group9

**Comment by okyksl** [comment]
@serkan-ozel-2015400123 we're not prioritizing **notifications** as of right now and I see that you included _privacy settings_ which is a **should** type of requirement. There are lots of tasks ahead to finish before our `Customer Milestone #2`, let's focus on our **settled features** in [Meeting #15](https://github.com/bounswe/bounswe2018group9/wiki/Meeting-%2315-Sprint-%233-(14.11.2018)). In any case, if you are running low on tasks you know who to contact :)

**Comment by okyksl** [comment]
The top priority changes on **user model** can be followed from #310. The **notification** feature which is stated by @serkan-ozel-2015400123 is not in our **three week agenda** and will be considered in future.
