### ISSUE TITLE
User Model Update

### ISSUE THREAD

**Issue by nazmicancalik** [bounswe/bounswe2018group9#310]
We need to update the user model to include following fields. Then we will implement the necessary endpoints.
* **Followers**
* **Following**
* **Interests**
* **Interests**
* **User Details**
   * **Nationality**
   * **Birthdate**
   * **Location/City**

**Comment by byklyci** [comment]
@nazmicancalik  I handled last night the user details part.The frontend team member @serkan-ozel-2015400123 want nationality,birth. And also I added the city right now. 
**SUMMARY** I handle:
User Details
    Nationality
    Birthdate
    Location/City

**Comment by nazmicancalik** [comment]
Good job @byklyci. We are done with the fields I am closing the issue. We will update the endpoints in a collective manner.
