### ISSUE TITLE
User change endpoint needed 

### ISSUE THREAD

**Issue by serkan-ozel-2015400123** [bounswe/bounswe2018group9#312]
I want to be able to change my users' date etc. every changable piece of indormation. Can you provide an endpoint like update user? 

Thanks 
@nazmicancalik @gumityolcu @gkhntkl @byklyci

**Comment by nazmicancalik** [comment]
https://github.com/bounswe/bounswe2018group9/pull/314

**Comment by nazmicancalik** [comment]
This issue is resolved, however we need to test the endpoints @gumityolcu .
