### ISSUE TITLE
Relative Navigation in Profile Page

### ISSUE THREAD

**Issue by srknzl** [bounswe/bounswe2018group9#316]
I have implemented absolute path navigation in profile module but actulaay it is better to have relative navigation, because if the parent routes change that one also should be changed. @kemaltulum in your appropriate time can you tell me how I can navigate to settings and to timeline pages relative to profile page.

In master 

Thanks

**Comment by serkan-ozel-2015400123** [comment]
The strange thing is if I come to profile page and press go to settings button by using relative navigation in the implementation, it works but If I press go back button at settings page and then try to go again to settings page, it does not do anything.

**Comment by okyksl** [comment]
@serkan-ozel-2015400123 @kemaltulum what's the status here?

**Comment by serkan-ozel-2015400123** [comment]
I don't know how to handle this, @kemaltulum  do you know I am waiting you actually

**Comment by kemaltulum** [comment]
I dealt with this issue while redesigning toolbar. It is working correctly now
