### ISSUE TITLE
Error Handling in Frontend 

### ISSUE THREAD

**Issue by srknzl** [bounswe/bounswe2018group9#317]
Regardless of whether detailed backend error handling( #228 #192)  is done or not,  we can state to user that something happened bad in backend of frontend. In upcoming weeks I can look to this by branching something like feature/frontend/error-handling

This includes sign in error, sign up error, event create error etc. Basically everything. This feature should always be parallelly go on with normal development process.

**Comment by okyksl** [comment]
@didemongu will make some improvements on this.
