### ISSUE TITLE
Domain Name, Extension and Brand Name Selection

### ISSUE THREAD

**Issue by kemaltulum** [bounswe/bounswe2018group9#32]
İf we are working on our logo, we can buy a domain and launch our product with a "Coming soon!" page.

I searched for the domains for "actopus", .com and .org extensions are invaded. The most proper domain extension seems to be .net. (about 13 dollar/year) or .io (about 50 dollar/year). Prices are taken from domain.com, other domain providers can offer cheaper prices.

Another thing about our brand name strategy is that no significant competitors for the keyword "actopus", which is good.

After a little bit elaboration, we can go on with a domain name and web page.

**Comment by gkhntkl** [comment]
in the ongoing meeting,we may talk this issue by looking at the cons and pros of those extensions.

**Comment by nazmicancalik** [comment]
@kemaltulum you are right we can buy a domain name and launch the product. However,  previous takers of this course claim that not so much done for coding part of the product. Also, there is a chance that there would be a specification about this topic (I mean the protocol for the course). So, it would be better first we consult assistants or Instructor. 
But there is a catch: we might not be able to found the domain name in the future.

**Comment by akaogluozgur** [comment]
Better to include both of this issues on the agenda of our next meeting.

**Comment by okyksl** [comment]
@kemaltulum if we consider development begins in September, there are lot of times to consider these. However, I am willing to give this a shot if we can produce something nice.

**Comment by byklyci** [comment]
Actually ı agree with Özgür and lets talk about this issue in the next meeting.

**Comment by nazmicancalik** [comment]
Since we decided to discuss this topic on next week's meeting, I am closing the issue. We can reopen it after meeting.
