### ISSUE TITLE
TEST Comments Endpoints

### ISSUE THREAD

**Issue by nazmicancalik** [bounswe/bounswe2018group9#320]
@akaogluozgur @gumityolcu Please test the last changed endpoints (event route endpoints) to make sure we get all the correct data as well as update and create correct data in the database.

@byklyci We need to test the vote after you finish voting endpoints. #279

**Comment by nazmicancalik** [comment]
Please share the test results here @gumityolcu @byklyci @akaogluozgur Have a good one : )

**Comment by okyksl** [comment]
@nazmicancalik, @akaogluozgur, @gumityolcu or @byklyci could you **list all the endpoints** that needs to be checked to the first comment in this issue so that we don't _miss any endpoint_.
