### ISSUE TITLE
TEST Vote Endpoints  

### ISSUE THREAD

**Issue by byklyci** [bounswe/bounswe2018group9#323]
@akaogluozgur @gumityolcu  Please test the last changed endpoints (event route endpoints) to make sure we get all the correct data as well as update and create correct data in the database. @nazmicancalik the vote endpoints is finished so we need to test the all event data model actually part by part.

**Comment by okyksl** [comment]
@nazmicancalik, @akaogluozgur, @gumityolcu or @byklyci could you **list all the endpoints** that needs to be checked to the first comment in this issue so that we don't _miss any endpoint_.

**Comment by akaogluozgur** [comment]
The endpoints needed to be checked are:

- addVote

- getVote

- updateVote

After I tested a bit, what I see is these endpoints will be complete when I add the request body validation part.

**Comment by nazmicancalik** [comment]
@akaogluozgur I think you are done with this testing part, please reopen the issue if you need it.Thanks for your efforts
