### ISSUE TITLE
Serve AWS Deployment from PORT 80

### ISSUE THREAD

**Issue by okyksl** [bounswe/bounswe2018group9#324]
@gumityolcu could you please turn our deployment to **default http port - 80** from our current **express development port - 3000**?

Additionally, there are some links on `README.md`, home page of wiki and sidebar _called_ `Actopus Alpha` or something like _deployment link_. Could you please also fix those links once you turned our deployment port?

**Comment by gumityolcu** [comment]
This issue is handled and needs to be merged. #346
