### ISSUE TITLE
TEST Attendance Endpoints

### ISSUE THREAD

**Issue by okyksl** [bounswe/bounswe2018group9#329]
@nazmicancalik, @akaogluozgur, @gumityolcu or @byklyci could you **list all the endpoints** that needs to be checked to the first comment in this issue so that we don't _miss any endpoint_.

**Comment by gumityolcu** [comment]
I will be testing:
POST api/events/:id/attendance
GET api/events/:id/attendance
PUT api/events/:id/attendance

**Comment by gumityolcu** [comment]
@nazmicancalik @okyksl @byklyci @akaogluozgur You can reach the resulting test document [here](https://github.com/bounswe/bounswe2018group9/wiki/Attendance-Endpoint-Tests-%231).

Apparently, the PUT endpoint doesn't work at all :smile:

**Comment by gumityolcu** [comment]
I am handling the issues with attendance @byklyci @akaogluozgur @gkhntkl @nazmicancalik

**Comment by gumityolcu** [comment]
Please check #352.

Closing issue
