### ISSUE TITLE
Should We Consult our Product Name to Our Customer?

### ISSUE THREAD

**Issue by kemaltulum** [bounswe/bounswe2018group9#33]
Should the name we choose for the product "Actopus" be approved by our customer?

**Comment by okyksl** [comment]
I talked with our **customer** and he approved the **Actopus**.

**Comment by cihatbaktir** [comment]
Well, I don't know why you assigned me to this issue since I am not your customer :) But I can make a couple of comments on it: You can choose any name you desire, unless it is **totally** irrelevant.

**Comment by okyksl** [comment]
@cihatbaktir I believe it's a misclick, sorry for the inconvenience :)
