### ISSUE TITLE
Change Meeting Time

### ISSUE THREAD

**Issue by serkan-ozel-2015400123** [bounswe/bounswe2018group9#34]
Can we change meeting time because it conflicts with my important PS section. (15 to 17).
Tuesday after 15.00, Monday 12.00-13.00, Wednesday after 14.00, Thursday from 9.00 to 12.00 fits me.

**Comment by dkilyas** [comment]
I am negative about changing the meeting time. I made my plans according to this time and actually it is the most suitable time for me. 
But, if most of us says that we can change it, then I will stick to that new plan.
(The ones that suit me are M:12-13 and W:after 14)

**Comment by akaogluozgur** [comment]
I am negative as well but again if most of the group select a time, I can change my plans.

**Comment by gkhntkl** [comment]
i can open a doodle poll to check all time section of the week if you wish.We can see there if there is a suitable time for us,if not we can continue with the usual time.

**Comment by nazmicancalik** [comment]
I added next week's meeting to the wiki sidebar. It is created according to usual time, but we can change if the group decides to change the time of the meeting. You can also add your agenda items to the Meeting 3 page.

**Comment by okyksl** [comment]
Should we handle this at #37, since poll is opened there?

**Comment by nazmicancalik** [comment]
Let's head to #37.
