### ISSUE TITLE
Advanced Search

### ISSUE THREAD

**Issue by nazmicancalik** [bounswe/bounswe2018group9#366]
We will have an advanced search interface for our application. Its request body will be defined in this issue. @kemaltulum We can talk about the design and parameters here. Greetings

**Comment by nazmicancalik** [comment]
We can also have a look at amazon's interface and get an idea about their search @kemaltulum . What is your preference?

**Comment by nazmicancalik** [comment]
@kemaltulum You can look at the parameters in the feature/backend/search branch. Please let me know if there is anything more needed. I will finish testing after the feedback.

**Comment by kemaltulum** [comment]
Sorry for the delay, today I will do some work and hopefully finish it.

**Comment by nazmicancalik** [comment]
Please report in a new issue if there is any problem with the advanced search.
