### ISSUE TITLE
Users Can Edit Unowned Events

### ISSUE THREAD

**Issue by okyksl** [bounswe/bounswe2018group9#368]
Currently, _any user_ can edit _any events_. We must **allow only the creator** of the event to edit the event.

**Comment by byklyci** [comment]
I tried to solve this problem with using the  {'owner' : req.params.id} inside the findByIdAndUpdate function I am not sure it is proper way but it seems like that.

**Comment by okyksl** [comment]
How about using `req.user` object?

**Comment by byklyci** [comment]
I am closing this issue.
