### ISSUE TITLE
The Poll to Set the Meeting Time

### ISSUE THREAD

**Issue by gkhntkl** [bounswe/bounswe2018group9#37]
here is the poll
[click here for the poll](https://doodle.com/poll/d2br32ugcarrizf9)

Please,dont forget to sign your name,thank you.
- [x] Gökhan Tekel
- [x] Didem Öngü
- [x] Hamdi Özgür Akaoğlu
- [x] Nazmican Çalık
- [x] İlyas Demirkıran
- [x] Yusuf Kalaycı
- [x] Serkan Özel
- [x] Kemal Tulum
- [x] Galip Ümit Yolcu
- [x] Oğuz Kaan Yüksel

**Comment by okyksl** [comment]
@bounswe/bounswe2018group9 what are we going to do? I don't see a secondary option to our current meeting time.

**Comment by gkhntkl** [comment]
I guess, we should obey the democracy.I dont have any offer.

**Comment by okyksl** [comment]
We'll review the result of this poll and discuss meeting scheduling in `Meeting #3` on `19 February, 2018 - 15:00`.
