### ISSUE TITLE
Nonfunctional Requirements Specification

### ISSUE THREAD

**Issue by gumityolcu** [bounswe/bounswe2018group9#38]
We prepare the Nonfunctional Requirements part of the requirements document here. Any comment, review, suggestion or contribution is welcome in the comments section.

The document being prepared is [here](https://github.com/bounswe/bounswe2018group9/wiki/Requirements-Analysis#2-non-functional-requirements).

**Comment by okyksl** [comment]
@gumityolcu just to get going, here are some _sub-headers_ to consider:

* Performance
* Security

**Comment by gumityolcu** [comment]
@gkhntkl  I am having doubts about this. For example, if I want to write "The passwords and personal information of users shall be encrypted before being put in the database." I can write this under a new section, 'Database' but I think it is more logical to put it under Security.

There may be requirements that should go under Database and no other section, but then the question would be, where do I put the example requirement above?

Any ideas?

**Comment by okyksl** [comment]
How about this:

* The passwords and personal information of users shall be protected. (Security item)
* Passwords shall be encrypted before being put in the database (Database item)

Additionally, why not use cross references such as this:

* **2.2.1.** **[2.1.1.]** Passwords shall be encrypted before being put in the database

where **2.2.1.** is the item number and **[2.1.1.]** is the reference item.

**Comment by gumityolcu** [comment]
The first version is on.

@okyksl I think we can do cross references like this if we define it in the beginning of the requirements. I didn't do any cross references but I added both security and database sections

**Comment by serkan-ozel-2015400123** [comment]
Under security we can write SSL certificate and reCaptcha features if we will use them. This two feature is very common so we should use them for security.

**Comment by serkan-ozel-2015400123** [comment]
I added some more requirements. Let's finish it today, thanks

**Comment by nazmicancalik** [comment]
I added some of the security protocols used widely to the requirements. Also edited some of the requirements to be specific and obvious. We can elaborate the existing requirements and make them specific

**Comment by akaogluozgur** [comment]
I added some non-functional requirements to security and robustness.
By the way, it seems the identifier of both robustness and performance was same (2.3) so I moved robustness to 2.7 and made changes accordingly. If this was on purpose I can change it back.
Also, I fixed some minor typos. Feel free to refine/change them.

**Comment by gumityolcu** [comment]
@akaogluozgur no it was an error. Nice work

**Comment by gkhntkl** [comment]
I added **Non-Functional Requirements 2.8**.If i am wrong,please correct me

**Comment by serkan-ozel-2015400123** [comment]
For annotations part, some of them can be written in system requirements.These parts consist of what system do to handle annotations on the other hand I think we should write properties of annotations to nonfunctional requirements.

**Comment by serkan-ozel-2015400123** [comment]
@okyksl  I agree

**Comment by akaogluozgur** [comment]
A new version of non-functional requirements is ready.
* Some of the existing requirements are reconstructed.
* New requirements and fields are added.
* Integrity field is added according to feedback from our customer
* Requirements are grouped by their definition of a [Wikipedia page](http://www.wiki-zero.com/index.php?q=aHR0cHM6Ly9lbi53aWtpcGVkaWEub3JnL3dpa2kvTm9uLWZ1bmN0aW9uYWxfcmVxdWlyZW1lbnQ) including definitions of almost all fields.

**You might want to change your existing references to the requirements if there is any, since the enumeration of fields and requirements are changed.**

Feel free to give feedback, new requirements will be added throughout the week. Please standby.

**Comment by gkhntkl** [comment]
I am not sure whether we should put the following item:

- Once the program is willingly turned off,the user should provide his/her password again and again to get into the platform.

**Comment by gumityolcu** [comment]
@gkhntkl I think we should not. This is basically a social media platform and when we look at other successful platforms (instagram, facebook, twitter  etc. anything really) we see that they have chosen to facilitate the sign in process after first sign in.

**Comment by gkhntkl** [comment]
@gumityolcu  okay.moreover,it does not make the user to spend more time.

**Comment by byklyci** [comment]
I added under avaliability part;
The system is available to existing Facebook users.

**Comment by byklyci** [comment]
I added under Privacy part;
In login page of the web and Android application,the password will not be visible unless user chooses the otherwise.

**Comment by serkan-ozel-2015400123** [comment]
Please correct this according to last ps. It is very long and complicated sentence. Can assitant said that please use "before,after, during" instead of "if".

In case of any inconsistency between incoming requests and database, the operation related to the request will be terminated, state of the database will be restored if any changes have been made. Moreover, an occasional log file will include the information about such events.

**Comment by gumityolcu** [comment]
2.2.3. The system shall achieve 99.5% uptime.

I can't understand this requirement. Uptime should be 99.5% of what?

**Comment by gumityolcu** [comment]
Also, in 2.2 and 2.3, I noticed we used the words "unexpected events" in order to indicate possible system failures that we didn't foresee. But event is a special word in our project and it has its definition in the glossary therefore we shouldn't use the word "event" to indicate anything other than an event in the context of our project. I changed the words "unexpected events" to "errors".

**Comment by okyksl** [comment]
@gumityolcu for **2.2.3.** can it mean _system should be working for at least 99.5% of the time?_

**Comment by gumityolcu** [comment]
@okyksl Yes, the problem was that I misremembered the definition of uptime 😄

**Comment by akaogluozgur** [comment]
@serkan-ozel-2015400123  Done.

**Comment by byklyci** [comment]
I am closing this issue, the review is done by @akaogluozgur and @byklyci.
