### ISSUE TITLE
Attendance Endpoints Tests & Fix

### ISSUE THREAD

**Issue by byklyci** [bounswe/bounswe2018group9#380]
I am handling the test about attendance endpoints and if there are any bugs, I will fix it.

**Comment by byklyci** [comment]
Last night I tested Post/Get/Put Attendance. I recognized that get and post are working but put is not properly working. I tried to handle it but I did not.

**Comment by nazmicancalik** [comment]
I will take over the issue. Good job

**Comment by nazmicancalik** [comment]
I have made the necessary changes to the code. Please accept the corresponding PR.
