### ISSUE TITLE
Annotation Endpoint review and refactor

### ISSUE THREAD

**Issue by gumityolcu** [bounswe/bounswe2018group9#385]
@nazmicancalik 

I have finished the first version of annotation data model and endpoints. Please review my work before we go any further because there are some vague points.

Do not hesitate to refactor the code when you think it is necessary but we will be working on the same files so we should be in touch while working.

**Comment by nazmicancalik** [comment]
Yes, of course. I will inform you accordingly, if I make any changes.

**Comment by nazmicancalik** [comment]
I have made the necessary changes to the endpoint it is mostly fine :) Good Job @gumityolcu
