### ISSUE TITLE
Postman Collection Share 

### ISSUE THREAD

**Issue by byklyci** [bounswe/bounswe2018group9#387]
{"version":1,"collections":[{"id":"70646e42-4e26-f27b-81db-b14d85c73784","name":"comments","timestamp":1544036914530,"requests":[{"collectionId":"70646e42-4e26-f27b-81db-b14d85c73784","id":"15b4badd-9e9e-4900-686b-20d59d97a4e9","name":"Get comments","description":"","url":"http://127.0.0.1:3000/api/events/5c030522a7ced70894276909/comments","method":"GET","headers":"Content-Type: application/json\n","data":"{\n  \"author\":  \"5bf80468be2e9f5045c7d48c\",\n  \"body\": \"Bar foo.\"\n}","dataMode":"raw","timestamp":0,"responses":[],"version":2},{"collectionId":"70646e42-4e26-f27b-81db-b14d85c73784","id":"47c86014-05b8-bb2e-5202-dda7551fe334","name":"edit comment","description":"","url":"http://127.0.0.1:3000/api/events/5c030522a7ced70894276909/comments/:commentId","method":"PUT","headers":"Content-Type: application/json\n","data":"{\n  \"body\":\"fooo\"\n}","dataMode":"raw","timestamp":0,"responses":[],"version":2},{"collectionId":"70646e42-4e26-f27b-81db-b14d85c73784","id":"5720f464-e5a2-70c6-725e-02da0e350f67","name":"Add Comment","description":"","url":"http://127.0.0.1:3000/api/events/5c030522a7ced70894276909/comments","method":"POST","headers":"Content-Type: application/json\n","data":"{\n  \"author\":  \"5bf80468be2e9f5045c7d48c\",\n  \"body\": \"Bar foo.\"\n}","dataMode":"raw","timestamp":0,"responses":[],"version":2},{"collectionId":"70646e42-4e26-f27b-81db-b14d85c73784","id":"ea3c2622-7757-de26-1170-98079a596b00","name":"Delete comments","description":"","url":"http://127.0.0.1:3000/api/events/5c030522a7ced70894276909/comments/5c066c7b9b6078632ff02b7c","method":"DELETE","headers":"Content-Type: application/json\n","data":"","dataMode":"raw","timestamp":0,"responses":[],"version":2}]},{"id":"81837770-a443-82b1-0cba-d14389cf58b8","name":"annotations","timestamp":1544726204646,"requests":[{"collectionId":"81837770-a443-82b1-0cba-d14389cf58b8","id":"059a1b96-4572-513f-5d9a-adbda2a1571c","name":"media body","description":"","url":"http://127.0.0.1:3000/api/annotations","method":"POST","headers":"Content-Type: application/json\n","data":"{\n\t\"@context\" : \"http://www.w3.org/ns/anno.jsonld\",\n    \"type\" : \"Annotation\",\n\t\"body\": {\n\t\t\"type\": \"Media\",\n\t    \"id\": \"link to media || mongoId\",\n\t    \"format\": \"jpeg\"\n    },\n    \"target\": {\n\t\t\"source\": \"actopus.com/events/:id\",\n\t    \"selector\":{\n        \t\"type\": \"XPathSelector\",\n        \t\"value\": \"img\",\n        \t\"refinedBy\": {\n   \t\t\t\t\"type\":\"FragmentSelector\",\n        \t\t\"value\": \"xywh=5,5,5,42\"\n       \t\t}\n        }\n\t}\n\n}","dataMode":"raw","timestamp":0,"responses":[],"version":2},{"collectionId":"81837770-a443-82b1-0cba-d14389cf58b8","id":"111ac98e-1c98-1ba9-d6e6-5fe4d749dfb3","name":"1 selector TextPos","description":"","url":"http://127.0.0.1:3000/api/annotations","method":"POST","headers":"Content-Type: application/json\n","data":"{\n\t\"@context\" : \"http://www.w3.org/ns/anno.jsonld\",\n    \"type\" : \"Annotation\",\n\t\"body\": {\n\t\t\"type\": \"TextualBody\",\n\t    \"value\": \"Annotation yeah\",\n\t    \"format\": \"plain-text\"\n    },\n    \"target\": {\n\t\t\"source\": \"actopus.com/events/:id\",\n\t    \"selector\":{\n        \t\"type\": \"TextPositionSelector\",\n        \t\"start\": 25,\n\t\t\t\"end\": 50\n    \t}\n\t}\n}","dataMode":"raw","timestamp":0,"version":2,"time":1544730497032},{"collectionId":"81837770-a443-82b1-0cba-d14389cf58b8","id":"3cd54b2e-da35-b1f6-ad4d-37f5499e011b","name":"refinedBy","description":"","url":"http://127.0.0.1:3000/api/annotations","method":"POST","headers":"Content-Type: application/json\n","data":"{\n\t\"@context\" : \"http://www.w3.org/ns/anno.jsonld\",\n    \"type\" : \"Annotation\",\n\t\"body\": {\n\t\t\"type\": \"TextualBody\",\n\t    \"value\": \"Annotation yeah\",\n\t    \"format\": \"plain-text\"\n    },\n    \"target\": {\n\t\t\"source\": \"actopus.com/events/:id\",\n\t    \"selector\":{\n        \t\"type\": \"XPathSelector\",\n        \t\"value\": \"img\",\n        \t\"refinedBy\": {\n   \t\t\t\t\"type\":\"FragmentSelector\",\n        \t\t\"value\": \"xywh=5,5,5,42\"\n       \t\t}\n        }\n\t}\n\n}","dataMode":"raw","timestamp":0,"version":2,"time":1544731476326},{"collectionId":"81837770-a443-82b1-0cba-d14389cf58b8","id":"40d779e6-23d5-6e6f-ea4e-f8d502bb089f","name":"get","description":"","url":"http://127.0.0.1/api/annotations?url=asdasd/5c06318b23e7ad3a0013e211","method":"GET","headers":"","data":[],"dataMode":"params","timestamp":0,"responses":[],"version":2},{"collectionId":"81837770-a443-82b1-0cba-d14389cf58b8","id":"a633eae5-9783-3c3c-06dd-50b53391d766","name":"1 selector XPath","description":"","url":"http://127.0.0.1:3000/api/annotations","method":"POST","headers":"Content-Type: application/json\n","data":"{\n\t\"@context\" : \"http://www.w3.org/ns/anno.jsonld\",\n    \"type\" : \"Annotation\",\n\t\"body\": {\n\t\t\"type\": \"TextualBody\",\n\t    \"value\": \"Annotation yeah\",\n\t    \"format\": \"plain-text\"\n    },\n    \"target\": {\n\t\t\"source\": \"actopus.com/events/:id\",\n\t    \"selector\":{\n        \t\"type\": \"XPathSelector\",\n        \t\"value\": \"img\"\n    \t}\n\t}\n\n}","dataMode":"raw","timestamp":0,"version":2,"time":1544730508865}]},{"id":"831f54a4-0ca6-9914-3dbf-a7ca3046973a","name":"events","timestamp":1542979551212,"requests":[{"collectionId":"831f54a4-0ca6-9914-3dbf-a7ca3046973a","id":"e3703a7b-f8fb-7533-0f1b-4fd6a65e44da","name":"add event","description":"","url":"http://127.0.0.1:3000/api/events/","method":"POST","headers":"Content-Type: application/json\n","data":"{\n    \"name\": \"Test Event 1\",\n    \"price\": \"10\",\n    \"description\": \"Test\",\n    \"date\": \"2010-01-01T00:00:00.000Z\",\n  \t\"duration\": {\n    \t\"length\": 10,\n      \t\"unit\" : \"hours\"\n    },\n    \"creator\": \"5bf80468be2e9f5045c7d48c\",\n    \"artists\": \"Turing\",\n    \"tags\": [],\n    \"medias\" : []\n  }","dataMode":"raw","timestamp":0,"version":2,"time":1544284785663}]},{"id":"83e09967-146e-0d11-4669-36e1f00e84a3","name":"users","timestamp":1542979194096,"requests":[{"collectionId":"83e09967-146e-0d11-4669-36e1f00e84a3","id":"3329a6e6-3db5-2bb4-fac1-059f38226658","name":"unfollow test","description":"Straightforward unfollow test","url":"http://127.0.0.1:3000/api/users/5bf802ecbe2e9f5045c7d48a/unfollow","method":"POST","headers":"Content-Type: application/json\n","data":"{\n  \"id\": \"5bf80468be2e9f5045c7d48c\"\n}","dataMode":"raw","timestamp":0,"responses":[],"version":2},{"collectionId":"83e09967-146e-0d11-4669-36e1f00e84a3","id":"3c431d61-0d9a-b7a9-a308-6b2c9c8e9d79","name":"GET","description":"","url":"http://127.0.0.1:3000/api/users/5c0632af23e7ad3a0013e219","method":"GET","headers":"Content-Type: application/json\n","data":"","dataMode":"raw","timestamp":0,"responses":[],"version":2},{"collectionId":"83e09967-146e-0d11-4669-36e1f00e84a3","id":"64874fdf-0cde-4b29-b51d-1094b44dd9ba","name":"addFollower test","description":"Straightforward addFollower test","url":"http://127.0.0.1:3000/api/users/5bf80468be2e9f5045c7d48c/addFollower","method":"POST","headers":"Content-Type: application/json\n","data":"{\n  \"id\": \"5bf802ecbe2e9f5045c7d48a\"\n}","dataMode":"raw","timestamp":0,"responses":[],"version":2},{"collectionId":"83e09967-146e-0d11-4669-36e1f00e84a3","id":"7ad8dcec-8f00-07c1-a214-0734c0ab4aa1","name":"follow test","description":"Straightforward follow test\n","url":"http://127.0.0.1:3000/api/users/5bf802ecbe2e9f5045c7d48a/follow","method":"POST","headers":"Content-Type: application/json\n","data":"{\n  \"id\": \"5bf80468be2e9f5045c7d48c\"\n}","dataMode":"raw","timestamp":0,"responses":[],"version":2},{"collectionId":"83e09967-146e-0d11-4669-36e1f00e84a3","id":"ae96eef6-a801-97dc-911c-a6855d14c101","name":"update user test","description":"Straightforward update test","url":"http://127.0.0.1:3000/api/users/5bf802ecbe2e9f5045c7d48a","method":"PUT","headers":"Content-Type: application/json\n","data":"{\n  \"user\":{\n      \"followers\": [],\n      \"following\": [\n          \"5bf80468be2e9f5045c7d48c\"\n      ],\n      \"interests\": [],\n      \"id\": \"5bf802ecbe2e9f5045c7d48a\",\n      \"name\": \"User 1\",\n      \"email\": \"test1@test.com\",\n      \"password\": \"$2b$10$sqQ2jDSwDf.URvUtR79d..T5Id0yQdvwmOQMs87aG/uWnB8yZoIze\",\n      \"_v\": 0\n\t}\n}","dataMode":"raw","timestamp":0,"responses":[],"version":2}]},{"id":"b4459b9c-e1d6-4892-5fb6-8826c94150e8","name":"attendance","timestamp":1543700868171,"requests":[{"collectionId":"b4459b9c-e1d6-4892-5fb6-8826c94150e8","id":"06afa0dc-e3b6-e230-fcab-a07b219ef259","name":"PUT attendance","description":"","url":"http://127.0.0.1:3000/api/events/5c030522a7ced70894276909/attendance","method":"PUT","headers":"Content-Type: application/json\n","data":"{\n\t\"user\":\"5c0023641aac670c90bb35eb\",\n\t\"attendanceType\": 1\n}","dataMode":"raw","timestamp":0,"responses":[],"version":2},{"collectionId":"b4459b9c-e1d6-4892-5fb6-8826c94150e8","id":"7463a591-c764-a076-1ef0-1cbb9b306693","name":"GET attendance","description":"Straightforward attendance","url":"http://127.0.0.1:3000/api/events/5c030522a7ced70894276909/attendance","method":"GET","headers":"Content-Type: application/json\n","data":"{\n\t\"user\":\"5c0023641aac670c90bb35eb\",\n\t\"attendanceType\": \"\"\n}","dataMode":"raw","timestamp":0,"responses":[],"version":2},{"collectionId":"b4459b9c-e1d6-4892-5fb6-8826c94150e8","id":"ae1cd5ee-a2f0-565d-6db6-f2446f01327a","name":"POST attendance","description":"Straightforward attendance","url":"http://127.0.0.1:3000/api/events/5c030522a7ced70894276909/attendance","method":"POST","headers":"Content-Type: application/json\n","data":"{\n\t\"user\":\"5c0023641aac670c90bb35eb\",\n\t\"attendanceType\": 2\n}","dataMode":"raw","timestamp":0,"version":2,"time":1543706302107}]},{"id":"bc08773c-c8e3-311c-ecee-19bb5fa2a5ad","name":"auth","timestamp":1542979191140,"requests":[{"collectionId":"bc08773c-c8e3-311c-ecee-19bb5fa2a5ad","id":"388b56b8-68b5-e5bc-5cb3-446a65481a42","name":"Empty Password Test","description":"Password field is empty","url":"http://127.0.0.1:3000/api/auth/signup","method":"POST","headers":"Content-Type: application/json\n","data":"{\n  \"name\" : \"Test User 2\",\n  \"email\" : \"test3@test.com\", \n  \"password\" : \"\"\n}","dataMode":"raw","timestamp":0,"responses":[],"version":2},{"collectionId":"bc08773c-c8e3-311c-ecee-19bb5fa2a5ad","id":"8badd389-f872-f302-9499-995fc72d52a8","name":"Omit Details Test","description":"details field is ommited","url":"http://127.0.0.1:3000/api/auth/signup","method":"POST","headers":"Content-Type: application/json\n","data":"{\n  \"name\" : \"Test User 2\",\n  \"email\" : \"test2@test.com\", \n  \"password\" : \"pass1\"\n}","dataMode":"raw","timestamp":0,"responses":[],"version":2},{"collectionId":"bc08773c-c8e3-311c-ecee-19bb5fa2a5ad","id":"938541cd-6113-3172-05af-ceb12420ce2d","name":"Full Request Test","description":"Every field is given in request body","url":"http://127.0.0.1:3000/api/auth/signup","method":"POST","headers":"Content-Type: application/json\n","data":"{\n  \"name\" : \"Test User 1\",\n  \"email\" : \"test1@test.com\", \n  \"password\" : \"pass1\",\n  \"userDetails\" : {\n    \"birth\": \"1996-11-03T00:00:00.000Z\",\n    \"nationality\": \"Turkish\",\n    \"city\": \"Istanbul\"\n\t}\n}","dataMode":"raw","timestamp":0,"responses":[],"version":2},{"collectionId":"bc08773c-c8e3-311c-ecee-19bb5fa2a5ad","id":"db206572-63df-cd11-94de-f219e6225022","name":"Duplicate Email Test","description":"An existing e mail is given in the body","url":"http://127.0.0.1:3000/api/auth/signup","method":"POST","headers":"Content-Type: application/json\n","data":"{\n  \"name\" : \"Test User 1\",\n  \"email\" : \"test1@test.com\", \n  \"password\" : \"pass1\"\n}","dataMode":"raw","timestamp":0,"responses":[],"version":2}]},{"id":"c3454123-2047-1270-bbe4-ab41cb976aa3","name":"user-media","timestamp":1544289983279,"requests":[{"collectionId":"c3454123-2047-1270-bbe4-ab41cb976aa3","id":"3873ab5d-2e49-1e3a-bac2-3baa299ff4ff","name":"Put Avatar","description":"","url":"http://127.0.0.1:3000/api/users/5c0632af23e7ad3a0013e219/avatar","method":"PUT","headers":"Content-Type: application/json\n","data":"{\n  \"creator\":  \"5c0632af23e7ad3a0013e219\",\n  \"link\": \"foo\",\n  \"description\": \"Bar foo.\",\n  \"filename\": \"foobar.jpg\"\n}","dataMode":"raw","timestamp":0,"responses":[],"version":2},{"collectionId":"c3454123-2047-1270-bbe4-ab41cb976aa3","id":"3f5d411b-fcb9-16d2-2e53-f1867156aa2a","name":"Delete Avatar","description":"","url":"http://127.0.0.1:3000/api/users/5c0632af23e7ad3a0013e219/avatar","method":"DELETE","headers":"Content-Type: application/json\n","data":"","dataMode":"raw","timestamp":0,"responses":[],"version":2},{"collectionId":"c3454123-2047-1270-bbe4-ab41cb976aa3","id":"523764c3-8127-0d91-a074-6326ba6d4d8d","name":"Put Cover","description":"","url":"http://127.0.0.1:3000/api/users/5c0632af23e7ad3a0013e219/cover","method":"PUT","headers":"Content-Type: application/json\n","data":"{\n  \"creator\":  \"5c0632af23e7ad3a0013e219\",\n  \"link\": \"foo\",\n  \"description\": \"Bar foo.\",\n  \"filename\": \"foobar.jpg\"\n}","dataMode":"raw","timestamp":0,"responses":[],"version":2},{"collectionId":"c3454123-2047-1270-bbe4-ab41cb976aa3","id":"5c3eb9c6-7f5e-d667-d8e1-44c0b563e8e7","name":"getCover","description":"","url":"http://127.0.0.1:3000/api/users/5c0632af23e7ad3a0013e219/cover","method":"GET","headers":"Content-Type: application/json\n","data":"","dataMode":"raw","timestamp":0,"responses":[],"version":2},{"collectionId":"c3454123-2047-1270-bbe4-ab41cb976aa3","id":"7c2c285c-41b9-409b-d7ca-5a62782c8e1b","name":"getAvatar","description":"","url":"http://127.0.0.1:3000/api/users/5c0632af23e7ad3a0013e219/avatar","method":"GET","headers":"Content-Type: application/json\n","data":"","dataMode":"raw","timestamp":0,"version":2,"time":1544290206790},{"collectionId":"c3454123-2047-1270-bbe4-ab41cb976aa3","id":"d56e3f57-c150-8985-c5a1-420ace08516d","name":"addCover","description":"","url":"http://127.0.0.1:3000/api/users/5c0632af23e7ad3a0013e219/cover","method":"POST","headers":"Content-Type: application/json\n","data":"{\n  \"creator\":  \"5c0632af23e7ad3a0013e219\",\n  \"link\": \"foo\",\n  \"description\": \"cover the last firebender.\",\n  \"filename\": \"foobar.jpg\"\n}","dataMode":"raw","timestamp":0,"responses":[],"version":2},{"collectionId":"c3454123-2047-1270-bbe4-ab41cb976aa3","id":"e395bdf1-daf1-bd93-915c-fc9ab64cb3b4","name":"Delete Cover","description":"","url":"http://127.0.0.1:3000/api/users/5c0632af23e7ad3a0013e219/cover","method":"DELETE","headers":"Content-Type: application/json\n","data":"","dataMode":"raw","timestamp":0,"responses":[],"version":2},{"collectionId":"c3454123-2047-1270-bbe4-ab41cb976aa3","id":"f4c83ca3-bc3d-9108-4c4c-52021cf718f2","name":"addAvatar","description":"","url":"http://127.0.0.1:3000/api/users/5c0632af23e7ad3a0013e219/avatar","method":"POST","headers":"Content-Type: application/json\n","data":"{\n  \"creator\":  \"5c0632af23e7ad3a0013e219\",\n  \"link\": \"foo\",\n  \"description\": \"avatar the last airbender.\",\n  \"filename\": \"foobar.jpg\"\n}","dataMode":"raw","timestamp":0,"version":2,"time":1544290898539}]},{"id":"eedeb6a1-1f63-6def-2ae5-bcbf5aaecf88","name":"event-media","timestamp":1543082856937,"requests":[{"collectionId":"eedeb6a1-1f63-6def-2ae5-bcbf5aaecf88","id":"31d11a7b-489a-d426-e549-ad416c5d5166","name":"Get media","description":"","url":"http://127.0.0.1:3000/api/events/5c0bee0ca875c50e58a855ff/media","method":"GET","headers":"Content-Type: application/json\n","data":"{\n  \"creator\":  \"5bf80468be2e9f5045c7d48c\",\n  \"link\": \"foo\",\n  \"description\": \"Bar foo.\",\n  \"filename\": \"foobar.jpg\"\n}","dataMode":"raw","timestamp":0,"version":2,"time":1544287047027},{"collectionId":"eedeb6a1-1f63-6def-2ae5-bcbf5aaecf88","id":"48dc0977-9aa7-938b-ea8b-81410ae5c201","name":"add media","description":"","url":"http://127.0.0.1:3000/api/events/5c0bee0ca875c50e58a855ff/media","method":"POST","headers":"Content-Type: application/json\n","data":"{\n  \"creator\":  \"5bf80468be2e9f5045c7d48c\",\n  \"link\": \"foo\",\n  \"description\": \"Bar foo.\",\n  \"filename\": \"foobar.jpg\"\n}","dataMode":"raw","timestamp":0,"version":2,"time":1544287049769},{"collectionId":"eedeb6a1-1f63-6def-2ae5-bcbf5aaecf88","id":"510e02a8-bf0e-c2f8-36b0-430794180c6f","name":"edit media","description":"","url":"http://127.0.0.1:3000/api/events/5c0bee0ca875c50e58a855ff/media/:mediaId","method":"PUT","headers":"Content-Type: application/json\n","data":"{\n  \"link\": \"foo\",\n  \"description\": \"Bar foo.\",\n  \"filename\": \"foobar.jpg\"\n}","dataMode":"raw","timestamp":0,"version":2,"time":1544287052705},{"collectionId":"eedeb6a1-1f63-6def-2ae5-bcbf5aaecf88","id":"961a43dd-ee09-d77b-bf44-67fded47e349","name":"delete media","description":"","url":"http://127.0.0.1:3000/api/events/5c0bee0ca875c50e58a855ff/media/5c08239143baad1bf6482213","method":"DELETE","headers":"Content-Type: application/json\n","data":"","dataMode":"raw","timestamp":0,"version":2,"time":1544287056659}]}],"environments":[],"headerPresets":[],"globals":[]}

**Comment by byklyci** [comment]
Here is the Postman Collection for our all test results. Just open Postman and import this collection to test whatever you want.

**Comment by kemaltulum** [comment]
This is exactly what I am looking for, thanks @byklyci
