### ISSUE TITLE
Error Messages Upon Wrong User Input

### ISSUE THREAD

**Issue by didemongu** [bounswe/bounswe2018group9#391]
We do not necessarily show necessary error messages like `Your password is wrong`, which is not good for users. I will deal with this situation.

**Comment by didemongu** [comment]
After a little search, I found out `Toast` component in Ionic. 
You can check it out [here](https://beta.ionicframework.com/docs/api/toast/)

**Comment by didemongu** [comment]
I added toast message in signin page for wrong user input.

**Comment by okyksl** [comment]
@didemongu will you handle the needed changes in #372?
