### ISSUE TITLE
Adding Team Member's Page to Wiki

### ISSUE THREAD

**Issue by byklyci** [bounswe/bounswe2018group9#4]
**_Due to 12 Feb ,2018_**
-------------------------------------------------------------------------------
Add your personal page to the [Wiki](https://github.com/bounswe/bounswe2018group9/wiki).

- [x] Gökhan Tekel
- [x] Didem Öngü
- [x] Hamdi Özgür Akaoğlu
- [x] Nazmican Çalık
- [x] İlyas Demirkıran
- [x] Yusuf Kalaycı
- [x] Serkan Özel
- [x] Kemal Tulum
- [x] Galip Ümit Yolcu
- [x] Oğuz Kaan Yüksel
----------------------------------------------------------------------------------

**Comment by byklyci** [comment]
Personal bio about us.

**Comment by okyksl** [comment]
@didemongu, @akaogluozgur, @gumityolcu

**Comment by serkan-ozel-2015400123** [comment]
I think we don't have didem in our repository group yet. What can we do about this?

**Comment by okyksl** [comment]
@serkan-ozel-2015400123, we have @didemongu in the repository :)

**Comment by serkan-ozel-2015400123** [comment]
Ok I realize now. Deleting the message that I posted on team page

**Comment by byklyci** [comment]
Just two person needed. @gkhntkl and @akaogluozgur could you please include your personel pages?

**Comment by byklyci** [comment]
I am closing this issue because it's done.
