### ISSUE TITLE
Functional Requirements - User Requirements Specification

### ISSUE THREAD

**Issue by byklyci** [bounswe/bounswe2018group9#40]
We prepare Functional Requirements/Member User Requirements part of the requirements document here. Any comment, review, suggestion or contribution is welcome in the comments section.
The document being prepared is [here](https://github.com/bounswe/bounswe2018group9/wiki/Requirements-Analysis#2-non-functional-requirements).

**Comment by byklyci** [comment]
I need your help for functional requirenments about our users please subscribe here your comments.

**Comment by gumityolcu** [comment]
I noticed there are some requirements that are linked to each other. I added references as @okyksl suggested in #38 . But I am not quite pleased with the format and didn't have any idea on how to do it differently. Can you check it and change it if you see fit?

The references are in 1.1.2.1.2 and 1.1.4.1.

**Comment by okyksl** [comment]
I think we should add a `Feed` section to the `User Requirements`.

**Comment by okyksl** [comment]
I assembled event related subsections into the `Events` subsection to make document easier to navigate.

**Comment by kemaltulum** [comment]
@okyksl I think it seems to be proper, but I realized an inconsistency. `Events` section has `Voting` subsection saying that users shall be voted. This is actually a small thing we can correct easily. On the other hand, I would suggest that we can consider organizing the requirements in a more object oriented manner.

I mean `User` entity has Profile, Feed and Personal Preferences...
`Event` entity has Date, Attendees, Semantic Tags,
And we can also define relationships between entities.

This is just a simple idea, we can discuss to make this more handy

**Comment by kemaltulum** [comment]
Another thing in my mind for functional requirements is the details of the `User Interface`

For example, when choosing start and finish dates of an event, will the user have two datepickers or daterange pickers. Or when searching an event, will we have a autocomplete functionality suggesting events immediately.

As you can guess, there is a bunch of messy things when we consider UI/UX design. Still we can work on it in a systematic manner like flow diagrams of screens.

**Comment by okyksl** [comment]
@kemaltulum I didn't check the `Voting` or any other subsection I moved semantically - _yet_. There might be some inconsistencies as you reported, please feel free to reorganize and edit.

I tried to organize the format of requirements to reflect _object oriented manner_ more and more. I believe **modularization** like that will make thinking through requirements more and more easy.

About the UI/UX design part, I believe these requirements are more about **what?** instead of **how?**.

**Comment by kemaltulum** [comment]
@okyksl Actually, I liked the way the requirements are organized but we need deciding on some points as I see. Then it will be much easier if we have a consensus with the structure.

You're right about the UI/UX design part. The details I mentioned are not requirements. I will have some additions considering how the user interact with the app under Functional - User requirements

**Comment by gkhntkl** [comment]
@kemaltulum @dkilyas  *Guest* section 1.1.1.3 should be corrected.The reason is that the guests are not allowed to behave just like a user.They can only visit the website but cannot  use the search engine of the website.There should be some restriction on guests.

**Comment by byklyci** [comment]
"Users shall have the option to Sign in via their Facebook account." ı also added this part under Availability. This topic is functional and nonfunctional in my opinion.Do you agree with me ?

**Comment by nazmicancalik** [comment]
I rearranged the following of the fields in  Requirement Analysis :
* __Authentication (Sign Up/Sign In)__: 
   * Authentication services is deleted.
      * I thought Authentication services should be given as a part of the sign up and sign in system. For example user should be able to see Forgot my password and remember me sections at sign in section that's why I restructured the authentication part.
      * Also, I guess changing e-mail and password should be added to the profile settings sub requirements.
   * Sign In / Sign Up revised. (**I need review/feedback from you here**)
      * I tried to make the requirements more specific and short as specified during class.
* __Timeline__: 
   * Timeline requirements are changed. (**I need review/feedback from you here**)
   * I added more items. (**Needs review**)
## **Questions**:

1. What can we put under **Profile/Personal** subsection? Any ideas ? @gkhntkl 
2. According to the feedback of customer `Guest Users shall not be able to make a search` which conflicts with our current requirements. **Should we delete our requirement about this ?**

**Comment by okyksl** [comment]
@nazmicancalik even though **The Customer** said that guests are not allowed to make search, I believe guests should be able to make search. To allure guests to sign up, we should show them what we have in our platform related with their queries.

**Comment by gkhntkl** [comment]
@okyksl i have contacted the customer about the searching,he said that guests will not be allowed to search in the platform,however,they will be able to see the pages via links  or google search results.

**Comment by gumityolcu** [comment]
@okyksl I agree,  we should talk about this issue in the next meeting

**Comment by gumityolcu** [comment]
1.1.4.2.3 Feed should include the events that are sponsored by verified users (Paid advertising business model)

Are we sure about this? This is not what I had imagined. There sure will be verified accounts but I thought a user would see events created by a verified account only if she follows it.

**Comment by okyksl** [comment]
@bounswe/bounswe2018group9 we need help especially on `User Requirements - Part 2`. Can we move our attention to `User Requirements` and finish it before the deadline - _26.02.2018_?

**Comment by nazmicancalik** [comment]
I will take over the part 2 by myself now. Can you give details which parts exactly do I need to review and update @okyksl

**Comment by okyksl** [comment]
**1.1.4.** through **1.1.8**.

**Comment by nazmicancalik** [comment]
Thanks @okyksl I will review and update those fields on Sunday.

**Comment by nazmicancalik** [comment]
@okyksl I deleted artist info for events since I thought there might not be an artist for an event. Mostly, I rearranged words and grammar for requirements for 
* 1.1.4. Feed
* 1.1.6 Events
   * Added android and web specifications for this item.
   * Attendance section is changed a bit.
   * Voting section is rearranged.
   * Annotation section is simplified and grammar corrected.
* 1.1.8 Verification  and 1.1.5 Communication
   * Seemed okay to me for now.

**Comment by okyksl** [comment]
@nazmicancalik can we add _artist info_ as at least `should` requirements to _contribution part of the events_? I checked the project description and it seems to me _artist info_ listed one of the core data of the _events structure_.

And further, should we consider the case where same event repeats in time and location? Imagine a movie, it will be on multiple locations at different times. How we are going to handle that cases?

**Comment by byklyci** [comment]
This issue is done and ı am closing it.
