### ISSUE TITLE
Functional Requirements - System Requirements Specification

### ISSUE THREAD

**Issue by gumityolcu** [bounswe/bounswe2018group9#41]
System Requirements part of the [Requirements Document](https://github.com/bounswe/bounswe2018group9/wiki/Requirements-Analysis) needs some items.

Please add any suggestions or ideas either here or directly to the document.

**Comment by okyksl** [comment]
I added `Search` and `Recommendation` subsections.

**Comment by kemaltulum** [comment]
I added `Admin Panel` subsection. I hope, I am not wrong with the definition of system requirements. Please correct me if needed

**Comment by okyksl** [comment]
I'm not so sure about `Admin Panel` belongs to `System Requirements`. It seems like a _user requirement_ since moderators of the app are also _users_. However, there are related _system requirements_ about `Admin Panel` such as _system should be able to log ill-behavior reports about a user_.

**Comment by serkan-ozel-2015400123** [comment]
@gumityolcu 1.2.3.1.1 Admin shall be able to delete or edit events when necessary 
1.2.3.1.1 Admin should be able to create roles with different rights 

I think these are not system functionalities. We should either change their syntax or delete them

**Comment by serkan-ozel-2015400123** [comment]
I have sent this document to Ümit but I want everybody to be able to see the changes that I am considering to make.

### 1.2.4 Annotations
* Annotations shall be retrieved by the system when a page with annotaions is opened
* Annotations shall be stored in the system
* System shall test the annotations to assure validity.
#### 1.2.4.1 Annotation Format 
* System should allow explanation texts 
* System should allow questions and answers 
* System should allow geographical references 
* System should allow images
* System should allow links to other sites
### 1.2.5 Events
* System shall store events attendance information
* System shall store attendance information for passed events, either attended or not.
* System shall store attendace information for incoming events
     * It can be will attend
     * It can be may attend 
     * It can be won’t attend.
* System shall show events in a particular location. e.g in a city
### 1.2.6 Database
* System shall store data to the database
* System shall update data in the database
* System should make integrity check once a week to prevent data loss.
### 1.2.7 Voting
* System shall store voting data.
* System shall retrieve voting data.
* System shall track voting information of users, events and comments.
### 1.2.8 Noticification
* Mobile version shall send notifications to users from notifications panel.
* (What can be in notifications?)

**Comment by serkan-ozel-2015400123** [comment]
I am adding these changes to document

**Comment by serkan-ozel-2015400123** [comment]
@nazmicancalik @gkhntkl  The user requirements is up to you, so please be informed that I am deleting this because it is about user requirements.

This was under admin panel
**1.2.3.1.1** Admin shall be able to delete or edit events when necessary
**1.2.3.1.1** Admin should be able to create roles with different rights

**Comment by serkan-ozel-2015400123** [comment]
@akaogluozgur @byklyci  And also I think format of annotations allowed should be under nonfunctional so  please add these information there 

1.2.4.1 Annotation Format
System should allow explanation texts
System should allow questions and answers
System should allow geographical references
System should allow images
System should allow links to other sites

**Comment by gkhntkl** [comment]
I guess,the user should be allowed to take instant photos and share it via the program which means that the program will have some permission to use the camera.(other folders may be included) 

what do you think?

**Comment by serkan-ozel-2015400123** [comment]
@gkhntkl @nazmicancalik  I agree. We need camera access for mobile version. In this case, you should add a user requirement about photo taking in mobile version. After that, I think we can also add upload functionality of user and system web version.

**Comment by okyksl** [comment]
@gumityolcu **1.2.9.2.4** says: 

> System should send notification to users if somebody sends follow request to them.

Will there be any requests in the follow procedure?

**Comment by serkan-ozel-2015400123** [comment]
@okyksl Actually, I need to change it. I tried to mean "if somebody follows the user"

**Comment by serkan-ozel-2015400123** [comment]
I think we are done. If so let's close this issue for now. @gumityolcu

**Comment by serkan-ozel-2015400123** [comment]
We have decided with @gumityolcu to close this for now. Leading problematic topics can exist by seperate issues.
