### ISSUE TITLE
Outgoing questions on project plan

### ISSUE THREAD

**Issue by serkan-ozel-2015400123** [bounswe/bounswe2018group9#42]
Here are the questions that we are going to ask to Suzan Uskudarli. The other concepts can be either clear for us or missed by us.  Feel free to recommend new ones.

1How many milestones should we use? **There is a example on the slides** : 
Examples of Activities:
Major Activities: 
Planning
Requirements Elicitation
Requirements Analysis
System Design
Object Design 
Implementation
System Testing
Delivery

Sub-activities during 
requirements analysis: 
Define scenarios
Define use-case model
Define object model
Define dynamic model
Design user interface

2-Are we going to write due dates for all milestones ?
3-Are we going to implement gant charts etc? (Graphical data showing)
4- Are we going to update this part always : where are we, where we should be, what we can do to make up and what is the difference ?
( **Actually need not to ask**: Throughout your project development, you will be expected to track your progress in accordance with your plan as well as keep your plan up to date. The goal of the plan is to organize the work by estimating the effort and resources needed complete the tasks and to compare the execution (real life progress). This way you are able to assess how you are progressing.)
 **This means we should have a part containing answers to these 4 questions and we should always update these questions**
5- whether or not we should make something basic involving milestones and major activities **only** .

**Comment by nazmicancalik** [comment]
@serkan-ozel-2015400123 Additionally we can ask:
* What time they expect us to finish the project ?
   * End of 451 or end of this term?
* Also, should we determine `when we are going to implement which part` now ? (Because if we are going to make a timeline for all activities and tasks we should clearly specify which part should be done when?)

**Comment by serkan-ozel-2015400123** [comment]
@nazmicancalik  I find out that hw3 mentions that we should update it always as we advance developing project. You can find it on first post.

**Comment by okyksl** [comment]
I think one of the most critical questions is definitely the format of the `Project Plan` draft. Is it up to us? Will it be **WBS** structure or else?

We need more _specification and guidance_ on this task. If it is up to us **mostly**, then I strongly suggest that we should have another meeting on _21 February 2018, Wednesday 20:00 online_.

**Comment by serkan-ozel-2015400123** [comment]
@okyksl I don't think it is not that flexible. And I think, for now, we can only do wbs. (basically same as writing milestone and objectives hierarchically)

**Comment by nazmicancalik** [comment]
I agree with @okyksl  We should definitely meet up to clearly specify ambiguities about this homework and also talk about what can be done. If possible we can also meet face-to-face.

**Comment by serkan-ozel-2015400123** [comment]
"Now, create a high level project plan that outlines the major activities and milestones."
In Hw3 it says this. Therefore, in my opinion, we should make something basic involving milestones and major activities **only**.

**Comment by nazmicancalik** [comment]
Actually @serkan-ozel-2015400123 you are right. It is highly possible that we should put the answer of these questions on the plan. However, there might one aspect of this questions being expected to answer:
Suzan Hoca and Meriç Hoca might want to get the answer via looking at the gant chart  in the project plan. Not necessarily by looking at question answers. Because even the slack activities are included in the gant chart. In short I think we should ask :)

**Comment by serkan-ozel-2015400123** [comment]
@nazmicancalik  Of course we will. When should we ask?

**Comment by nazmicancalik** [comment]
@serkan-ozel-2015400123  Let's ask , if there is nothing to add we can close this issue. Let's continue the conversation thorough whatsapp from now on

**Comment by okyksl** [comment]
I think the specific questions asked at the homework meant to be answered by our `Project Plan` document _at any time by inspecting it_. I don't think there should be regularly updated pre-fetched answers on the document, rather `Project Plan` document will be the place to track and evaluate these kind of questions.

**Comment by serkan-ozel-2015400123** [comment]
Hi,

I am Serkan from BOUNSWE organization, group9. For us plan is a bit ambigious, so could you inform us, please?

Questions:

1)How many milestones should we use? There is a example on the slides :

Examples of Activities:
Major Activities:
Planning
Requirements Elicitation
Requirements Analysis
System Design
Object Design
Implementation
System Testing
Delivery

Sub-activities during
requirements analysis:
Define scenarios
Define use-case model
Define object model
Define dynamic model
Design user interface

Should we write milestones spanning the whole project like this?

How can we know which milestones will we put there when we are at the beginning?

2-Are we going to write due dates for all milestones(It is hard to estimate due dates now for future tasks) ?
3-Are we going to implement gantt chart, wbs or critical path for hw3(for this week)?
4- Are we going to include these questions in the plan and if so are we going to  update this part during development?

1-where are we now?

2-where should we be?

3-what is the difference?

4- what we can do to make up?
Thanks in advance

This is email I have sent

**Comment by okyksl** [comment]
@serkan-ozel-2015400123 could you forward the answer to this email? And also if the discussion with **The Boss** continues could you please CC all of us to the ongoing discussion?

**Comment by serkan-ozel-2015400123** [comment]
Ms uskudarli answered through piazza to class this noon.
