### ISSUE TITLE
Actopus Database Backup and Migration from mLab

### ISSUE THREAD

**Issue by byklyci** [bounswe/bounswe2018group9#429]
We need to create backup our database for the final customer report.I will handle this issue.

**Comment by byklyci** [comment]
The terminal commands as follows for our database backup:
* **I hide our password beacuse of security policy.** 
## For the exporting database binary format is;
* mongodump -h ds141813.mlab.com:41813 -d actopus2018 -u admin -p ........... -o ActopusDatabase/actopus2018 
## For the exporting annotation collection json format is;
*  mongoexport -h ds141813.mlab.com:41813 -d actopus2018 -c annotations -u admin -p .......... -o annotations.json
## For the exporting user collection json format is;
*  mongoexport -h ds141813.mlab.com:41813 -d actopus2018 -c users -u admin -p .......... -o users.json
## For the exporting event collection json format is;
*  mongoexport -h ds141813.mlab.com:41813 -d actopus2018 -c events -u admin -p .......... -o events.json
## For the exporting vote collection json format is;
*  mongoexport -h ds141813.mlab.com:41813 -d actopus2018 -c votess -u admin -p .......... -o votes.json

**Comment by byklyci** [comment]
I am closing this issue because it is done.

**Comment by gumityolcu** [comment]
I think we should reopen the issue because this has to be done **after** #437 doesn't it?

**Comment by byklyci** [comment]
I am reopening this issue because of the 100 elements needed for the report.

**Comment by didemongu** [comment]
#437 is closed

**Comment by byklyci** [comment]
I will backup the database again because the 100 item is added

**Comment by byklyci** [comment]
I will close when I finish @didemongu not yet.

**Comment by byklyci** [comment]
I finalized the database backup.
