### ISSUE TITLE
Ranking System and Algorithms

### ISSUE THREAD

**Issue by gumityolcu** [bounswe/bounswe2018group9#43]
I added the Ranking section to Functional Requirements/System Requirements. I wasn't sure if we want the users to be ranked too so I didn't add it. What do you think? Any other points?

Also,
I also did some reading on the ranking algorithms currently in use. I found these articles about [reddit](https://www.reddit.com) and [Hacker News](https://news.ycombinator.com/). If you are interested check them out there are some really good ideas : 
https://medium.com/hacking-and-gonzo/how-reddit-ranking-algorithms-work-ef111e33d0d9
https://medium.com/hacking-and-gonzo/how-hacker-news-ranking-algorithm-works-1d9b0cf2c08d

Here's the summary: there are different ways to do it. We can use mathematical tricks, statistics etc. There are machine learning techniques. But according to the first article, Amazon (where ranking is very important) uses the simple <num_of_upvotes>/<num_of_votes> formula so we may use something simple too.

Moreover, we will need to decide how to integrate these ideas with our multiparameter ranking requirements. The answer may depend on how much time/work we will have before our deadlines, which programming languages we will be using etc. So I think it is best to make this decision in the future, when we have a more precise idea of what we will be doing (after the planning process perhaps).

**Comment by serkan-ozel-2015400123** [comment]
I think this is a good concept. And I don't think we should rank users. It is enough to verify a certain user is fake or real person. 

Moreover we have recommendation system. What is the difference between rec. system and ranking? 
`System shall send recommendations based on followed users, activity preferences and events attended.`
System already recommends events to users. Ranking can be effective in terms of searching but I think recommendation includes this as well. If so, we can put ranking under recommendation header.
@gumityolcu

**Comment by okyksl** [comment]
Shouldn't ranking also consider users? Let's say one user tries to find another user by name -_might be an verified artist_- how come we will rank that search among the users?

**Comment by serkan-ozel-2015400123** [comment]
Yeah, maybe we should consider the popularity of people who have same names and according to the ranking list more popular one.

**Comment by gumityolcu** [comment]
@serkan-ozel-2015400123 @okyksl  Okay, we have a problem. I thought ranking system was to be used when a user wants to see the Top or Hot events in our platform. Serkan thought it was to be used for recommendation purposes. I think recommentdation should be a different system because there we care less about the votes, date and number of attendees of an event and we care more about if a specific user has liked or attended an event of similar kind. I think recommendation system should be different from the ranking system. Oğuz thought we would use recommendation for sorting our search results. That is plausible but we should decide precisely if our software will have a "Top Ranking Events" part where ranking is done regardless of the user, or if we want to use the ranking system only for sorting purposes.

**Comment by byklyci** [comment]
I agree with @gumityolcu ranking system and recommedation system is different.But there will be a problem and much work to seperate them. So ı am confused about this situation.What will we do exactly?

**Comment by okyksl** [comment]
`Ranking System` will be discussed further on `Meeting #4` - _26.02.2018_.
