### ISSUE TITLE
Realistic Database Preparation

### ISSUE THREAD

**Issue by gumityolcu** [bounswe/bounswe2018group9#437]
According to the mail sent to us by the customer, we need to have **at least 100 items** that are **real** or **realistic**.

@didemongu @dkilyas  Can anyone of you handle this issue?

**Comment by didemongu** [comment]
What is the mean of "item"? Does it mean only event or it contains users? @gumityolcu

**Comment by kemaltulum** [comment]
In the case of Actopus approximately 70 events from 30 users might be sufficient. Numbers may change

**Comment by didemongu** [comment]
I added 100 items
