### ISSUE TITLE
Project Plan Elements and Project Libre Usage 

### ISSUE THREAD

**Issue by serkan-ozel-2015400123** [bounswe/bounswe2018group9#44]
We have asked our questions to customer and she has not returned directly but she has posted new contents to piazza. This is what she has added to hw3:
```
 Note that this plan will be a very high
 level plan at this point.
The point it to get familiar with 
 project planning software and
 the elements of a project plan, i.e. milestones, tasks, and resources.
Please use: https://www.projectlibre.com/ for
 your projects. You may choose any strategy 
for milestones. We will use your choices to 
discuss their viability.
```
Can all of us go and check this planning site which our instructor has sended ?
[Project Libre](https://www.projectlibre.com/)

**Comment by okyksl** [comment]
@bounswe/bounswe2018group9 I set up a team meeting between 20:00 - 23:00 on Friday (23.02.2018) to discuss `Project Planning` phase.

**Comment by serkan-ozel-2015400123** [comment]
I guess we are more familiar with the program now after meeting3.1. Closing the issue
