### ISSUE TITLE
Glossary - Project Jargon

### ISSUE THREAD

**Issue by okyksl** [bounswe/bounswe2018group9#45]
We must define our `Glossary` i.e _project jargon_ to communicate with precision and clarity. Here are few notes about the `Glossary`:

* Since our glossary will be our _project's vocabulary to express our ideas_ getting familiar with it is everyone's job.
* To achieve precision and clarity as stated, glossary should be a reference point in our communications and especially **documents**.
* With project advances, so must our glossary to reflect the changes in the project.

**Comment by didemongu** [comment]
I think a glossary in alphabetical order is more readable. I alphabetised our existing glossary. We should add new terms by considering the alphabetical order.

**Comment by serkan-ozel-2015400123** [comment]
* activity preferences

I am changing all the words like interests, event choices etc. to this word. Moreover, I defined it on the glossary. We can use same words for same meaning, otherwise we may need to define them multiple times.

**Comment by okyksl** [comment]
I observed that we use **activity** and **event** interchangeably, should we decide on one of them?

**Comment by okyksl** [comment]
**Event** is chosen over _activity_.

**Comment by okyksl** [comment]
@bounswe/bounswe2018group9 `Glossary` updated from scratch, so could you please review the `Glossary` to get familiar with and then also update your requirements section according to the `Glossary`?

**Comment by serkan-ozel-2015400123** [comment]
@didemongu @okyksl Do you put subitem under annotation word intentionally?

**Comment by okyksl** [comment]
@serkan-ozel-2015400123 It's intentionally, I though it will be useful to define annotation types seperately.

**Comment by okyksl** [comment]
I'm closing this issue as we prepared a comprehensive [Glossary](https://github.com/bounswe/bounswe2018group9/wiki/Requirements-Analysis#glossary) to satisfy our needs.
