### ISSUE TITLE
Meeting #4 Agenda Preparation

### ISSUE THREAD

**Issue by serkan-ozel-2015400123** [bounswe/bounswe2018group9#47]
@bounswe/bounswe2018group9 I think we should start preparing agenda for `Meeting #4`. Also, becase we have decided to discuss what have we done last week, ups and downs, we can start filling what we will talk there. Prior to this, we need to make a new page for the meeting documentation. Am I wrong?

**Comment by nazmicancalik** [comment]
@serkan-ozel-2015400123 You are right I am adding meeting 4 page. You can add agenda items there.

**Comment by nazmicancalik** [comment]
I am closing the issue.
__Please add your agenda items to the meeting notes from__ [__here__](https://github.com/bounswe/bounswe2018group9/wiki/Meeting-%234-(26.02.2018))

**Comment by okyksl** [comment]
Should we use specific issues such as this before the meetings to assembly **agenda items** or should we directly open the meeting document and edit the agenda?

**Comment by serkan-ozel-2015400123** [comment]
I think this is useless issue :D

**Comment by okyksl** [comment]
Then from now on, let's open the meeting document and add directly agenda items unless you have an  agenda item which needs discussion.
