### ISSUE TITLE
GitHub Accounts Profile Pictures 

### ISSUE THREAD

**Issue by byklyci** [bounswe/bounswe2018group9#48]
We are **_Actopus Team_**, and we should upload our profile pictures for Github accounts.This is a good point for us, because without pictures accounts seems like boot account. :sweat_smile:

**Comment by serkan-ozel-2015400123** [comment]
Aah, come on man I cant be a robot you know

**Comment by serkan-ozel-2015400123** [comment]
Though you are right. I better add my pic.

**Comment by byklyci** [comment]
Serkan oh my boy, you are handsome guy please add your charismatic picture. :smile:

**Comment by serkan-ozel-2015400123** [comment]
I added my most charismatic, wonder beatiful incredible pic.

**Comment by okyksl** [comment]
Thats the spirit @serkan-ozel-2015400123!

**Comment by akaogluozgur** [comment]
Done.

**Comment by byklyci** [comment]
@didemongu @gkhntkl @gumityolcu can you add your github profile pictures, then ı will close this issue.

**Comment by didemongu** [comment]
I added a pp too.

**Comment by byklyci** [comment]
I am closing that issue.
