### ISSUE TITLE
Wiki Design

### ISSUE THREAD

**Issue by okyksl** [bounswe/bounswe2018group9#5]
Here is some consideration about the design of the Wiki:
* Additional `Authors` section to sidenav will be useful.
* Home page should focus on project content rather than details such as Meetings or Team Members, however it should also be a secondary navigation unit to sidenav for a fluent navigation through Wiki.
* A `Resources` section including pages such as `Repository Examples` and `Git Learning` will be useful. **Organized accumulation** of external resources will save as a lot of time and effort later on.

**Comment by serkan-ozel-2015400123** [comment]
Oğuz all of the things you have mentioned are done actually except we don't have a page like repository examples. However, we have learn git page added and we can add any extra pages to the resources sction as you mentioned. Therefore, if not any change recommendations to our wiki design we can close this issue.

**Comment by nazmicancalik** [comment]
Hi,
After a consideration, sidenav would be better for members and meeting notes.

**Comment by byklyci** [comment]
Now, sidenav includes members and meetings but the home page looks empty in my opinion.

**Comment by byklyci** [comment]
And also for our first meeting documentation ; we talked about adding picture. @didemongu Can you add our picture including our meeting in lounge.

**Comment by okyksl** [comment]
@serkan-ozel-2015400123, should I move the `Researching Repository` under the `Resources` and close the `Homeworks` part?

**Comment by okyksl** [comment]
@bounswe/bounswe2018group9 checkout the `Meetings` page. I plan to add a short passage to the `Home` as well. Any suggestions & ideas about the current design of the wiki?

**Comment by serkan-ozel-2015400123** [comment]
I think we can close wiki design issue right now until some other time.
