### ISSUE TITLE
Meeting #3.1 Notes

### ISSUE THREAD

**Issue by nazmicancalik** [bounswe/bounswe2018group9#51]
I have added Meeting # 3.1 Notes. You can read it [here.](https://github.com/bounswe/bounswe2018group9/wiki/Meeting-%233.1-(23.02.2018)) Please feel free to give feedback. If there is anything I missed, please specify. 

**Note:** I haven't added any action items since that meeting was held to get things done.(Project Plan)

**Comment by byklyci** [comment]
You can add action items, we learn project libre ,especially @okyksl and we had hard times to make some innovation. :sweat_smile:

**Comment by okyksl** [comment]
`Project Libre` was definitely great fun!

**Comment by okyksl** [comment]
I reviewed the [Meeting #3.1](https://github.com/bounswe/bounswe2018group9/wiki/Meeting-%233.1-(23.02.2018)) so let's close this issue.
