### ISSUE TITLE
Project Planning - Milestones

### ISSUE THREAD

**Issue by okyksl** [bounswe/bounswe2018group9#53]
Let's document our project's milestones with these points in mind:

* Explicitly state **objective**.
* State **deliverables** with explanation.

**Comment by serkan-ozel-2015400123** [comment]
@okyksl  If you can add the chart we prepared to wiki page "Project Plan", I can write milestones' objectives etc.

**Comment by serkan-ozel-2015400123** [comment]
I have written milestones under project plan page. Closeing the issue.
