### ISSUE TITLE
Add New Method to Communication Plan: Google Hangouts

### ISSUE THREAD

**Issue by kemaltulum** [bounswe/bounswe2018group9#54]
As we have decided that it is useful having another way of discussing and reviewing things together, I am adding Google Hangouts as another method for our communication plan.

**Comment by kemaltulum** [comment]
This will occur generally on Friday evenings unless we decide otherwise for that week.
Include all the members available at that time when we share the Google Hangouts link on Whatsapp.

**Comment by okyksl** [comment]
I also added `Hangouts` as communication platform to the document.
