### ISSUE TITLE
Project Planning Document Format

### ISSUE THREAD

**Issue by okyksl** [bounswe/bounswe2018group9#57]
* I have reconstructed our project plan document on `TeamGantt` [here](https://prod.teamgantt.com/gantt/schedule/?ids=1068242&public_keys=FEDRISmQt6FI&zoom=d100&font_size=12&estimated_hours=0&assigned_resources=0&percent_complete=0&documents=0&comments=0&col_width=355&menu_view=1&resource_filter=1&name_in_bar=0&name_next_to_bar=0&resource_names=1#user=&company=&custom=&date_filter=&hide_completed=false&color_filter=).
* Due to limitations of free account of [TeamGantt](https://www.teamgantt.com), we can at most have 3 distinct accounts which are able to change the document.
* Also, there are certain tasks need to be done:

- [x] Assign tasks to responsible team members.
- [x] Dependency among the tasks should be linked.
- [x] Review the `Project Design` workflow.

**Comment by okyksl** [comment]
@nazmicancalik could you update us on the latest consensus of `Project Design` section?
Clearly, we should start with `User Stories & Scenarios`.

**Comment by nazmicancalik** [comment]
@okyksl I agree with you. We should put User stories and scenarios to up top of project design subheader.
I think we should try to find our own way of planning.<br/> 
The design tab in my mind is as follows:
* Project Design
   * User Stories and Scenarios
       * Person 1
          * User stories
          * User scenario 
       * Person 2
          * User stories
          * User scenario
       * Person 3
          * User stories
          * User scenario
    * Diagrams
       * Use case Diagrams
       * Use case Diagrams Review
       * Class Diagrams
       * Class Diagrams Review
       * Sequence Diagrams
       * Sequence Diagrams Review
    * Mockups
       * Web Mockup
           * Home Page (Feed)
           * Login Page
           * Guest Feed Page
           * Profile Page
           * Settings Page
       * Web Mockup Review
           * Home Page (Feed) Review
           * Login Page Review
           * Guest Feed Page Review
           * Profile Page Review
           * Settings Page Review
       * Class Diagrams
           * Class Diagram Main Template Preparation
           * Class Attributes
           * Class Methods 
       * Class Diagrams Review
           * Class Diagram Main Template Preparation Review
           * Class Attributes Review
           * Class Methods Review
       * Sequence Diagrams
           * __I couldn't think of any sub headers here we can add later (It is acceptable being fuzzy)__ 
       * Sequence Diagrams Review
   * Cmpe 451 Part
      * Database Design 
      * Web Implementation
          * Customer Feedback
      * Android Implementation
          * Customer Feedback
      * Testing 
      * Presentation


These all comes to my mind for now. 
I think details of the plan is not so important for now. I guess a suitable, not so wrong plan will do for now. However, we should update the plan as the fog disappears and objectives become clear. :)

**Comment by okyksl** [comment]
@nazmicancalik there are `Class Diagrams` and `Sequence Diagrams` both on `Diagrams` section and also `Mockups` section. I assume you intended to put them into the `Diagrams` section.

**Comment by serkan-ozel-2015400123** [comment]
@okyksl  @nazmicancalik  We should add regular project planning just like meetings. Uskudarli said this last lecture

**Comment by gumityolcu** [comment]
I am writing about #64  ::
@okyksl 
I do not know if we will have a second mockup phase. This is due to the fact that we made the plan together, in our group but our deliverables' deadlines are not given according to our plan but according to our course organisation. As a result, there are inconsistencies we can not avoid unless we see the future.

However, I think we should have a second mockup phase when we decide on details like Colors, Fonts, Icons that we will use in the actual product. It would be better to make the decision on these matters in a mockup tool, or maybe a drawing software, before we start developing the real thing.

Since the problem is between our plan and the course plan, we could ask about this to the assistant or the instructor. Or we could just ignore it and modify our plan whenever we see inconsistencies. What do you think? I really can't decide what we should do?

**Comment by gumityolcu** [comment]
After the review process, we decided to add regular review tasks to the project plan in order to keep coordination with the course plan.

a Man/hour table will be prepared. 

The rest of the plan is enumerated and "(Milestone N)" descriptions are added to milestones.

Do you have any other reviews on the project plan?

**Comment by byklyci** [comment]
How can we reach man/hour table? @gumityolcu

**Comment by kemaltulum** [comment]
@byklyci We will be creating man/hour table starting from this week, I think. There are some things to be discussed here: #77

**Comment by okyksl** [comment]
I think current version of the [Project Plan](https://prod.teamgantt.com/gantt/schedule/?ids=1068242&public_keys=FEDRISmQt6FI&zoom=d100&font_size=12&estimated_hours=0&assigned_resources=0&percent_complete=0&documents=0&comments=0&col_width=355&menu_view=1&resource_filter=1&name_in_bar=0&name_next_to_bar=0&resource_names=1#user=&company=&custom=&date_filter=&hide_completed=false&color_filter=) document represent our high-level workflow with good quality.

We still have following problems that I think we should work harder:
* Our project plan does not cover month _May_. Since we don't know what we're going to work on and since we stressed earlier with **The Boss** we are doing _agile development_, I think our plan is adequate for the moment. However, we should carefully monitor our high-level workflow.
* We tend to forget to track and fill our progress, both in [Project Plan](https://prod.teamgantt.com/gantt/schedule/?ids=1068242&public_keys=FEDRISmQt6FI&zoom=d100&font_size=12&estimated_hours=0&assigned_resources=0&percent_complete=0&documents=0&comments=0&col_width=355&menu_view=1&resource_filter=1&name_in_bar=0&name_next_to_bar=0&resource_names=1#user=&company=&custom=&date_filter=&hide_completed=false&color_filter=) and also [Worklog](https://github.com/bounswe/bounswe2018group9/wiki/Worklog). We have to reflect and review what we're doing and use these tools to track our progress **more often and more efficiently**.
