### ISSUE TITLE
Personas Page

### ISSUE THREAD

**Issue by serkan-ozel-2015400123** [bounswe/bounswe2018group9#58]
We should first create personas page in our wiki. Using xtensio lets create our personas first. We should start preparing personas to finish hw4 in normal time. @bounswe/bounswe2018group9

**Comment by serkan-ozel-2015400123** [comment]
We are done with creating seperate issues

**Comment by okyksl** [comment]
@bounswe/bounswe2018group9 I'm creating appropriate pages for `User Stories` and `User Scenarios`.

**Comment by nazmicancalik** [comment]
In my opinion we can open a comibined page  for user scenarios and mockups both included in one page. Later we can add specific pages for mockups.
