### ISSUE TITLE
Personal Log Links

### ISSUE THREAD

**Issue by byklyci** [bounswe/bounswe2018group9#6]
_Due to 12 Feb 2018,_
Don't forget to send your personel effort documentation to our T.A. Can Tunca (can.tunca@boun.edu.tr).

- [x] Gökhan Tekel
- [x] Didem Öngü
- [x] Hamdi Özgür Akaoğlu
- [x] Nazmican Çalık
- [x] İlyas Demirkıran
- [x] Yusuf Kalaycı
- [x] Serkan Özel
- [x] Kemal Tulum
- [x] Galip Ümit Yolcu
- [x] Oğuz Kaan Yüksel

**Comment by okyksl** [comment]
- [ ] Gökhan Tekel
- [ ] Didem Öngü
- [ ] Hamdi Özgür Akaoğlu
- [ ] Nazmican Çalık
- [ ] İlyas Demirkıran
- [ ] Yusuf Kalaycı
- [ ] Serkan Özel
- [ ] Kemal Tulum
- [ ] Galip Ümit Yolcu
- [x] Oğuz Kaan Yüksel

**Comment by okyksl** [comment]
@bounswe/bounswe2018group9

**Comment by okyksl** [comment]
I'm closing this issue as we have finished.
