### ISSUE TITLE
Muhittin Çalışkan - Persona and User Scenario Overview

### ISSUE THREAD

**Issue by akaogluozgur** [bounswe/bounswe2018group9#60]
![Muhitting Çalışkan](https://user-images.githubusercontent.com/25777154/36946674-533e1cf4-1fd1-11e8-8d15-4352b28e52b5.png)

**Remaining Tasks:**
* Photo will be reconsidered.

Feel free to contribute

**Comment by nazmicancalik** [comment]
I have an idea for Muhittin's case:<br/>
Since Muhittin doesn't know much about hobbies, leisure time activities and he hasn't had a passion for something before, we can create a case where Muhittin finds his passion about something different (some event, cultural activity) and it changes his life. Any thoughts ?

**Comment by akaogluozgur** [comment]
@nazmicancalik  I think that is a good idea, I will consider this while writing User Scenario today.

**Comment by serkan-ozel-2015400123** [comment]
I hope Muhittin can find out what is the meaning of joy one day.

**Comment by byklyci** [comment]
I love you uncle Muhittin :sweat_smile:

**Comment by nazmicancalik** [comment]
Other than some typos it seemed okay to me @akaogluozgur . Of course , other members may give feedback as well. Good work, thanks to your effort 👍

**Comment by akaogluozgur** [comment]
- The user story is added.

- The general page is reconstructed.

- Nobody offered anything about the photo so I did not change it.
 
Guess that's all. In a couple, of minutes, this issue will magically vanish as if it were just figments of your imagination.

**Comment by okyksl** [comment]
@akaogluozgur great scenario and good references to _Yalova_! I'm moving your scenario under the [Muhittin's Persona page](https://github.com/bounswe/bounswe2018group9/wiki/Muhittin-Çalışkan).

When you have time, we can together work on:
* Acceptance criteria
* Scenario with mockups
