### ISSUE TITLE
Mockup Pages for Website

### ISSUE THREAD

**Issue by serkan-ozel-2015400123** [bounswe/bounswe2018group9#62]
We are preparing template pages for scenario pictures. 
-Home
-Event Creation Page
-Sign up page
-User home page(Feed,after login)
-User profile settings page
-Maybe trending page(for guests)

@bounswe/bounswe2018group9 

Then we can use these pages and edit them a little to obtain our actual pictures to use in user scenarios. Editing means adding relevant information and also showing what user did in each picture.

Please note that proto.io doesn't provide collaborator feature, so we should create different accounts and then combine the work.
Here is the link of my workspace:
https://pr.to/FXJPJ6/
Also mine: (Yusuf)
https://pr.to/38G44Q/

**Comment by gumityolcu** [comment]
@nazmicancalik @okyksl and I are working on Android mockups.

**Comment by gumityolcu** [comment]
@serkan-ozel-2015400123 Serkan this is great work. Just to remind you: We need a "Sign in with Facebook" button in the signup page.

**Comment by gkhntkl** [comment]
@serkan-ozel-2015400123 that is awesome.I have recognized that Actopus is started with lowercase in Home page.It may not lead any problem,i hope.

**Comment by serkan-ozel-2015400123** [comment]
@gkhntkl I am checking and correcting

**Comment by serkan-ozel-2015400123** [comment]
@gumityolcu  I will add it you're right.

**Comment by nazmicancalik** [comment]
Good work Serkan, keep up the good work :)

**Comment by byklyci** [comment]
I am working on Event Creation Page and you can follow me [here](https://pr.to/38G44Q/)

**Comment by nazmicancalik** [comment]
Good work 👍

**Comment by serkan-ozel-2015400123** [comment]
The only thing left is profile page and @kemaltulum is responsible closing the issue.

**Comment by okyksl** [comment]
@serkan-ozel-2015400123 we might also need a **Map page**. I'll take that job, you guys worked hard enough!
