### ISSUE TITLE
Mockup Pages for Android Application

### ISSUE THREAD

**Issue by nazmicancalik** [bounswe/bounswe2018group9#63]
Guys, I have started doing Android Mockups for the project. Since I have time and also it will be faster if we assign this issue to only one person. I will be creating mockups and sharing their photos here as I go. 

You can reach out to mockups from [here](https://pr.to/SPI6KA/).
Please don't hesitate to correct me if I am mistaken.

**Comment by serkan-ozel-2015400123** [comment]
@nazmicancalik Good work Nazmican. I want to ask something here: Does it matter to use android mockup in scenario or use web mockup?

**Comment by byklyci** [comment]
Actually we can use both of them because differances make sense.

**Comment by nazmicancalik** [comment]
@serkan-ozel-2015400123 Actually Serkan, I understand from the description that we should have on e mockup for web also we should have one mockup for android. We can use 2 different personas for mockup scenarios. Correct me if I'm wrong.

**Comment by nazmicancalik** [comment]
Guys, good news. The updated version of our mockup is alive. Here is the scenario for Ceyda I and @gumityolcu have thought for android:

1) Signs Up with facebook.
2) Picks Interests
3) Feed Page
4) Sees event details
5) Goes to event. 

Umit is done with the scenario and we created android mockup for scenario. All pages (Pages that are going to be used in our scenario) are ready and interactive. I think other groups should continue with web mockup and scenario. 

## Extra
* We will add the scenario and mockup in a single page integrated. And also we will create a gif for Ceyda following her scenario in android mockup. (Gif can be put to mockup page.)

We tried to create something good, hope you guys like it :)

**Comment by byklyci** [comment]
This is amazing thanks your labour. @nazmicancalik @gumityolcu

**Comment by akaogluozgur** [comment]
Great work guys!

**Comment by nazmicancalik** [comment]
Android mockup pages and user (Ceyda) scenario gif is uploaded to the `resources` branch.

**Comment by okyksl** [comment]
Great work @nazmicancalik! I'll integrate changes to the `Wiki`.
