### ISSUE TITLE
Inconsistencies with the Project Plan

### ISSUE THREAD

**Issue by gumityolcu** [bounswe/bounswe2018group9#64]
We weren't expecting to be preparing the mockups this week when we prepared out project plan. Now, I think we should add new tasks for this week in our plan. I propose adding under Mockups "Mockup Draft" and scheduling it to this week. We can then make it a predecessor of the actual mockup tasks. What do you think?

Additionally, we changed the name of the second client persona from İremsu to Ceyda. I corrected it in the plan.

**Comment by okyksl** [comment]
@gumityolcu do you have any information about whether we will have a _second mockup phase_ where we will focus on _user interface and functionalities_ **without considering user scenarios**?

**Comment by okyksl** [comment]
@gumityolcu could you checkout the new structure? I'm closing this as I believe inconsistency you spotted is fixed. Let's discuss _project workflow_ details including my question above on #57.
