### ISSUE TITLE
Repository Overview Readme & Wiki Page 

### ISSUE THREAD

**Issue by byklyci** [bounswe/bounswe2018group9#69]
_As we discussed our last meeting_ [Meeting 5#](https://github.com/bounswe/bounswe2018group9/wiki/Meeting-%235-(05.03.2018));
We need a revision and control check mechanism for our customer.We will make a good paths for very reachable and understandable for guests when they are stalking our repo.
* README image & photo & navigation
* Wiki navigation & restructure
* New icons for our wiki page 
I am waiting from you guys;
* Innovative structures
* Brainstorming
* Repository scan from Github 
 **_Actopus_** is the best team among the whole Bounswe history.:1st_place_medal:

**Comment by kemaltulum** [comment]
I realized that adding icons to wiki page is easier than I expected :octopus: :house: :100: 
We can use these icons in our wiki page, which we have discussed today.
[The complete list of icons is here](https://gist.github.com/rxaviers/7360908)
@didemongu I think, Didem, you can empower these icons in a creative way and make our seen shiny

**Comment by byklyci** [comment]
Guys I made commit docs(readme): add group pictures and personal page link about the groups whole pictures and profile information.To be continued.

**Comment by okyksl** [comment]
@byklyci thanks for the work, could we now focus on **_navigation_** features?

**Comment by gumityolcu** [comment]
@byklyci  @didemongu  The icons look great! Nice work!

**Comment by gumityolcu** [comment]
We don't have links to out user personas/scenarios and our mockups yet, we need to add them

**Comment by byklyci** [comment]
I send the pictures of web and android mockup on sidebar mocups section. @gumityolcu

**Comment by byklyci** [comment]
@okyksl ı am working about the navigation features with the html language and ı will it the readme.md

**Comment by byklyci** [comment]
I also want to add gif about octopus which a social one.Please make me some suggestion about gifs.
@bounswe/bounswe2018group9

**Comment by byklyci** [comment]
[Our actopus gif](https://dribbble.com/shots/3341064-Octopus) will be like that if you like ı will add this octopus:)Actulally it is so cute. In my opinion we should add this.

**Comment by akaogluozgur** [comment]
I think we need to consider about plagiarism. Did you look for creative commons license of the GIF so that we can use it safely?

**Comment by byklyci** [comment]
Yeah it can be a problem but actullay for this week it can be helpful for us and also we can add the resource where is coming from(site,page,who etc.)But you are right and lets think about this situation in our next meeting(Meeting 6).

**Comment by okyksl** [comment]
@byklyci could we also add a table of contents part just like sidebar of the `Wiki` to the `README.md`? I think widgets looks pretty well but we may want to supplement them with additional organized links.

**Comment by byklyci** [comment]
I  am closing this issue because it is done.
