### ISSUE TITLE
Discuss tools that facilitates team-working like Slack, Trello, Google Groups

### ISSUE THREAD

**Issue by serkan-ozel-2015400123** [bounswe/bounswe2018group9#7]
Are we going to use any of them? In meeting action items, Kemal is responsible for setting up slack. That's because I am assigning to Kemal.

**Comment by okyksl** [comment]
I think our usage of Issues until now was efficient and active. I believe additional products to manage the workflow of our project might be overkill - *I'm talking about Trello here* -. Slack on the other hand, might give additional benefits to track less formal dialogues and helps to organize outside of repo file sharing. However, it still feels like overkill - *less than Trello* -.

Any thoughts @kemaltulum?

**Comment by okyksl** [comment]
Also checkout the [Typescript Repository](https://github.com/Microsoft/TypeScript). They use **Projects** section of GitHub, it looks like Trello.

**Comment by okyksl** [comment]
I'm closing this issue until we feel overwhelmed with our current communication platforms.
