### ISSUE TITLE
Requirements & Mockups Synchronization

### ISSUE THREAD

**Issue by serkan-ozel-2015400123** [bounswe/bounswe2018group9#74]
Hi, 

Our requirements is very detailed. However, our mockups don't have all the features in requirements. There are two options here:

1-Without changing main features delete some parts of the requirements.
2-Add those features to mockups.

@bounswe/bounswe2018group9  

I have prepared this report about user requirements and mockups please check it..
[Click](https://1drv.ms/w/s!AmIQ5c_wmGx3kh0KPWYltAi25Wzf)
And this is for system requirement report
[Click](https://1drv.ms/w/s!AmIQ5c_wmGx3kh6MUEMEz9MgzcIj)

**Comment by nazmicancalik** [comment]
@serkan-ozel-2015400123 I will update the mobile mockups.

**Comment by kemaltulum** [comment]
I would like to change web mockups accordingly as well. However, proto.io is very complex for us and we have just few days until the trial ends. For web mockups, I am planning to use a simpler program like powerpoint to draw all the things needed. 
@serkan-ozel-2015400123

**Comment by nazmicancalik** [comment]
@serkan-ozel-2015400123 I read your notes. I have following questions to ask for mobile mockups:

1. Do we really need to take birthday as an input during sign up process ?
2. As you can see in the mobile mockup *Signing up via facebook is already included in the mobile mockup* I didn't understand why did you include Facebook part note (2nd note)

I will add price and some of the other mockup pages for android

**Comment by nazmicancalik** [comment]
* I have added new page for profile settings.
* Added price, upvote, specific time etc.

Things to do: 
Event creation page.

**Comment by byklyci** [comment]
Can we change the sidebar section mockup versions? Because old versions are there. @serkan-ozel-2015400123

**Comment by serkan-ozel-2015400123** [comment]
They are not ready yet I suppose @byklyci. When it is finished we will update them with @dkilyas

**Comment by okyksl** [comment]
@serkan-ozel-2015400123 I believe link you sent is unavailable now. Couples of ideas about the synchronization:

* Do not delete any item from `Requirements Analysis`. If we start deleting items from now, imagine what will happen in `Implementation` part of the project :)
* Mockups are supplementary to the `Requirements Elicitation` process, they don't have any _obligation_ to follow and contain every single item of the `Requirements Analysis`. Therefore, try to overview the main requirements with precision asked by **The Boss** but try not to overkill things and tire yourself.

**Comment by okyksl** [comment]
I think we have a consensus based on what I said above. We have a detailed [Requirements](https://github.com/bounswe/bounswe2018group9/wiki/Requirements-Analysis), which will be very valuable for the upcoming weeks. We should continue to develop it whenever its necessary and also we should make our designs, implementations, tests strictly in correspondence with it _i.e subtracting or editing the [Requirements](https://github.com/bounswe/bounswe2018group9/wiki/Requirements-Analysis) just for the sake of the job is not approved_.
