### ISSUE TITLE
Git Cheat Sheet

### ISSUE THREAD

**Issue by nazmicancalik** [bounswe/bounswe2018group9#75]
Guys, I have created a git cheat sheet wiki page for mostly used git commands. It also includes a `How to` section. You can reach the document from [here](https://github.com/bounswe/bounswe2018group9/wiki/Git-Cheat-Sheet).

For now it only includes branch operations - [Work In Isolation](https://github.com/bounswe/bounswe2018group9/wiki/Git-Cheat-Sheet#work-in-isolation)
But we can add new how to's later. You can specify what can be added more.

**Comment by kemaltulum** [comment]
I read it, it has all the proper details and seems so beneficial. Thank you @nazmicancalik  
I can ask one point just to prove I examined the cheat sheet. :+1 : smile:
The last point in the things we should do in case of a conflict is repeated in the next point. I saw two commits and adds before pushing

**Comment by akaogluozgur** [comment]
I think the guide is very useful. Thanks for your efforts buddy.

**Comment by serkan-ozel-2015400123** [comment]
👍

**Comment by okyksl** [comment]
@nazmicancalik couple of points to look up when you have time:

* I think we should prefer **rebase** over **merging**.
* Could you also add `Pull Request` procedure?

Also if you wish, I can take it from here. Good work!

**Comment by byklyci** [comment]
Man @nazmicancalik this is amazing job.I am the person who has a problem with this situation so much and you solved my problem.So I need to thank you twice. This is the best cheat sheet about Pull Request ever.

**Comment by nazmicancalik** [comment]
@kemaltulum Thanks for heads up, correct me if I'm wrong but I think we should add the changed file to the staging area after resolving the conflicts. I may be severely wrong though 😄 

@okyksl You are right, we can change to rebase if all agree. Also thanks for your help, since I am not so good at the subject it might be better for you to make some additions and revise the document 🙂 

@byklyci Thanks, we can make it better as we go along 😄

**Comment by okyksl** [comment]
@nazmicancalik I revised our [Git Cheat Sheet](https://github.com/bounswe/bounswe2018group9/wiki/Git-Cheat-Sheet), here are some of the things I changed:

* Added links and notes about our complementary sources [Contribution Guide](https://github.com/bounswe/bounswe2018group9/wiki/Contribution-Guide) and [Learn Git](https://github.com/bounswe/bounswe2018group9/wiki/Learn-Git). 
* Added link to [Atlassian Cheatsheet](https://www.atlassian.com/git/tutorials/atlassian-git-cheatsheet) which is a great comprehensive secondary source to our cheatsheet. _By the way, I suggest [Atlassian Tutorials](https://www.atlassian.com/git/tutorials) for also learning git_.
* Edited [How to's](https://github.com/bounswe/bounswe2018group9/wiki/Git-Cheat-Sheet#how-tos) section to make them more comprehensive and detailed.

I think for now, our [Git Cheat Sheet](https://github.com/bounswe/bounswe2018group9/wiki/Git-Cheat-Sheet) is matured enough. Any additional feedback and improvement is welcomed as always :)
