### ISSUE TITLE
Review of User Stories and Personas

### ISSUE THREAD

**Issue by akaogluozgur** [bounswe/bounswe2018group9#76]
First of all, all personas are restructured and some typos are fixed and **Muhittin's age is nerfed from 28 to 35 as you desired.**
## New structures of personas are following:
* First column includes some information about person and photo, Personality, Goals and Frustrations. Since I thought  peoples goals and frustrations are correlated with their personality and information about them.

* Second column includes some defining adjectives about the person and story since in the story, actions taken by person highlights this characteristic of person.

* Third Column includes Bio, Motivation and Story since motivations of people are might be determined by earlier events of person's biography and motivations of person's determines story part of the persona.

**Obviously, new structure of personas has some advantages and disadvantages:**

Advantages:

* As explained above information are grouped based of correlation about them.
* All personas have same structure.
---
Disadvantages:
* In some personas middle column falls short compared the other columns.
* The structure of personas lower some flexibility for example we need to consider the balance of all columns whenever we add something.

## According to my review:
* I think most of the story and personas part is done here. Some little refinement is needed.

[Ceyda Yılmaz Beylice](https://github.com/bounswe/bounswe2018group9/wiki/Ceyda-Y%C4%B1lmaz-Beylice)
* Since requirements are changed little bit, enumeration of acceptance criteria might be changed. I did not change acceptance criteria since I think it is if some enumeration is changed in requirements, we need to fix them instead of change references to it.

[Muhittin Çalışkan](https://github.com/bounswe/bounswe2018group9/wiki/Muhittin-%C3%87al%C4%B1%C5%9Fkan)
* I prepared some mockups and write the mockup scenario, please review this part especially.
* I can increase some of the content if you want me to do.

[Şeyda Karagöz](https://github.com/bounswe/bounswe2018group9/wiki/%C5%9Eeyda-Karag%C3%B6z)
* I can increase the content of story a bit to obtain balance but I think it is good as it is.

Please do not hesitate to offer some recommendations and comments if yours.

**Comment by serkan-ozel-2015400123** [comment]
@akaogluozgur  As you said requirements are changing now, we should update accceptance crit. at the end

**Comment by akaogluozgur** [comment]
Mockups and Mockups scenario is prepared and added corresponding files.

**Comment by byklyci** [comment]
@akaogluozgur thank you for your effort it is a great job. :+1:

**Comment by nazmicancalik** [comment]
@akaogluozgur Thanks, good work :)

**Comment by serkan-ozel-2015400123** [comment]
@okyksl You may be right about Şeyda. The story can be reviewed .

**Comment by okyksl** [comment]
@akaogluozgur could you checkout my feedback on this issue whenever you have available time?

**Comment by akaogluozgur** [comment]
sorry for late response. I will be checking out you feedback soon

**Comment by byklyci** [comment]
I am closing this issue.Thank for the job.

**Comment by okyksl** [comment]
I think we have a very small alteration task that @akaogluozgur will handle in the upcoming days.

**Comment by serkan-ozel-2015400123** [comment]
What is the status here @okyksl  @akaogluozgur

**Comment by okyksl** [comment]
I haven't communicated with @akaogluozgur further on this topic. I see you have changed the order [Şeyda Karagöz](https://github.com/bounswe/bounswe2018group9/wiki/Şeyda-Karagöz) and [Muhittin Çalışkan](https://github.com/bounswe/bounswe2018group9/wiki/Muhittin-Çalışkan), may I ask the reason?

**Comment by akaogluozgur** [comment]
We have already submitted the report, that is the state as you should know as well.

**Comment by serkan-ozel-2015400123** [comment]
`
I see you have changed the order Şeyda Karagöz and Muhittin Çalışkan, may I ask the reason?
`
I thought it would be better. However, it didnt think the references, took it back again.

 `
We have already submitted the report, that is the state.
`
We are done with this until next semester I suppose closing the issue
