### ISSUE TITLE
Man/hour Information Documentation Structure

### ISSUE THREAD

**Issue by kemaltulum** [bounswe/bounswe2018group9#77]
First, let me define what man/hour means with my words. It is the number of hours one would spend on a given task.

There are three basic benefits for us:
*  Specifying man/hour for any task, we can divide the total work more fairly.
*  Trying to specify the man/hour for tasks pushes us to better understand the content of the task. We would be more conscious about what the task requires.
* We can foresee for a job that requires more people to be done in time. For example, if a task needs 10 man/hour, that task is assigned by at least 3 people.

**Note:** Teamgantt does not enable us specifying mah/hour information for the tasks, since it has some restrictions for free usage.

I would like to discuss the structure of the document for man/hour information. 

|    ID    | Who | What | Deadline | Man/hour |
| :------: | :-: | :--: | :------: | :----: |
| **4.1** | Nazmican | Prepare git command manual | 11.03.2018 | 4 man/hour |
| **4.2** | Oğuz Kaan | Arrange meeting notes after the meeting | 09.03.2018 | 2 man/hour |

This is the table we keep actions for each meeting. We can add a new column for man/hour info. This should actually be discussed further in the meeting, since we had another column suggestion for this table in the last meeting.

The key point in here is that we should divide tasks as separate as possible so that we can specify man/hour information and effectively distribute tasks.

When this information is kept regularly in the meetings I can keep a separate document like this

|    ID    | Who | Week 5 | Week 6 |
| :------: | :-: | :--: | :------: | 
| **1** | Kemal | 3 man/hour|  4 man/hour | 
| **2** | Yusuf | 2 man/hour | 5 man/hour | 

Today, in the problem session maybe, I will be discussing this topic with our customer Meriç, then we can  finalize the details in the meeting.

**Comment by okyksl** [comment]
@kemaltulum as we discussed on [Meeting #5](https://github.com/bounswe/bounswe2018group9/wiki/Meeting-%235-(05.03.2018)) **3.2.**, I updated the meeting documentation format to include a status section, can you check it out?

Here are some of the points on this issue:
* Estimating **workload** for tasks are a must do, I believe meetings are ideal times for estimation.
* Status section of next week's meeting, can cover areas such as _what's the status of the task, when its finished, how many hours spends on that task_. However I don't think its a good idea to make our meeting documents the _main tracking point_ of **resource allocation and workload**. Meeting documents should include _solely the content of meetings_.
* Thus, I suggest an additional `Workload Table` under the `Project Plan` section where we can _meticulously_ **follow resource allocation and workload**.

**Comment by kemaltulum** [comment]
@okyksl As you point out, adding extra column to our meetings action table would not be ideal. `Workload Table` is a decent idea, I can create one today and we can start updating it in the meeting.

**Comment by okyksl** [comment]
Actually, I created a [Worklog Page](https://github.com/bounswe/bounswe2018group9/wiki/Worklog) which is accessible under the [Project Plan](https://github.com/bounswe/bounswe2018group9/wiki/Project-Plan).

**Comment by kemaltulum** [comment]
I made the planned changes. The final structure of the document can be found under Project Plan, [Worklog](https://github.com/bounswe/bounswe2018group9/wiki/Worklog). Since the structure is clear now, I am closing the issue
