### ISSUE TITLE
Setup README.md

### ISSUE THREAD

**Issue by serkan-ozel-2015400123** [bounswe/bounswe2018group9#8]
We also decided to set up readme.md file. "According to Github's official document on README.md and our repository needs, README.md should include sections such as Project Name, Description, Contributing, Credits." This is the discussion item we do have. The assignees of this issue are the responsibles for this action item. 

We can write something like that : "

We are currently working on this repository for CMPE352(Fundamentals of Software Engineering) and CMPE451(Development in Software Engineering) courses in Bogaziçi University."

as the others do, and changing the background color adding some other things etc.

**Comment by akaogluozgur** [comment]
I am checking out the Github's official document right now. Changes will be added tomorrow.

**Comment by gumityolcu** [comment]
I added the group members and links to our pages in the wiki. I will upload the document when everyone has created their pages.

I think several major updates will be made to the README file once we get the project, we can not do much until then.

**Comment by byklyci** [comment]
Nice job. Thank you..

**Comment by nazmicancalik** [comment]
Should we close the issue, since we don't have something to add for now, or should we wait for addition of  **contributing** wiki page issue #11 so that we can add the **contributing page link** to the readme file.

**Comment by okyksl** [comment]
@nazmicancalik, sorry for the late response. I think we should close the issue since _initial structure of the **README.md**_ is finished. Any additional change for the **README.md** can be tracked from its specific issue from now on.
