### ISSUE TITLE
Updating Worklog Page Weekly

### ISSUE THREAD

**Issue by kemaltulum** [bounswe/bounswe2018group9#80]
Even though it is certainly an extra job, we should log what we do in a week in [Worklog](https://github.com/bounswe/bounswe2018group9/wiki/Worklog) under [Project Plan](https://github.com/bounswe/bounswe2018group9/wiki/Project-Plan) for some reasons:
* It would be really helpful for managing resources of us. I mean, logging the work we are doing, we will be more aware of what we have been doing so far.
* We should do it since it is asked by our customer :disappointed: 

We should fill the following table with the work we have done and its workload. This type of table exists for each week. We should log the work we have done based on the task given in the meeting and also the extra works. 

* For new tasks, not mentioned in the meeting, you can enumerate new tasks
* Feel free to add new lines for a single task to clarify what is done within the task.

| Resource | Task | Log | Workload (man-hour) |
| :------: | :--: | :-: | :------: |
| Kemal Tulum | **4.x.1.** | Update Worklog Structure | 0.5 | - | - |
| Kemal Tulum | **4.x.2.** | Prepare Worklog Update Wki | 0.5 | - | - |
| Nazmican Çalık| **4.x.1.** | Git Command Manual | 3 | - | - |

At the end of the semester, we are asked to fill such a table:

| Who | Workload (man-hour) |
| :-: | :----: |
| Nazmican Çalık | x hours |
| Gökhan Tekel | x hours |
| Didem Öngü | x hours |
| Hamdi Özgür Akaoğlu | x hours |
| İlyas Demirkıran | x hours |
| Yusuf Kalaycı | x hours |
| Serkan Özel | x hours |
| Kemal Tulum | x hours |
| Galip Ümit Yolcu | x hours |
| Oğuz Kaan Yüksel | x hours |

We are all working hard, let's just report them in the worklog tables for any week.

There would be unclear situations, please ask them in here.

**Comment by byklyci** [comment]
Will we report last week 's(week 5 ) workload also? Or Is milestone of starting is this week? @kemaltulum

**Comment by okyksl** [comment]
@byklyci I don't think we have realistic estimations of `Week #5`, let's focus on what we can do: `Week #6` and later.

@kemaltulum should we have a _fixed task_ with id `4.0` named **Reflect & Review & Feedback** to contain that types of workload?

**Comment by okyksl** [comment]
I reserved **4.0.** as stated above.

@bounswe/bounswe2018group9 I see that most of us, _including me_, forgets to fill the [Worklog](https://github.com/bounswe/bounswe2018group9/wiki/Worklog) table. Please be more sensitive to report and track your work, I guarantee you it will help you with work segregation and timing.

With that being said, from now on we will **strictly** follow [Worklog](https://github.com/bounswe/bounswe2018group9/wiki/Worklog) and `Meeting Status` to track our progress and resource usage. Be sure to catch up!
