### ISSUE TITLE
The Choice of Sequence Diagram Drawing Tool

### ISSUE THREAD

**Issue by kemaltulum** [bounswe/bounswe2018group9#81]
Sequence diagrams are complex graphs. We would be using some tools.

Choosing criteria for the tools:
* Weather the diagram can be exported or not
* Pricing plan of the tool, basically it should be totally free

 Let's discuss the tools available here.

**Comment by kemaltulum** [comment]
Here the tools that I found at first and suggested in the meeting:
* [LucidChart](https://www.lucidchart.com/)
* [MermaidJS](https://mermaidjs.github.io/sequenceDiagram.html)
* [XMind](https://www.xmind.net/zen/)
* [UMLet](http://www.umlet.com/)

Please comment on them

**Comment by nazmicancalik** [comment]
@kemaltulum  I checked these tools you have sent. @akaogluozgur  and @byklyci have picked Lucid Chart for **Class Dİagrams** as far as I remember. They may give us an idea about its pros and cons.

**Comment by byklyci** [comment]
Yeah, we choose for Lucid Chart for class diagrams and I think it is an efficient platform.Also you can share the document via email. @kemaltulum

**Comment by gkhntkl** [comment]
@kemaltulum @didemongu Then,i have started LucidChart.

**Comment by kemaltulum** [comment]
@gkhntkl I think, it is OK. But we should first determine for which use cases we will draw sequence diagram, which is an another issue. Closing this one...

**Comment by okyksl** [comment]
@kemaltulum sorry for the inconvenience, is [LucidChart](https://www.lucidchart.com) free? I couldn't find the free registration option for _university emails_.
