### ISSUE TITLE
Sequence Diagram Design

### ISSUE THREAD

**Issue by gkhntkl** [bounswe/bounswe2018group9#86]
I have two ways of drawing scenarios,one of them is the following style;

### Authentication
* Sign-Up  
* Sign-In  
### Profile
*  Edit Profile  
*  Timeline
* Feed Page
* Trending Page
* Create Event
* Edit Event
* Post Comment,Vote
* Search

the other one is by dividing the scenarios into 3 sub-parts where each one refers to admin,user and guest.

1-some use cases for admin
     .
     .
2-some use cases for registered user
     .
     .
3-some use cases for guest
     .
     .

Which one should we choose? Or if you had other propasal,please share it.
thank you.

**Comment by gkhntkl** [comment]
I have two ways of drawing scenarios,one of them is the following style;

### Authentication
* Sign-Up  
* Sign-In  
### Profile
*  Edit Profile  
*  Timeline
* Feed Page
* Trending Page
* Create Event
* Edit Event
* Post Comment,Vote
* Search

the other one is by dividing the scenarios into 3 sub-parts where each one refers to admin,user and guest.

1-some use cases for admin
     .
     .
2-some use cases for registered user
     .
     .
3-some use cases for guest
     .
     .

Which one should we choose? Or if you had other propasal,please share it.
thank you.

**Comment by serkan-ozel-2015400123** [comment]
I think we should provide use cases for all the functionality of all the user types. @gkhntkl . Based on use cases, we need sequence diagrams of them.

**Comment by serkan-ozel-2015400123** [comment]
@gkhntkl was working on them recently. I learned that @kemaltulum @didemongu were not very active when I asked. Can you send some of the sequence diagrams @gkhntkl ? And maybe I  can start doing some of them tomorrow.

**Comment by kemaltulum** [comment]
@serkan-ozel-2015400123 It is not just a matter of doing it, but understanding and implementing it in the most genuine way possible. In this regard, we are not being inactive at all. 

We discussed the details of the sequence diagrams with @gkhntkl The entities in the sequence diagrams should match the ones in the class diagram. Therefore, not being able to examine the Class Diagram is a considerable problem. On the other hand, I have prepared some drafts, which will be in here within hours.

**Comment by akaogluozgur** [comment]
I am integrating the Class Diagram [here](https://github.com/bounswe/bounswe2018group9/wiki/Class-Diagrams). Whole information will be available tonight.

**Comment by gumityolcu** [comment]
I believe this is very useful for this matter : http://www.tracemodeler.com/articles/a_quick_introduction_to_uml_sequence_diagrams/

**Comment by gumityolcu** [comment]
Set of example UML Sequence Diagrams:
http://www.tracemodeler.com/gallery/index.html

**Comment by nazmicancalik** [comment]
@gumityolcu thanks for the link Ümit :+1:

**Comment by nazmicancalik** [comment]
Okay guys maybe we should open another issue and follow the remaining sequence diagrams from there

**Comment by serkan-ozel-2015400123** [comment]
Some of us dont know actually what a sequence diagram is .I learned from internet that vertical blocks are for messages only. Not for object lifeline. That is it is drawed when there is a interaction between two objects. I highly recommend all of us to read one complete tutorial about sequence diagram. For example, you can use dashed line for indicating the object lifeline.

**Comment by serkan-ozel-2015400123** [comment]
http://www.tracemodeler.com/articles/a_quick_introduction_to_uml_sequence_diagrams/

**Comment by okyksl** [comment]
@bounswe/bounswe2018group9 can you state your work on #91 and also can you please start to integrate your changes to the [Sequence Diagrams](https://github.com/bounswe/bounswe2018group9/wiki/Sequence-Diagrams)?

**Comment by okyksl** [comment]
As @serkan-ozel-2015400123 pointed out, we started to work on diagrams without the _concern of user type_. As @nazmicancalik pointed out, we started to work on `Sequence Diagrams` on specific issues. In this coming week, we will review & revision `Sequence Diagrams` for _synchronization and qualification_ purposes.
