### ISSUE TITLE
Admin panel requirements

### ISSUE THREAD

**Issue by serkan-ozel-2015400123** [bounswe/bounswe2018group9#87]
Dear friends, what else can we add ?

#### 1.2.4 Admin Panel
* **1.2.4.1.** The system shall provide an admin panel for admins with privileged rights
  * **1.2.4.1.1** An admin shall be able to delete or edit events.
      * **1.2.4.1.1.1** An event shall be deleted when it contains illegal contents in 1.2.4.1.2.2.
      * **1.2.4.1.1.2** An event shall be deleted when it is not an actual event but used for another purpose like advertisement.
      * **1.2.4.1.1.3** An event should be blocked for a day when it contains illegal contents in 1.2.4.1.2.2. This is for user to change the content without removing the event.
  * **1.2.4.1.2** An admin shall be able to block a user from logging a specific amount time.
      * **1.2.4.1.2.1** A member user shall be blocked for a day when he or she spams messages and disturbs other users.
      * **1.2.4.1.2.2** A member user shall be blocked for an appropriate time based on what he or she has done when he or she sends illegal contents like pornography, criminal activities.
  * **1.2.4.1.3** An admin shall be able to view emails came from users. 
       * **1.2.4.1.4** An admin shall be able to respond the emails. The admin shall respond in 2 days.

**Comment by okyksl** [comment]
I'm not so sure about whether _Admin actions_ belong to the **1.2.** or not.

We can add a _should type_ requirement such as:

> Admin should be able to verify celebrity accounts as official.

**Comment by serkan-ozel-2015400123** [comment]
@okyksl  Okay you are right. Should I move it to 1.1? This will affect references I guess if there is one about admin panel

**Comment by okyksl** [comment]
I believe the right place would be under **1.1.**, could you cross-check with other groups covering _Admin type of stuff_?

**Comment by serkan-ozel-2015400123** [comment]
There is not any admin panel in group 6. @okyksl However group 3 has put it under user req. I will do it also please be informed that you may need to change references to requirements. @bounswe/bounswe2018group9

**Comment by nazmicancalik** [comment]
@serkan-ozel-2015400123  Adding the requirements is good but do we need to specifically implement Admin Panel for the project. Because as you know it comes with a great responsibility. What are the criteria of customer Meriç's?  Was there any specific request for an admin panel ?

**Comment by nazmicancalik** [comment]
I have asked our customer about the focus we should give on admin panel issue: He simply replied:

You don't need to focus on that too much.

Best,
Meriç Turan

**Comment by nazmicancalik** [comment]
Guys I am getting an impression that we are losing too much time on details, lets discuss and clarify our detail levels on the next meeting so that we don't bore ourselves at the early stages of this 2 course span project. We need our stamina for more key aspects of the project. Thanks :D

**Comment by okyksl** [comment]
@nazmicancalik @serkan-ozel-2015400123 I think we can still retain **Admin Panel** requirements, but let's make them **should** instead of **shall**.

**Comment by serkan-ozel-2015400123** [comment]
@okyksl Done

**Comment by okyksl** [comment]
Let's close this issue as its resolved.
