### ISSUE TITLE
Web Mockup Review

### ISSUE THREAD

**Issue by gumityolcu** [bounswe/bounswe2018group9#89]
Hello, I looked at the second version of web mockups prepared by @dkilyas. Great work on managing the tab structure on the left and adding chat section to the right. This is awesome! Here is my feedback:

**PAGES WE NEED TO EDIT**
1. In Event Creation Page:
- 1.1.6.7.3 : We need a Duration section

2. In Event Details Page:
- Currently, there are two events in this page. This page should be unique for an event in the system. I couldn't find a corresponding requirement but I think you will agree 😄 
- Instead of "name surname" we should have "event title". This is also does not correspond to a requirement.
- 1.1.3.3.1.: There should be space for event description
- 1.1.1.: There should be two versions of this page, for Guests (who can't share/comment/vote/post photos/attend/not attend) and for Members.
- 1.1.3.3.5.: Users shall be able to post/view photos about and event

3. In Unregistered Trending Pages:
- 1.1.1.7.: Guests shall not be able to mark attendance information about events. Actually I added this requirement just right now but I think it is necessary and logical.

4. In the Settings Page(ProfileInfo in Proto.io):
- 1.1.8.1.: We need a way to verify an account
- 1.1.3.1.2.: We need a way to change activity preferences. We just need a button to add and delete activities.
- 1.1.5.2.: We need a way to block someone

5. Messaging:
- I think it is a great idea to integrate Messaging with a chat mechanism. I personally don't think we need a mockup showing the chatting process because it's pretty straightforward. What do you think?

**PAGES WE NEED TO ADD**

We need a Profile Page. I think you prepared Settings(ProfileInfo) and Attended Events(ProfileEventsAttended) pages but I think these do not correspond to a Profile page -that is the page of a profile seen by another user-.

Thus I think we need to add 3 pages : 
1. Unverified public profile page
2. Verified public profile page
3. Protected(not public) profile page

All these pages should include a Follow and Message buttons.

**Comment by dkilyas** [comment]
Thanks for your feedback. I made the corrections on the pages according to your feedback.
With this link you can see the last version of the web mockups:
[https://pr.to/TLA0RY/](url)
1. In Event Creation Page:

- [ ] 1.1.6.7.3 : We need a Duration section

2. In Event Details Page:

-  I thought that there should be blocks that tell some details of the event. Seeing every detail of every event on the home page or on the trend page may be disturbing. This summary blocks will provide necessary information about the user. At that point, if the user wants to see other details of the event, then the user will open the detailed page of the event. The most important advantage of the summary block is that the user will not be disturbed by reading/seeing the details of every event and the choice will be up to the user.

- [ ] 1.1.3.3.1.: There should be space for event description

- [ ] 1.1.1.: There should be two versions of this page, for Guests (who can't share/comment/vote/post photos/attend/not attend) and for Members.

- [ ] 1.1.3.3.5.: Users shall be able to post/view photos about and event

3. In Unregistered Trending Pages:

- [ ]  1.1.1.7.: Guests shall not be able to mark attendance information about events. Actually I added this requirement just right now but I think it is necessary and logical.

4.In the Settings Page(ProfileInfo in Proto.io):

- I think that is too specific. It can be added later on.

5. Messaging

- I think that way too. But I added the message page :D


- [ ] The page of a profile seen by another user

**Comment by gumityolcu** [comment]
Proto says that the link is invalid. Any ideas on the source of this problem? Can you give another link @dkilyas ?

**Comment by dkilyas** [comment]
Just copy paste the link it will work. @gumityolcu

**Comment by okyksl** [comment]
@gumityolcu @dkilyas just to check, do we also cover _annotations_?

**Comment by serkan-ozel-2015400123** [comment]
@okyksl @dkilyas   I agree. We should put annotation option. There should be a option to write some text or add another photos attached to some part of the event photos.

**Comment by gumityolcu** [comment]
@okyksl @dkilyas @serkan-ozel-2015400123 I reviewed the web mockups using the Android mockups, where I forgot the annotations. Thus I forgot them again, we need annotations in the web mockups 😄 Sorry for that.

**Comment by nazmicancalik** [comment]
@gumityolcu  I have added the annotations to android mockups now. It is simply a button saying that add annotations. I don't think it should be more specific than that.
Since after those much detail, it becomes designing the webpages. I think only mentioning them is even adequate.

**Comment by okyksl** [comment]
@gumityolcu @dkilyas could you inform us on status of this issue?

**Comment by byklyci** [comment]
@dkilyas the new proto.io work is wonderful in my opinion.Can you add our team logo which is your drawings in your free time? And ı saw some new symbols about **_Actopus_**. :+1:  Thank you

**Comment by byklyci** [comment]
I am closing this issue. Thanks for the job.
