### ISSUE TITLE
Sequence Diagram - Sign-Up

### ISSUE THREAD

**Issue by gkhntkl** [bounswe/bounswe2018group9#94]
![1](https://user-images.githubusercontent.com/32368789/37873747-41ed479e-302b-11e8-99ca-db379fe448f9.png)

Sign-Up is ready.Check it out whether it okay or not,please.

**Comment by gumityolcu** [comment]
I believe instead of writing "valid credential syntax and "user exists" in the little rectangles, we should write "alt" -meaning alternative- and below the little rectangle we should write [valid credential syntax] and [existing user].

Apart from that, I think it is great!

**Comment by gumityolcu** [comment]
Oh, and I think in the second if, you should write [user doesn't exist] instead of [user exists].

**Comment by serkan-ozel-2015400123** [comment]
Yeah I agree with Ümit.  According to the link, Ümit posted to whatsapp there should not be a text at those corners of boxes. Rather it should be below of the corner as far as I remember.

I am okay if instructors will be okay with this. @kemaltulum  @gumityolcu

**Comment by gkhntkl** [comment]
@gumityolcu @serkan-ozel-2015400123 that is handled,thanks.

**Comment by nazmicancalik** [comment]
Good job @gkhntkl :+1:
