### ISSUE TITLE
Sequence Diagram - Search

### ISSUE THREAD

**Issue by didemongu** [bounswe/bounswe2018group9#97]
![search 1](https://user-images.githubusercontent.com/36166597/37879346-40f47cd6-3080-11e8-8c60-c3381066cf63.png)

https://www.lucidchart.com/invitations/accept/6a8db999-e181-4273-b940-ac59499a6b0a

Here is the sequence diagram for search and its link. I wait for your feedback.

**Comment by gumityolcu** [comment]
Hey I edited it a bit, added lines indicating the lifetime of objects and added a loop structure to where we return arrays.

**Comment by didemongu** [comment]
Good work. I put it to wiki so I close issue.
