### ISSUE TITLE
Accceptance Testing

### ISSUE THREAD

**Issue by serkan-ozel-2015400123** [bounswe/bounswe2018group9#98]
Hey guys. We are goint to prepare acceptance tests this week. I think we can use the pattern in the last link of homework. Let us use the same format for our tests. 

Currently we are deciding which test cases we will consider. 
1- Create an event
2- Change profile
3- Attend an event
4- Follow a user
5-Search event
6- Recommendation(should be more concrete I guess)
7- Send message to a friend
8- Annotate

Are they enough or unnecessary? 
 @gkhntkl @dkilyas @byklyci

**Comment by nazmicancalik** [comment]
Just an idea; You guys can design test cases for specific settings cases such as changing password, change profile pic etc. :D

**Comment by byklyci** [comment]
I am taking **1.Create an event** and **4.Follow a user** test cases  if there is no problem for you guys..

**Comment by serkan-ozel-2015400123** [comment]
I agree with nazmican. So there will be more cases for edit profile. In this case it will be harder than certain tests. We should make a fair distribution

**Comment by byklyci** [comment]
As ı said I started to make test cases such as **1.Create an event** and **4.Follow a user**  and ı will open an issue about it. Give your comment and feedbacks about these.

**Comment by byklyci** [comment]
You can achieve test case which create an event anf follow a user here #99

**Comment by serkan-ozel-2015400123** [comment]
If you are okay with I am taking edit profile and attend an event 2,3 @byklyci @gkhntkl @dkilyas

**Comment by serkan-ozel-2015400123** [comment]
Let's use this markdown template which is in this page. 

https://github.com/bounswe/bounswe2018group9/wiki/Test-Case-Template

I prepared it according to https://images.template.net/wp-content/uploads/2015/12/29053639/Test-Case-Template-PDF.pdf link which our instructor has sended.

**Comment by byklyci** [comment]
I am closing this issue because we seperated task and made our job.
