### ISSUE TITLE
Test Cases (Create an event)

### ISSUE THREAD

**Issue by byklyci** [bounswe/bounswe2018group9#99]
Hey guys. We are going to prepare acceptance tests this week. I need your comment and feedbacks about as follows:

**_a- Create an event
b- Follow a user_**

I will add my work here and the final version will add our repository after the final task prepared.

**Comment by okyksl** [comment]
@byklyci wouldn't it be better to create separate issue for each test case?

**Comment by byklyci** [comment]
It can be better ı will do it @okyksl

**Comment by byklyci** [comment]
# Final version is:

<p>Test Case #1</p>

<p><b>Create an Event</b>: …</p>

<p><b>Description</b>: Test if users can create events.</p>

<p><b>Design Time</b>: 01.04.2018</p>

<p><b>Designed by</b>: Yusuf Kalaycı</p>

<p><b>Execution Time</b>: …</p>

<p><b>Executed by</b>: …</p>

<p><b>Related Requirement</b>: 
* Events  (Requirements 1.2.6)
* System shall store attendance information for passed events, either attended or not.(Req:1.2.6.2)
* createEvent() (Requirement 1.1.6.1.2. )
* getAttendance()  (Requirement: 1.1.6.3.)
* setComment() (Requirements: 1.1.9.1.)
* setTag() (Requirements: 1.1.6.2.)
* setLocation() (Requirements: 1.1.6.7.)
* setVote() (Requirements: 1.1.6.4.)





</p>

<p><b>Preconditions</b>: 

User is a member of actopus.
User have successfully signed in and navigated into setting/profile page.


<p>

<p><b>Steps</b>:</p>

* Go to event creation 
* Choose event 
* Enter requirement information
* Click save 

<table>

<tr>

<td> Step </td>

<td> Action </td>

<td> Expected System Response </td>

<td> Pass/Fail </td>

<td> Comment </td>

</tr>

<tr>

<td> 1 </td>

<td> Go to event creation </td>

<td> Show whole event with their title </td>

<td> – </td>

<td> – </td>

</tr>

<tr>

<td> 2 </td>

<td> Choose event  </td>

<td> Choose event among the events on the page</td>

<td> – </td>

<td> – </td>

</tr>

<tr>

<td> 3</td>

<td> Enter requirement information </td>

<td> Show entered information </td>

<td> – </td>

<td> – </td>

</tr>
<tr>

<td> 4 </td>

<td> Click save </td>

<td> Check if the data are valid. If so, All the changes are stored. memberUser.update(information) is called. Else go to 1 and display error message.  </td>

<td> – </td>

<td> – </td>

</tr>



<tr>

</table>

<p><b>Postconditions</b>: The corresponding changes have been made by the system and stored to remember the changes.</p>

**Comment by byklyci** [comment]
I am closing because it is done.
